#!/usr/bin/env python3
"""Merge multiple CDL captures into a combined function set."""

import csv
import sys
import os

def load_csv(path):
    funcs = {}
    with open(path) as f:
        for line in f:
            if line.startswith('addr,'):
                break
        reader = csv.DictReader(
            f,
            fieldnames=['addr', 'name', 'size', 'code_bytes', 'code_pct',
                         'read_bytes', 'write_bytes'],
        )
        for row in reader:
            funcs[row['addr']] = {
                'name': row['name'],
                'size': int(row['size']),
                'code_bytes': int(row['code_bytes']),
                'read_bytes': int(row['read_bytes']),
                'write_bytes': int(row['write_bytes']),
            }
    return funcs


def main():
    base = os.path.dirname(os.path.abspath(__file__))
    root = os.path.join(base, '..', '..')
    build = os.path.join(root, 'build')

    captures = {
        'rolling_start': load_csv(os.path.join(build, 'cdl_racing.csv')),
        'steering_crash': load_csv(os.path.join(build, 'cdl_racing_input_variant.csv')),
        'auto_gears': load_csv(os.path.join(build, 'cdl_racing_gears.csv')),
        'manual_gears': load_csv(os.path.join(build, 'cdl_racing_manual_gears.csv')),
    }
    menu = load_csv(os.path.join(build, 'cdl_menu.csv'))

    # Merge: take max code_bytes across all captures
    all_addrs = set()
    for c in captures.values():
        all_addrs.update(c.keys())

    merged = {}
    for addr in all_addrs:
        best_code = 0
        best_name = ''
        best_size = 0
        best_read = 0
        best_write = 0
        for c in captures.values():
            if addr in c:
                entry = c[addr]
                if entry['code_bytes'] > best_code:
                    best_code = entry['code_bytes']
                    best_name = entry['name']
                    best_size = entry['size']
                best_read = max(best_read, entry['read_bytes'])
                best_write = max(best_write, entry['write_bytes'])
        merged[addr] = {
            'name': best_name,
            'size': best_size,
            'code_bytes': best_code,
            'read_bytes': best_read,
            'write_bytes': best_write,
        }

    # Categorize
    menu_code = {a for a, e in menu.items() if e['code_bytes'] > 0}
    racing_code = {a for a, e in merged.items() if e['code_bytes'] > 0}

    racing_only = sorted(racing_code - menu_code)
    shared = sorted(racing_code & menu_code)
    menu_only = sorted(menu_code - racing_code)

    total_racing_bytes = sum(merged[a]['code_bytes'] for a in racing_only)
    total_shared_bytes = sum(merged[a]['code_bytes'] for a in shared)

    print(f"RACING_ONLY: {len(racing_only)} functions, {total_racing_bytes:,} code bytes")
    print(f"SHARED: {len(shared)} functions, {total_shared_bytes:,} code bytes")
    print(f"MENU_ONLY: {len(menu_only)} functions")

    # Write combined CSV
    csv_path = os.path.join(build, 'cdl_racing_combined.csv')
    with open(csv_path, 'w', newline='') as f:
        f.write('addr,name,size,code_bytes,code_pct,read_bytes,write_bytes,category\n')
        for addr in sorted(all_addrs | menu.keys()):
            e = merged.get(addr, {'name': '', 'size': 0, 'code_bytes': 0,
                                   'read_bytes': 0, 'write_bytes': 0})
            if addr in menu and menu[addr]['size'] > e['size']:
                e['size'] = menu[addr]['size']
                if not e['name']:
                    e['name'] = menu[addr]['name']
            if e['code_bytes'] == 0 and (addr not in menu or menu[addr]['code_bytes'] == 0):
                continue
            cat = ('SHARED' if addr in shared
                   else ('RACING_ONLY' if addr in racing_only else 'MENU_ONLY'))
            pct = (e['code_bytes'] / e['size'] * 100) if e['size'] > 0 else 0
            f.write(f"{addr},{e['name']},{e['size']},{e['code_bytes']},{pct:.1f},"
                    f"{e['read_bytes']},{e['write_bytes']},{cat}\n")
    print(f"Combined CSV: {csv_path}")

    # Write function_set.md
    lines = []
    lines.append('# Driving Model Function Set (CDL-Validated)')
    lines.append('')
    lines.append('Generated by merging 4 empirical CDL captures (`merge_cdl.py`):')
    lines.append('- **Rolling start**: 300 frames idle at race start')
    lines.append('- **Steering + crash**: ~1,746 frames — left turns, grass, wall collisions')
    lines.append('- **Auto gears**: ~2,194 frames — gas/idle/brake cycles, auto transmission')
    lines.append('- **Manual gears**: ~1,732 frames — manual transmission, UP/DOWN gear shifts')
    lines.append('')
    lines.append('CDL records which bytes the CPU executed during racing vs menu idle.')
    lines.append('Threshold: 2+ code bytes = exercised.')
    lines.append('')
    lines.append('## Summary')
    lines.append('')
    lines.append('| Category | Functions | Code Bytes |')
    lines.append('|----------|-----------|------------|')
    lines.append(f'| RACING_ONLY | {len(racing_only)} | {total_racing_bytes:,} |')
    lines.append(f'| SHARED | {len(shared)} | {total_shared_bytes:,} |')
    lines.append(f'| MENU_ONLY | {len(menu_only)} | — |')
    lines.append('')

    # RACING_ONLY table
    lines.append(f'## RACING_ONLY ({len(racing_only)} functions)')
    lines.append('')
    lines.append('These execute during racing but NOT during menu idle.')
    lines.append('This is the driving model + racing-specific code.')
    lines.append('')
    lines.append('| Address | Name | Size | Code Bytes | Coverage |')
    lines.append('|---------|------|------|------------|----------|')
    for addr in racing_only:
        e = merged[addr]
        pct = (e['code_bytes'] / e['size'] * 100) if e['size'] > 0 else 0
        lines.append(f"| {addr} | {e['name']} | {e['size']} | {e['code_bytes']} | {pct:.1f}% |")

    lines.append('')

    # SHARED table
    lines.append(f'## SHARED ({len(shared)} functions)')
    lines.append('')
    lines.append('These execute during both racing and menu — system/utility code.')
    lines.append('')
    lines.append('| Address | Name | Size | Code Bytes | Coverage |')
    lines.append('|---------|------|------|------------|----------|')
    for addr in shared:
        e = merged[addr]
        pct = (e['code_bytes'] / e['size'] * 100) if e['size'] > 0 else 0
        lines.append(f"| {addr} | {e['name']} | {e['size']} | {e['code_bytes']} | {pct:.1f}% |")

    md_path = os.path.join(base, 'function_set.md')
    with open(md_path, 'w', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"function_set.md updated: {md_path}")


if __name__ == '__main__':
    main()
