void FUN_0600A000(void) { }
void FUN_0600A478(void) { }
void FUN_0600A614(void) { }
void camera_car_transform_setup(void) { }
void course_specific_renderer(void) { }
void camera_position_lerping(void) { }
void race_state_machine(void) { }
void race_utility_calc(void) { }
void FUN_0600C286(void) { }
void FUN_0600C7D8(void) { }
void FUN_0600C8D0(void) { }
void vehicle_state_physics(void) { }
void finish_line_display(void) { }
