/* camera_lerp -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0600B4D2 - 0x0600B6A0
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0600B4D2


    .global camera_lerp
    .type camera_lerp, @function
camera_lerp:
    mov.l r14, @-r15
    mov.l r13, @-r15
    mov.l r12, @-r15
    mov.l r11, @-r15
    mov.l r10, @-r15
    mov.l r9, @-r15
    sts.l pr, @-r15
    add #-0x8, r15
    .byte   0xDA, 0x0A    /* mov.l .L_pool_0600B50C, r10 */
    mov.l @r10, r10
    .byte   0xDE, 0x0A    /* mov.l .L_pool_0600B510, r14 */
    mov.l @r14, r14
    .byte   0xD3, 0x0A    /* mov.l .L_pool_0600B514, r3 */
    mov.l r14, @r3
    .byte   0xD0, 0x0A    /* mov.l .L_pool_0600B518, r0 */
    bra     .L_0600B534
    mov.l @r0, r0
.L_0600B4F4:
    .byte   0xDC, 0x09    /* mov.l .L_pool_0600B51C, r12 */
    .byte   0xDB, 0x0A    /* mov.l .L_pool_0600B520, r11 */
    bra     .L_0600B540
    nop
.L_0600B4FC:
    .byte   0xDC, 0x09    /* mov.l .L_pool_0600B524, r12 */
    .byte   0xDB, 0x0A    /* mov.l .L_pool_0600B528, r11 */
    bra     .L_0600B540
    nop
.L_0600B504:
    .byte   0xDC, 0x09    /* mov.l .L_pool_0600B52C, r12 */
    .byte   0xDB, 0x0A    /* mov.l .L_pool_0600B530, r11 */
    bra     .L_0600B540
    nop
.L_pool_0600B50C:
    .4byte  sym_0607EB8C
.L_pool_0600B510:
    .4byte  sym_0607E944
.L_pool_0600B514:
    .4byte  sym_0607E940
.L_pool_0600B518:
    .4byte  sym_0607EAD8
.L_pool_0600B51C:
    .4byte  sym_06063488
.L_pool_0600B520:
    .4byte  sym_06063434
.L_pool_0600B524:
    .4byte  sym_060634A4
.L_pool_0600B528:
    .4byte  sym_06063450
.L_pool_0600B52C:
    .4byte  sym_060634C0
.L_pool_0600B530:
    .4byte  sym_0606346C
.L_0600B534:
    cmp/eq #0x0, r0
    bt      .L_0600B4F4
    cmp/eq #0x1, r0
    bt      .L_0600B4FC
    cmp/eq #0x2, r0
    bt      .L_0600B504
.L_0600B540:
    .byte   0xD9, 0x3E    /* mov.l .L_pool_0600B63C, r9 */
    mov #0x0, r1
    .byte   0xDD, 0x3E    /* mov.l .L_pool_0600B640, r13 */
    mov.l @(16, r14), r2
    mov.l @r13, r3
    sub r3, r2
    add r9, r2
    cmp/gt r2, r1
    addc r1, r2
    shar r2
    add r2, r3
    mov.l r3, @r13
    mov.l @(20, r14), r2
    mov.l @(4, r13), r3
    sub r3, r2
    cmp/gt r2, r1
    addc r1, r2
    shar r2
    add r2, r3
    mov.l r3, @(4, r13)
    mov.l @(24, r14), r2
    mov.l @(8, r13), r3
    mov.w   DAT_0600b630, r1
    sub r3, r2
    add r1, r2
    mov #0x0, r3
    cmp/gt r2, r3
    addc r3, r2
    shar r2
    mov.l @(8, r13), r1
    add r2, r1
    .byte   0xD3, 0x31    /* mov.l .L_pool_0600B644, r3 */
    jsr @r3
    mov.l r1, @(8, r13)
    mov.l @(8, r13), r6
    mov.l @(4, r13), r5
    .byte   0xD3, 0x2F    /* mov.l .L_pool_0600B648, r3 */
    jsr @r3
    mov.l @r13, r4
    .byte   0xD3, 0x2F    /* mov.l .L_pool_0600B64C, r3 */
    jsr @r3
    mov.l @(32, r14), r4
    .byte   0xD3, 0x2E    /* mov.l .L_pool_0600B650, r3 */
    jsr @r3
    mov.l @(36, r14), r4
    .byte   0xD3, 0x2E    /* mov.l .L_pool_0600B654, r3 */
    jsr @r3
    mov.l @(28, r14), r4
    mov.w   DAT_0600b632, r0
    .byte   0xD3, 0x2A    /* mov.l .L_pool_0600B64C, r3 */
    mov.l @(r0, r14), r4
    add #-0xC, r0
    mov.l @(r0, r14), r2
    jsr @r3
    add r2, r4
    .byte   0xD0, 0x2A    /* mov.l .L_pool_0600B658, r0 */
    mov.l @r0, r0
    tst r0, r0
    bt      .L_0600B686
    mov r9, r6
    mov r9, r5
    .byte   0xD3, 0x28    /* mov.l .L_pool_0600B65C, r3 */
    jsr @r3
    mov r9, r4
    .byte   0xD5, 0x27    /* mov.l .L_pool_0600B660, r5 */
    .byte   0xD3, 0x28    /* mov.l .L_pool_0600B664, r3 */
    mov.l @r5, r5
    jsr @r3
    mov.l @(24, r12), r4
    .byte   0xD6, 0x27    /* mov.l .L_pool_0600B668, r6 */
    .byte   0xD2, 0x27    /* mov.l .L_pool_0600B66C, r2 */
    mov.l @r6, r6
    mov r2, r5
    mov.l r2, @(4, r15)
    mov.w @r5, r5
    .byte   0xD3, 0x26    /* mov.l .L_pool_0600B670, r3 */
    extu.w r5, r5
    jsr @r3
    mov.l @(24, r11), r4
    mov #0x0, r6
    mov.w   DAT_0600b634, r0
    .byte   0xD3, 0x19    /* mov.l .L_pool_0600B648, r3 */
    mov.l @(r0, r14), r5
    jsr @r3
    mov r6, r4
    mov.w   DAT_0600b636, r0
    .byte   0xD3, 0x18    /* mov.l .L_pool_0600B650, r3 */
    jsr @r3
    mov.l @(r0, r14), r4
    mov.w   .L_wpool_0600B638, r0
    .byte   0xD2, 0x1F    /* mov.l .L_pool_0600B674, r2 */
    .byte   0xD3, 0x17    /* mov.l .L_pool_0600B654, r3 */
    mov.l @(r0, r14), r4
    mov.l @r2, r2
    jsr @r3
    add r2, r4
    mov.l @(12, r10), r5
    shll2 r5
    mov.l r5, @r15
    .byte   0xD3, 0x1C    /* mov.l .L_pool_0600B678, r3 */
    mov.l @r15, r4
    .byte   0xD2, 0x16    /* mov.l .L_pool_0600B664, r2 */
    add r3, r5
    add r12, r4
    mov.l @r5, r5
    jsr @r2
    mov.l @r4, r4
    mov.l @(12, r10), r6
    shll2 r6
    mov.l r6, @r15
    .byte   0xD3, 0x17    /* mov.l .L_pool_0600B67C, r3 */
    add r3, r6
    mov.l @r6, r6
    mov.l @(4, r15), r5
    mov.w @r5, r5
    extu.w r5, r5
    mov.l @r15, r4
    add r11, r4
    bra     .L_0600B680
    mov.l @r4, r4

    .global DAT_0600b630
DAT_0600b630:
    .2byte  0x8000

    .global DAT_0600b632
DAT_0600b632:
    .2byte  0x01D8

    .global DAT_0600b634
DAT_0600b634:
    .2byte  0x01B4

    .global DAT_0600b636
DAT_0600b636:
    .2byte  0x01D0
.L_wpool_0600B638:
    .2byte  0x01C8
    .2byte  0xFFFF
.L_pool_0600B63C:
    .4byte  0x00008000
.L_pool_0600B640:
    .4byte  sym_06078670
.L_pool_0600B644:
    .4byte  sym_06027080
.L_pool_0600B648:
    .4byte  sym_060270F2
.L_pool_0600B64C:
    .4byte  mat_rot_xy_b
.L_pool_0600B650:
    .4byte  mat_rot_yz_b
.L_pool_0600B654:
    .4byte  mat_rot_xz_b
.L_pool_0600B658:
    .4byte  sym_06059F30
.L_pool_0600B65C:
    .4byte  mat_scale_b
.L_pool_0600B660:
    .4byte  sym_06063510
.L_pool_0600B664:
    .4byte  sym_06032158
.L_pool_0600B668:
    .4byte  sym_060634F4
.L_pool_0600B66C:
    .4byte  sym_06089E98
.L_pool_0600B670:
    .4byte  sym_06031DF4
.L_pool_0600B674:
    .4byte  sym_06083258
.L_pool_0600B678:
    .4byte  sym_060634F8
.L_pool_0600B67C:
    .4byte  sym_060634DC
.L_0600B680:
    .byte   0xD2, 0x11    /* mov.l .L_pool_0600B6C8, r2 */
    jsr @r2
    nop
.L_0600B686:
    .byte   0xD4, 0x11    /* mov.l .L_pool_0600B6CC, r4 */
    mov.l @r4, r3
    add #-0x30, r3
    mov.l r3, @r4
    add #0x8, r15
    lds.l @r15+, pr
    mov.l @r15+, r9
    mov.l @r15+, r10
    mov.l @r15+, r11
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14
