/* cmd_validate_chain -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0603B1B6 - 0x0603B31C
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0603B1B6
    .space 2    /* align to match original address 0x0603B1B6 (mod 4 = 2) */


    .global cmd_validate_chain
    .type cmd_validate_chain, @function
cmd_validate_chain:
    mov.l r14, @-r15
    mov.l r13, @-r15
    sts.l pr, @-r15
    sts.l macl, @-r15
    add #-0x8, r15
    mov.l r5, @r15
    mov.l r6, @(4, r15)
    .byte   0xBE, 0x90    /* bsr 0x0603AEE8 (external) */
    mov r7, r13
    mov r0, r14
    tst r14, r14
    bf      .L_0603B1DC
    mov #-0x9, r4
    add #0x8, r15
    lds.l @r15+, macl
    lds.l @r15+, pr
    mov.l @r15+, r13
    .byte   0xA3, 0xB0    /* bra 0x0603B93C (external) */
    mov.l @r15+, r14
.L_0603B1DC:
    mov #0x0, r6
    mov.l @r15, r5
    .byte   0xBE, 0xF6    /* bsr 0x0603AFD0 (external) */
    mov r14, r4
    mov.l @r14, r5
    mov r13, r0
    mov.l @r15, r3
    mov.l @(16, r5), r5
    cmp/eq #-0x1, r0
    bf/s    .L_0603B1F8
    sub r3, r5
    mov.w   DAT_0603b270, r13
    mul.l r13, r5
    sts macl, r13
.L_0603B1F8:
    mov r13, r7
    mov.l @(4, r15), r6
    bsr     cmd_multi_validate
    mov r14, r4
    mov r0, r13
    .byte   0xBE, 0xC7    /* bsr 0x0603AF94 (external) */
    mov r14, r4
    cmp/pz r13
    bf      .L_0603B20E
    .byte   0xB3, 0x97    /* bsr 0x0603B93C (external) */
    mov #0x0, r4
.L_0603B20E:
    mov r13, r0
    add #0x8, r15
    lds.l @r15+, macl
    lds.l @r15+, pr
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14

    .global cmd_multi_validate
    .type cmd_multi_validate, @function
cmd_multi_validate:
    mov.l r14, @-r15
    mov r4, r14
    mov.l r13, @-r15
    sts.l pr, @-r15
    add #-0xC, r15
    mov.l   .L_pool_0603B274, r3
    mov.l r3, @(8, r15)
    mov.l @r14, r4
    mov.l @(40, r4), r13
    mov.l r3, @(40, r4)
    bsr     .L_0603B28E
    mov r14, r4
    mov r0, r4
    tst r4, r4
    bt      .L_0603B244
    mov.l @r14, r5
    .byte   0xB3, 0x7E    /* bsr 0x0603B93C (external) */
    mov.l r13, @(40, r5)
    bra     .L_0603B284
    nop
.L_0603B244:
    .byte   0xB0, 0xEE    /* bsr 0x0603B424 (external) */
    mov r14, r4
    mov r0, r4
    cmp/pz r4
    bt      .L_0603B258
    mov.l @r14, r5
    .byte   0xB3, 0x74    /* bsr 0x0603B93C (external) */
    mov.l r13, @(40, r5)
    bra     .L_0603B284
    nop
.L_0603B258:
    tst r4, r4
    bf      .L_0603B278
    mov r15, r6
    mov r15, r5
    add #0x4, r5
    .byte   0xB0, 0xCA    /* bsr 0x0603B3FA (external) */
    mov r14, r4
    .byte   0xB3, 0x69    /* bsr 0x0603B93C (external) */
    mov #0x0, r4
    mov.l @r14, r4
    bra     .L_0603B282
    mov.l r13, @(40, r4)

    .global DAT_0603b270
DAT_0603b270:
    .2byte  0x0914
    .2byte  0xFFFF
.L_pool_0603B274:
    .4byte  0x7FFFFFFF
.L_0603B278:
    mov.l   .L_pool_0603B30C, r3
    jsr @r3
    nop
    bra     .L_0603B244
    nop
.L_0603B282:
    mov.l @r15, r0
.L_0603B284:
    add #0xC, r15
    lds.l @r15+, pr
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14
.L_0603B28E:
    mov #0x12, r0

    .global menu_list_scroll
    .type menu_list_scroll, @function
menu_list_scroll:
    mov.l r14, @-r15
    mov r4, r14
    mov.l r13, @-r15
    mov.l r8, @-r15
    sts.l pr, @-r15
    add #-0xC, r15
    mov.l r5, @r15
    mov.l r6, @(4, r15)
    mov.l r7, @(8, r15)
    mov.b @(r0, r14), r3
    extu.b r3, r3
    tst r3, r3
    bt      .L_0603B2B8
    mov #-0x10, r4
    add #0xC, r15
    lds.l @r15+, pr
    mov.l @r15+, r8
    mov.l @r15+, r13
    .byte   0xA3, 0x42    /* bra 0x0603B93C (external) */
    mov.l @r15+, r14
.L_0603B2B8:
    .byte   0xB3, 0x74    /* bsr 0x0603B9A4 (external) */
    mov r14, r4
    mov #0x1, r4
    mov #0x11, r0
    mov.b r4, @(r0, r14)
    mov #0x12, r0
    mov.b r4, @(r0, r14)
    mov.l @r14, r3
    mov.l @(16, r3), r8
    .byte   0xBE, 0xC5    /* bsr 0x0603B058 (external) */
    mov r14, r4
    mov r8, r4
    mov.l @r15, r3
    sub r0, r4
    cmp/ge r4, r3
    bt      .L_0603B2DC
    bra     .L_0603B2DE
    mov.l @r15, r13
.L_0603B2DC:
    mov r4, r13
.L_0603B2DE:
    mov r13, r5
    .byte   0xB5, 0xCC    /* bsr 0x0603BE7C (external) */
    mov.l @r14, r4
    mov r13, r5
    mov.l   .L_pool_0603B310, r3
    jsr @r3
    mov.l @(8, r14), r4
    mov #0x1, r7
    mov.l @(8, r15), r6
    mov.l @(4, r15), r5
    mov.l   .L_pool_0603B314, r3
    jsr @r3
    mov.l @(4, r14), r4
    mov.l   .L_pool_0603B318, r3
    jsr @r3
    mov.l @(8, r14), r4
    mov #0x0, r4
    add #0xC, r15
    lds.l @r15+, pr
    mov.l @r15+, r8
    mov.l @r15+, r13
    .byte   0xA3, 0x18    /* bra 0x0603B93C (external) */
    mov.l @r15+, r14
.L_pool_0603B30C:
    .4byte  cdb_wait_scdq
.L_pool_0603B310:
    .4byte  sym_0603F9DA
.L_pool_0603B314:
    .4byte  sym_0603EF54
.L_pool_0603B318:
    .4byte  sym_0603FA00
