/* controller_config -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0603DB28 - 0x0603DDFC
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0603DB28


    .global controller_config
    .type controller_config, @function
controller_config:
    mov.l r14, @-r15
    mov r5, r0
    mov.l r13, @-r15
    mov.l r12, @-r15
    mov.l r11, @-r15
    mov.l r10, @-r15
    mov.l r9, @-r15
    mov.l r8, @-r15
    sts.l pr, @-r15
    add #-0xC, r15
    mov.l   .L_sym_060A4C80, r10
    mov.l r4, @r15
    mov.w r0, @(4, r15)
    mov r6, r0
    cmp/eq #0x1, r0
    bt/s    .L_0603DB5E
    mov #0x0, r13
    tst r6, r6
    bt      .L_0603DB5E
    mov.w   .L_wpool_0603DB9E, r3
    cmp/eq r3, r6
    bf      .L_0603DB5A
    mov r7, r0
    cmp/eq #0x1, r0
    bt      .L_0603DB5E
.L_0603DB5A:
    bra     .L_0603DDD6
    mov #0x2, r0
.L_0603DB5E:
    mov r7, r0
    cmp/eq #0x1, r0
    bt      .L_0603DB72
    mov r7, r0
    cmp/eq #0x2, r0
    bt      .L_0603DB72
    tst r7, r7
    bt      .L_0603DB72
    bra     .L_0603DDD6
    mov #0x2, r0
.L_0603DB72:
    extu.b r6, r3
    mov.l   .L_sym_060A4C58, r2
    extu.b r7, r1
    mov r6, r0
    mov.b r3, @r2
    mov.l   .L_sym_060A4C59, r2
    cmp/eq #0x1, r0
    bf/s    .L_0603DB90
    mov.b r1, @r2
    mov r7, r0
    cmp/eq #0x1, r0
    bf      .L_0603DB90
    mov #0x2, r2
    bra     .L_0603DBB0
    mov.w r2, @r10
.L_0603DB90:
    tst r6, r6
    bf      .L_0603DBAC
    mov r7, r0
    cmp/eq #0x1, r0
    bf      .L_0603DBAC
    bra     .L_0603DBAE
    mov #0x1, r2
.L_wpool_0603DB9E:
    .2byte  0x0100
.L_sym_060A4C80:
    .4byte  sym_060A4C80
.L_sym_060A4C58:
    .4byte  sym_060A4C58
.L_sym_060A4C59:
    .4byte  sym_060A4C59
.L_0603DBAC:
    extu.w r13, r2
.L_0603DBAE:
    mov.w r2, @r10
.L_0603DBB0:
    mov.w @r10, r3
    mov.l   .L_sym_060A3E38, r2
    mov.w r3, @r2
    mov.l   .L_sym_060A4C70, r4
    mov.l r13, @r4
    mov.l r13, @(4, r4)
    mov.l   .L_sym_060A4C60, r5
    mov.l r13, @r5
    mov.l   .L_sym_060A4C68, r4
    mov.l r13, @r4
    mov.l r13, @(4, r5)
    mov.l r13, @(4, r4)
    mov.l   .L_sym_060A53A8, r4
    mov.l   .L_sym_060635AE, r0
    mov r4, r11
    mov.w @r0, r0
    add #-0x10, r15
    extu.w r0, r0
    mov.l   .L_sym_060358EC, r3
    shlr r0
    jsr @r3
    mov.l r15, @-r15
    mov #0x0, r2
    mov.l r2, @-r15
    mov.l   .L_pool_0603DCD8, r2
    mov.l r2, @-r15
    mov r15, r3
    mov.l   .L_sym_060359E4, r2
    add #0x10, r3
    jsr @r2
    mov.l r3, @-r15
    mov.l   .L_sym_060357B8, r3
    jsr @r3
    nop
    mov.l r0, @r11
    mov.l   .L_sym_060A53B0, r5
    mov.l   .L_sym_060635B0, r9
    mov r5, r12
    mov.w @r9, r0
    extu.w r0, r0
    add #-0x10, r15
    shlr r0
    mov.l   .L_sym_060358EC, r3
    jsr @r3
    mov.l r15, @-r15
    mov #0x0, r2
    mov.l r2, @-r15
    mov.l   .L_pool_0603DCD8, r2
    mov.l r2, @-r15
    mov r15, r3
    mov.l   .L_sym_060359E4, r2
    add #0x10, r3
    jsr @r2
    mov.l r3, @-r15
    mov.l   .L_sym_060357B8, r3
    jsr @r3
    nop
    mov.l r0, @r12
    mov.l @r11, r2
    mov.l r2, @(4, r4)
    mov.l @r12, r3
    mov.l r3, @(4, r5)
    mov.l @r15, r2
    mov.l   .L_sym_060A4C5C, r3
    mov.l r2, @r3
    mov.w @(4, r15), r0
    mov.l   .L_sym_060635B2, r3
    mov r0, r2
    mov.w r2, @r3
    mov.l   .L_display_scene_update, r8
    mov.l   .L_sym_060A3E68, r14
    mov.l @r11, r2
    mov.l r2, @(8, r15)
    .byte   0xBF, 0x21    /* bsr 0x0603DA88 (external) */
    mov r13, r4
    mov r0, r4
    jsr @r8
    mov.l @(8, r15), r5
    mov.l @(8, r15), r3
    sub r0, r3
    mov.l r3, @-r15
    .byte   0xBE, 0xCB    /* bsr 0x0603D9EC (external) */
    mov r13, r4
    neg r0, r4
    jsr @r8
    mov.l @r12, r5
    mov.l @r15+, r2
    sub r0, r2
    mov.l r2, @r14
    .byte   0xBE, 0xC3    /* bsr 0x0603D9EC (external) */
    mov r13, r4
    mov r0, r4
    jsr @r8
    mov.l @r11, r5
    mov.l @r12, r2
    sub r0, r2
    mov.l r2, @-r15
    .byte   0xBF, 0x09    /* bsr 0x0603DA88 (external) */
    mov r13, r4
    mov r0, r4
    jsr @r8
    mov.l @r12, r5
    mov.l @r15+, r2
    sub r0, r2
    mov.l r2, @(4, r14)
    mov.l r13, @(8, r14)
    .byte   0xBE, 0xB2    /* bsr 0x0603D9EC (external) */
    mov r13, r4
    neg r0, r0
    mov.l r0, @(12, r14)
    .byte   0xBE, 0xFC    /* bsr 0x0603DA88 (external) */
    mov r13, r4
    mov.l r0, @(16, r14)
    .byte   0xBE, 0xF9    /* bsr 0x0603DA88 (external) */
    mov r13, r4
    mov.l r0, @(20, r14)
    .byte   0xBE, 0xA8    /* bsr 0x0603D9EC (external) */
    mov r13, r4
    mov.l r0, @(24, r14)
    mov.l   .L_pool_0603DCFC, r4
    mov.l r4, @(28, r14)
    mov.l r13, @(32, r14)
    mov.l r13, @(36, r14)
    mov.l r13, @(40, r14)
    mov.l r4, @(44, r14)
    mov.l r13, @(48, r14)
    mov.l   .L_sym_060635AE, r2
    mov.w @r2, r2
    extu.w r2, r2
    shlr r2
    exts.w r2, r2
    bra     .L_0603DD00
    nop
    .2byte  0xFFFF
.L_sym_060A3E38:
    .4byte  sym_060A3E38
.L_sym_060A4C70:
    .4byte  sym_060A4C70
.L_sym_060A4C60:
    .4byte  sym_060A4C60
.L_sym_060A4C68:
    .4byte  sym_060A4C68
.L_sym_060A53A8:
    .4byte  sym_060A53A8
.L_sym_060635AE:
    .4byte  sym_060635AE
.L_sym_060358EC:
    .4byte  sym_060358EC
.L_pool_0603DCD8:
    .4byte  0x40F00000
.L_sym_060359E4:
    .4byte  sym_060359E4
.L_sym_060357B8:
    .4byte  sym_060357B8
.L_sym_060A53B0:
    .4byte  sym_060A53B0
.L_sym_060635B0:
    .4byte  sym_060635B0
.L_sym_060A4C5C:
    .4byte  sym_060A4C5C
.L_sym_060635B2:
    .4byte  sym_060635B2
.L_display_scene_update:
    .4byte  display_scene_update
.L_sym_060A3E68:
    .4byte  sym_060A3E68
.L_pool_0603DCFC:
    .4byte  0x00010000
.L_0603DD00:
    mov #0x34, r0
    mov.w r2, @(r0, r14)
    mov.w @r9, r3
    mov #0x36, r0
    extu.w r3, r3
    shlr r3
    exts.w r3, r3
    mov.w r3, @(r0, r14)
    mov.w   .L_wpool_0603DDEA, r3
    mov #0x38, r0
    mov.w r3, @(r0, r14)
    mov #0x3C, r0
    mov.l   .L_sym_060635AE_2, r3
    mov.w @r3, r3
    extu.w r3, r3
    shlr r3
    mov.w r3, @(r0, r14)
    mov.w @r9, r3
    extu.w r3, r3
    shlr r3
    mov #0x3E, r0
    mov.w r3, @(r0, r14)
    exts.w r13, r3
    mov #0x40, r0
    mov.w r3, @(r0, r14)
    mov #0x44, r0
    mov.l r13, @(r0, r14)
    mov #0x48, r0
    mov.l r13, @(r0, r14)
    mov #0x4C, r0
    mov.l r4, @(r0, r14)
    mov #0x50, r0
    mov.l r4, @(r0, r14)
    mov.w @(4, r15), r0
    extu.w r0, r0
    cmp/eq #0x2, r0
    bf      .L_0603DDC0
    mov.l   .L_sym_060A3EE8, r4
    mov r4, r5
    add #-0x80, r5
    mov.l @r5, r2
    mov.l r2, @r4
    mov.l @(4, r5), r3
    mov.l r3, @(4, r4)
    mov.l @(8, r5), r2
    mov.l r2, @(8, r4)
    mov.l @(12, r5), r3
    mov.l r3, @(12, r4)
    mov.l @(16, r5), r2
    mov.l r2, @(16, r4)
    mov.l @(20, r5), r3
    mov.l r3, @(20, r4)
    mov.l @(24, r5), r2
    mov.l r2, @(24, r4)
    mov.l @(28, r5), r3
    mov.l r3, @(28, r4)
    mov.l @(32, r5), r2
    mov.l r2, @(32, r4)
    mov.l @(36, r5), r3
    mov.l r3, @(36, r4)
    mov.l @(40, r5), r2
    mov.l r2, @(40, r4)
    mov.l @(44, r5), r3
    mov.l r3, @(44, r4)
    mov.l @(48, r5), r2
    mov.l r2, @(48, r4)
    mov #0x34, r0
    mov.w @(r0, r5), r3
    mov.w r3, @(r0, r4)
    mov #0x36, r0
    mov.w @(r0, r5), r3
    mov.w r3, @(r0, r4)
    mov #0x38, r0
    mov.w @(r0, r5), r3
    mov.w r3, @(r0, r4)
    mov #0x3C, r0
    mov.w @(r0, r5), r3
    mov.w r3, @(r0, r4)
    mov #0x3E, r0
    mov.w @(r0, r5), r3
    mov.w r3, @(r0, r4)
    mov #0x40, r0
    mov.w @(r0, r5), r3
    mov.w r3, @(r0, r4)
    mov #0x44, r0
    mov.l @(r0, r5), r3
    mov.l r3, @(r0, r4)
    mov #0x48, r0
    mov.l @(r0, r5), r3
    mov.l r3, @(r0, r4)
    mov #0x4C, r0
    mov.l @(r0, r5), r3
    mov.l r3, @(r0, r4)
    mov #0x50, r0
    mov.l @(r0, r5), r3
    mov.l r3, @(r0, r4)
.L_0603DDC0:
    mov.l @r15, r4
    mov.l   .L_pool_0603DDF4, r3
    and r3, r4
    shlr r4
    mov.l @r15, r0
    and #0x3E, r0
    shlr2 r0
    add r0, r4
    mov.l   .L_sym_060A3E44, r3
    mov.l r4, @r3
    mov #0x0, r0
.L_0603DDD6:
    add #0xC, r15
    lds.l @r15+, pr
    mov.l @r15+, r8
    mov.l @r15+, r9
    mov.l @r15+, r10
    mov.l @r15+, r11
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14
.L_wpool_0603DDEA:
    .2byte  0x0190
.L_sym_060635AE_2:
    .4byte  sym_060635AE
.L_sym_060A3EE8:
    .4byte  sym_060A3EE8
.L_pool_0603DDF4:
    .4byte  0x0007FF80
.L_sym_060A3E44:
    .4byte  sym_060A3E44
