/* course_data_loader -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0601B584 - 0x0601B644
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0601B584


    .global course_data_loader
    .type course_data_loader, @function
course_data_loader:
    mov.l r14, @-r15
    sts.l pr, @-r15
    add #-0x4, r15
    mov.l   .L_pool_0601B5F8, r14
    mov.l   .L_pool_0601B5FC, r5
    mov.l   .L_vdp2_cram_0x6C0, r4
    jsr @r14
    mov #0x60, r6
    mov.l   .L_pool_0601B604, r5
    mov.l   .L_vdp2_cram_0x720, r4
    jsr @r14
    mov #0x20, r6
    mov.l   .L_pool_0601B60C, r5
    mov.l   .L_vdp2_cram_0x740, r4
    jsr @r14
    mov #0x20, r6
    mov.w   .L_wpool_0601B5F4, r6
    mov.l   .L_pool_0601B614, r5
    mov.l   .L_vdp2_cram_0x000, r4
    mov.l   .L_pool_0601B61C, r3
    jsr @r3
    nop
    mov.l   .L_pool_0601B620, r3
    jsr @r3
    mov #0xC, r4
    mov.l   .L_pool_0601B624, r3
    jsr @r3
    nop
    mov.l   .L_pool_0601B628, r2
    mov #0x16, r6
    mov.l r2, @r15
    mov r2, r7
    mov r2, r5
    mov.l   .L_mask_0xC000, r3
    mov.l @(4, r7), r7
    mov.l @r5, r5
    add r3, r7
    mov.l   .L_pool_0601B630, r3
    jsr @r3
    mov #0x8, r4
    mov #0x0, r6
    mov.l   .L_pool_0601B634, r5
    mov.l   .L_pool_0601B638, r4
    mov.b @r5, r5
    .byte   0xB2, 0x38    /* bsr 0x0601BA50 (external) */
    mov.b @r4, r4
    mov #0x0, r2
    mov.l   .L_pool_0601B63C, r3
    mov.b r2, @r3
    mov #0x4, r2
    mov.l   .L_pool_0601B640, r3
    mov.b r2, @r3
    add #0x4, r15
    lds.l @r15+, pr
    rts
    mov.l @r15+, r14
.L_wpool_0601B5F4:
    .2byte  0x0180
    .2byte  0xFFFF
.L_pool_0601B5F8:
    .4byte  memcpy_word_idx
.L_pool_0601B5FC:
    .4byte  sym_0604866C
.L_vdp2_cram_0x6C0:
    .4byte  0x25F006C0                  /* VDP2 color RAM +0x6C0 */
.L_pool_0601B604:
    .4byte  sym_0604862C
.L_vdp2_cram_0x720:
    .4byte  0x25F00720                  /* VDP2 color RAM +0x720 */
.L_pool_0601B60C:
    .4byte  sym_060485EC
.L_vdp2_cram_0x740:
    .4byte  0x25F00740                  /* VDP2 color RAM +0x740 */
.L_pool_0601B614:
    .4byte  sym_0604996C
.L_vdp2_cram_0x000:
    .4byte  0x25F00000                  /* VDP2 color RAM +0x000 */
.L_pool_0601B61C:
    .4byte  dma_transfer
.L_pool_0601B620:
    .4byte  sym_0602853E
.L_pool_0601B624:
    .4byte  sym_06028560
.L_pool_0601B628:
    .4byte  sym_060638C8
.L_mask_0xC000:
    .4byte  0x0000C000                  /* bits 15:14 mask */
.L_pool_0601B630:
    .4byte  sym_06028400
.L_pool_0601B634:
    .4byte  sym_0605D4F5
.L_pool_0601B638:
    .4byte  sym_0605D4F4
.L_pool_0601B63C:
    .4byte  sym_0605D4FA
.L_pool_0601B640:
    .4byte  sym_0608600D
