/* course_state_setup -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0601B0D8 - 0x0601B160
 * Auto-generated by tools/generate_l3_tu.py
 *
 * Initializes 5 course display slots by uploading VDP pattern data.
 * Each slot gets three geom_dispatch_final calls:
 *   1. Pattern fill A (mode 0x8, 0x60 bytes from course_pattern_fill_a)
 *   2. Pattern fill B (mode 0x8, 0x60 bytes from course_pattern_fill_b)
 *   3. Color fill    (mode 0xC, 0x60 bytes from course_pattern_fill_b)
 * VRAM offsets are computed from slot index with stride 3.
 */

    .section .text.FUN_0601B0D8


    .global course_state_setup
    .type course_state_setup, @function
course_state_setup:
    mov.l r14, @-r15         ! save r14
    mov.l r13, @-r15         ! save r13
    mov.l r12, @-r15         ! save r12
    mov.l r11, @-r15         ! save r11
    mov.l r10, @-r15         ! save r10
    mov.l r9, @-r15          ! save r9
    mov.l r8, @-r15          ! save r8
    sts.l pr, @-r15          ! save return address
    add #-0x4, r15           ! allocate 4 bytes stack local
    mov.l   .L_pool_pattern_fill_a, r8  ! r8 = &course_pattern_fill_a
    mov #0x5, r10            ! r10 = 5 (slot count)
    mov.l   .L_pool_pattern_fill_b, r13 ! r13 = &course_pattern_fill_b
    mov.l   .L_pool_geom_dispatch, r14  ! r14 = &geom_dispatch_final
    mov #0x0, r4             ! r4 = 0
    extu.w r4, r11           ! r11 = 0 (loop counter)
    extu.w r4, r12           ! r12 = 0 (slot base index, stride 3)
.L_slot_loop:
    mov r8, r7               ! r7 = course_pattern_fill_a (source data)
    mov #0x60, r6            ! r6 = 0x60 (96 bytes to copy)
    extu.w r12, r9           ! r9 = slot_base (zero-extended)
    mov.l r9, @r15           ! save slot_base to stack local
    add #0x6, r9             ! r9 = slot_base + 6
    shll2 r9                 ! r9 <<= 2
    shll2 r9                 ! r9 <<= 2
    shll2 r9                 ! r9 <<= 2 (total: r9 = (slot_base+6) * 64)
    mov r9, r5               ! r5 = (slot_base+6) * 64
    add #0x2, r5             ! r5 += 2
    shll r5                  ! r5 *= 2 → VRAM word offset for pattern A
    jsr @r14                 ! call geom_dispatch_final(0x8, vram_ofs, 0x60, fill_a)
    mov #0x8, r4             ! r4 = 0x8 (VDP pattern write mode) [delay slot]
    mov r13, r7              ! r7 = course_pattern_fill_b (source data)
    mov #0x60, r6            ! r6 = 0x60 (96 bytes to copy)
    mov.l @r15, r5           ! r5 = slot_base (reload from stack)
    add #0x7, r5             ! r5 = slot_base + 7
    shll2 r5                 ! r5 <<= 2
    shll2 r5                 ! r5 <<= 2
    shll2 r5                 ! r5 <<= 2 (total: r5 = (slot_base+7) * 64)
    add #0x21, r5            ! r5 += 33
    shll r5                  ! r5 *= 2 → VRAM word offset for pattern B
    jsr @r14                 ! call geom_dispatch_final(0x8, vram_ofs, 0x60, fill_b)
    mov #0x8, r4             ! r4 = 0x8 (VDP pattern write mode) [delay slot]
    mov r13, r7              ! r7 = course_pattern_fill_b (source data)
    mov #0x60, r6            ! r6 = 0x60 (96 bytes to copy)
    mov r9, r5               ! r5 = (slot_base+6) * 64
    add #0x25, r5            ! r5 += 37
    shll r5                  ! r5 *= 2 → VRAM word offset for color fill
    jsr @r14                 ! call geom_dispatch_final(0xC, vram_ofs, 0x60, fill_b)
    mov #0xC, r4             ! r4 = 0xC (VDP color write mode) [delay slot]
    add #0x1, r11            ! r11++ (increment loop counter)
    extu.w r11, r3           ! r3 = counter (zero-extended)
    cmp/ge r10, r3           ! T = (counter >= 5)?
    bf/s    .L_slot_loop     ! loop if counter < 5
    add #0x3, r12            ! r12 += 3 (advance slot base) [delay slot]
    add #0x4, r15            ! deallocate stack local
    lds.l @r15+, pr          ! restore return address
    mov.l @r15+, r8          ! restore r8
    mov.l @r15+, r9          ! restore r9
    mov.l @r15+, r10         ! restore r10
    mov.l @r15+, r11         ! restore r11
    mov.l @r15+, r12         ! restore r12
    mov.l @r15+, r13         ! restore r13
    rts                      ! return
    mov.l @r15+, r14         ! restore r14 [delay slot]
.L_pool_pattern_fill_a:
    .4byte  sym_0604A490
.L_pool_pattern_fill_b:
    .4byte  sym_0604A4B8
.L_pool_geom_dispatch:
    .4byte  sym_060284AE
