/* disp_split_stub -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x060334D2 - 0x060334DA
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_060334D2


    .global disp_split_stub
    .type disp_split_stub, @function
disp_split_stub:
    sts.l pr, @-r15
    jsr @r0
    nop
    lds.l @r15+, pr
