/* effect_cleanup_stub -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x06028580 - 0x06028654
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_06028580


    .global effect_cleanup_stub
    .type effect_cleanup_stub, @function
effect_cleanup_stub:
    mov.l r14, @-r15
    shll8 r5
    shlr2 r5
    add r4, r5
    mov.l r13, @-r15
    shll r5
    mov.w   .L_wpool_060285DA, r4
    cmp/pz r6
    mov.l r12, @-r15
    bt/s    particle_sys_mgr
    movt r12
    neg r6, r6

    .global particle_sys_mgr
    .type particle_sys_mgr, @function
particle_sys_mgr:
    sts.l pr, @-r15
    mov r6, r14
    mulu.w r6, r4
    mov r5, r13
    mov.w   .L_wpool_06028610, r6
    add #0xA, r5
    sts macl, r7
    shlr16 r7
    add r4, r7
    .byte   0xBE, 0xDD    /* bsr 0x06028368 (external) */
    mov #0x8, r4
    shlr16 r14
    exts.w r14, r7
    mov r13, r5
    .byte   0xBE, 0xD8    /* bsr 0x06028368 (external) */
    mov #0x8, r4
    mov.l   .L_sym_06028614, r5
    mov #0x2E, r0
    mov.l @(8, r5), r2
    or r6, r0
    mov.l @r2, r2
    tst r12, r12
    lds.l @r15+, pr
    add r13, r2
    mov.w r0, @(14, r2)
    bf/s    .L_060285D4
    mov.l @r15+, r12
    mov #0x2D, r1
    or r6, r1
    mov.w r1, @r2
.L_060285D4:
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14
.L_wpool_060285DA:
    .2byte  0x2710
.L_sym_06028614:
    .4byte  sym_06028614
    .4byte  0x45186763
    .4byte  0x96144509
    .4byte  0x354C4500
    .4byte  0xAEE4E408
    .4byte  0x45186763
    .4byte  0x960C4509
    .4byte  0x354C4500
    .4byte  0xAEC2E408
    .4byte  0x45186763
    .4byte  0x96044509
    .4byte  0x354C4500
    .4byte  0xAEE8E408
.L_wpool_06028610:
    .2byte  0xF000
    .2byte  0x0009

    .global sym_06028614
sym_06028614:
    .4byte  sym_06061294
    .4byte  sym_06061298
    .4byte  sym_0606129C
    .4byte  sym_060612A0
    .4byte  loc_060612A4
    .4byte  loc_060612A8

    .global sym_0602862C
sym_0602862C:
    .4byte  sym_060612AC
    .4byte  sym_060612B0
    .4byte  sym_060612B4
    .4byte  sym_060612B8
    .4byte  loc_060612BC
    .4byte  loc_060612C0

    .global sym_06028644
sym_06028644:
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0020 /* UNKNOWN */
    .word 0x0020 /* UNKNOWN */
    .word 0x0020 /* UNKNOWN */
    .word 0x0020 /* UNKNOWN */
