/* fixpt_div_full -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x06042458 - 0x06042ACA
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_06042458


    .global fixpt_div_full
    .type fixpt_div_full, @function
fixpt_div_full:
    mov.l r14, @-r15
    sts.l pr, @-r15
    cmp/pz r4
    bt      .L_06042462
    neg r4, r4
.L_06042462:
    mov.l   .L_fp_180, r2
    cmp/ge r2, r4
    bf/s    .L_0604246E
    mov #0x1, r14
    bra     .L_0604247E
    mov #0x0, r4
.L_0604246E:
    mov.l   .L_fp_90, r2
    cmp/gt r2, r4
    bf      .L_0604247C
    mov.l   .L_fp_180, r2
    sub r4, r2
    bra     .L_0604247E
    mov r2, r4
.L_0604247C:
    mov #0x0, r14
.L_0604247E:
    mov.l   .L_sym_0604249C, r3
    jsr @r3
    nop
    tst r14, r14
    bt      .L_0604248A
    neg r0, r0
.L_0604248A:
    lds.l @r15+, pr
    rts
    mov.l @r15+, r14
.L_fp_180:
    .4byte  0x00B40000
.L_fp_90:
    .4byte  0x005A0000
.L_sym_0604249C:
    .4byte  sym_0604249C

    .global sym_0604249C
sym_0604249C:
    mov.l   .L_fp_90_2, r2
    neg r4, r4
    add r2, r4

    .global sym_060424A2
sym_060424A2:
    mova    DAT_060424c8, r0
    sts macl, r3
    swap.w r4, r1
    extu.w r1, r1
    shll2 r1
    mov.w @(r0, r1), r2
    add #0x2, r0
    mulu.w r4, r2
    mov.w @(r0, r1), r0
    sts macl, r2
    extu.w r0, r0
    lds r3, macl
    swap.w r2, r2
    extu.w r2, r2
    rts
    add r2, r0
    .2byte  0x0009
.L_fp_90_2:
    .4byte  0x005A0000

    .global DAT_060424c8
DAT_060424c8:
    mul.l r7, r4

    .global DAT_060424ca
DAT_060424ca:
    .word 0x0000 /* UNKNOWN */
    .word 0x0478 /* UNKNOWN */
    mul.l r7, r4
    mov.l r7, @(r0, r4)
    mac.l @r14+, @r8+
    mov.l r7, @(r0, r4)
    mov.w r6, @(r0, r13)
    mov.b r7, @(r0, r4)
    mov.l r13, @(44, r1)
    .word 0x0473 /* UNKNOWN */
    mov.l r4, @(60, r6)
    .word 0x0470 /* UNKNOWN */
    mov.l r12, @(8, r10)
    mov.l @(r0, r6), r4
    mov.l r3, @(8, r15)
    mov.b @(r0, r6), r4
    mov.b r10, @r3
    .word 0x0468 /* UNKNOWN */
    cmp/str r0, r8
    mov.b r6, @(r0, r4)
    mov.b r7, @-r12
    .word 0x0461 /* UNKNOWN */
    sub r13, r0
    mov.w @(r0, r5), r4
    .word 0x3539 /* UNKNOWN */
    .word 0x0458 /* UNKNOWN */
    cmp/hi r9, r9
    .word 0x0453 /* UNKNOWN */
    addc r14, r13
    mac.l @r4+, @r4+
    .word 0x4241 /* UNKNOWN */
    .word 0x0448 /* UNKNOWN */
    .word 0x4690 /* UNKNOWN */
    .word 0x0443 /* UNKNOWN */
    .word 0x4AD8 /* UNKNOWN */
    mov.w @(r0, r3), r4
    tas.b @r15
    mov.l r3, @(r0, r4)
    mov.l @(32, r5), r3
    .word 0x0430 /* UNKNOWN */
    mov.l @(56, r8), r7
    .word 0x0428 /* UNKNOWN */
    mov.l @(56, r11), r11
    .word 0x0420 /* UNKNOWN */
    mov.l @(24, r14), r15
    .word 0x0419 /* UNKNOWN */
    mov.l @r0+, r4
    .word 0x0411 /* UNKNOWN */
    exts.w r1, r8
    .word 0x0409 /* UNKNOWN */
    mov.b @r3, r12
    mac.l @r15+, @r3+
    add #0x39, r0
    mul.l r15, r3
    add #0x38, r4
    mov.w @(r0, r14), r3
    add #0x2F, r8
    .word 0x03E3 /* UNKNOWN */
    add #0x1C, r12
    .word 0x03DA /* UNKNOWN */
    add #-0x1, r15
    mac.l @r12+, @r3+
    .word 0x83D9 /* UNKNOWN */
    mov.w r12, @(r0, r3)
    .word 0x87A8 /* UNKNOWN */
    .word 0x03BA /* UNKNOWN */
    bf      .L_0604262C
    mov.l @(r0, r10), r3
    bf/s    .L_060425A4
    mov.b r10, @(r0, r3)
    mov.w   .L_const_0x7fff_w, r2
    mul.l r9, r3
    mov.w   .L_const_0x65ab_w, r6
    .word 0x038B /* UNKNOWN */
    mov.w   .L_const_0xb826_w, r10
    .word 0x0380 /* UNKNOWN */
    mov.w   .L_const_0x009_w, r13
    .word 0x0372 /* UNKNOWN */
    bra     .L_060427A0
    mov.l r6, @(r0, r3)
    .2byte  0xA48D
    .4byte  0x0359A7F3
    .4byte  0x034BAB4C
    .4byte  0x033EAE97
    .4byte  0x032FB1D5
    .4byte  0x0322B504
    .2byte  0x0313
.L_const_0xb826_w:
    .2byte  0xB826
    .4byte  0x0305BB39
    .4byte  0x02F6BE3E
    .4byte  0x02E7C134
    .4byte  0x02D8C41B
    .4byte  0x02C8C6F3
    .4byte  0x02B8C9BB
    .4byte  0x02A8CC73
    .4byte  0x0298CF1B
.L_060425A4:
    .word 0x0288 /* UNKNOWN */
    mov.l   .L_const_0xf737, r1
    .word 0x0278 /* UNKNOWN */
    mov.l   .L_fp_neg_30461_5ffd, r4
    mov.l r6, @(r0, r2)
    mov.l   .L_fp_one_2, r6
    mov.l r5, @(r0, r2)
    mov.l   .L_fp_110_fe98, r9
    mov.b r4, @(r0, r2)
    mov.l   .L_const_0x366a, r11
    mov.b r3, @(r0, r2)
    mov.l   .L_fp_27_2545, r13
    .word 0x0221 /* UNKNOWN */
    mov.l   .L_fp_3_4556, r15
    .word 0x0211 /* UNKNOWN */
    mov #0x8, r2
    mov.l @(r0, r15), r1
    mov #0x19, r4
    mov.b @(r0, r14), r1
    mov #0x17, r6
    .word 0x01DB /* UNKNOWN */
    mov #0x3, r8
    .word 0x01C8 /* UNKNOWN */
    mov #-0x22, r9
    mov.w r11, @(r0, r1)
    mov #-0x5A, r11
    mov.b r10, @(r0, r1)
    mov #0x5B, r13
    .word 0x0190 /* UNKNOWN */
    mov #-0x1, r14
    mov.l @(r0, r7), r1
    .word 0xF08F /* UNKNOWN */
    .word 0x016B /* UNKNOWN */
    .word 0xF20D /* UNKNOWN */
    .word 0x0158 /* UNKNOWN */
    .word 0xF378 /* UNKNOWN */
    mov.w r4, @(r0, r1)
    .word 0xF4D0 /* UNKNOWN */
    .word 0x0131 /* UNKNOWN */
    .word 0xF615 /* UNKNOWN */
    mac.l @r1+, @r1+
    .word 0xF746 /* UNKNOWN */
    .word 0x010B /* UNKNOWN */
    .word 0xF865 /* UNKNOWN */
    mul.l r15, r0
    .word 0xF970 /* UNKNOWN */
    mov.b r14, @(r0, r0)
    .word 0xFA67 /* UNKNOWN */
    .word 0x00D1 /* UNKNOWN */
    .word 0xFB4B /* UNKNOWN */
    mov.w @(r0, r11), r0
    .word 0xFC1C /* UNKNOWN */
    .word 0x00A9 /* UNKNOWN */
    .word 0xFCD9 /* UNKNOWN */
    mov.w r9, @(r0, r0)
    .word 0xFD82 /* UNKNOWN */
    .word 0x0081 /* UNKNOWN */
    .word 0xFE17 /* UNKNOWN */
.L_fp_110_fe98:
    .4byte  0x006EFE98
    .4byte  0x005AFF06
    .4byte  0x0046FF60
    .4byte  0x0032FFA6
    .4byte  0x001EFFD8
.L_0604262C:
    sts mach, r0
    .word 0xFFF6 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0xFFFF /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */

    .global math_trig_lib
    .type math_trig_lib, @function
math_trig_lib:
    sts.l pr, @-r15
    mov.l   .L_sym_06042714, r11
    cmp/pz r10
    bt/s    .L_06042652
    mov r4, r12
.L_const_0x65ab_w:
    .2byte  0x65AB
.L_06042652:
    cmp/pz r12
    bt      .L_06042658
    neg r12, r4
.L_06042658:
    mov #0x41, r2
    cmp/ge r2, r5
    bt      .L_06042664
    mov.l   .L_max_s16_w, r13
    bra     .L_06042674
    nop
.L_06042664:
    mov.l   .L_divu_dvsr, r0
    swap.w r4, r2
    mov.l r5, @r0
    exts.w r2, r2
    mov.l r2, @(16, r0)
    shll16 r4
    mov.l r4, @(20, r0)
    mov.l @(20, r0), r13
.L_06042674:
    mov #0x0, r4
    mov #0x5A, r5
.L_06042678:
    mov r4, r14
    add r5, r14
    shar r14
    mov r14, r0
    shll2 r0
    shll r0
    mov.l @(r0, r11), r2
    cmp/gt r13, r2
    bt      .L_0604269E
    mov r14, r4
    add #0x1, r4
    mov r4, r0
    shll2 r0
    shll r0
    mov.l @(r0, r11), r3
    cmp/ge r3, r13
.L_fp_neg_30461_5ffd:
    .4byte  0x8902A003
.L_const_0x009_w:
    .2byte  0x0009
.L_0604269E:
    mov r14, r5
    cmp/ge r5, r4
    bf      .L_06042678
    mov r14, r0
    mov r13, r4
    shll2 r0
    shll r0
    mov.l @(r0, r11), r3
    sub r3, r4
    add #0x4, r0
    mov.l @(r0, r11), r5
    dmuls.l r4, r5
    sts mach, r3
    sts macl, r4
    xtrct r3, r4
    mov.l   .L_fp_one, r2
    cmp/gt r2, r4
    bf      .L_060426C4
    mov.l   .L_fp_one, r4
.L_060426C4:
    mov r14, r0
    shll16 r0
    cmp/pz r12
    bt/s    .L_060426D0
    add r0, r4
    neg r4, r4
.L_060426D0:
    cmp/pz r10
    bt      .L_060426E4
    cmp/pz r12
    bf      .L_060426DE
    mov.l   .L_fp_180_2, r2
    bra     .L_060426E0
    nop
.L_060426DE:
    mov.l   .L_fp_neg_180, r2
.L_060426E0:
    sub r4, r2
    mov r2, r4
.L_060426E4:
    mov r4, r0
    lds.l @r15+, pr
    lds.l @r15+, macl
    lds.l @r15+, mach
    mov.l @r15+, r9
    mov.l @r15+, r10
    mov.l @r15+, r11
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14
    .2byte  0x0009
.L_divu_dvsr:
    .4byte  0xFFFFFF00
.L_sym_06042714:
    .4byte  sym_06042714
.L_max_s16_w:
.L_const_0x7fff_w:
    .2byte  0x7FFF
    .2byte  0x0000
.L_fp_one:
    .4byte  0x00010000
.L_fp_180_2:
    .4byte  0x00B40000
.L_fp_neg_180:
    .4byte  0xFF4C0000

    .global sym_06042714
sym_06042714:
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0039 /* UNKNOWN */
    .word 0x4A3A /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    mul.l r7, r4
    .word 0x0039 /* UNKNOWN */
    .word 0x414B /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x08F0 /* UNKNOWN */
    .word 0x0039 /* UNKNOWN */
    mov.b r7, @r15
    .word 0x0000 /* UNKNOWN */
    .word 0x0D6A /* UNKNOWN */
    .word 0x0039 /* UNKNOWN */
    mov.l r10, @(52, r4)
    .word 0x0000 /* UNKNOWN */
    mov.l r14, @(24, r1)
    .word 0x0038 /* UNKNOWN */
    .word 0xF10C /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    mov.l r6, @(20, r6)
    .word 0x0038 /* UNKNOWN */
    mov.b @(152, gbr), r0
    .word 0x0000 /* UNKNOWN */
    mov.l r14, @(32, r10)
    .word 0x0038 /* UNKNOWN */
    bf/s    .L_0604280C
    .word 0x0000 /* UNKNOWN */
    mov.l r6, @(56, r15)
    .word 0x0038 /* UNKNOWN */
    mov.l @(0, r7), r1
    .word 0x0000 /* UNKNOWN */
    xor r15, r3
    .word 0x0038 /* UNKNOWN */
    .word 0x0AE0 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    or r8, r8
    mul.l r3, r0
    .byte   0xBB, 0xC4    /* bsr 0x06041EEE (external) */
    .word 0x0000 /* UNKNOWN */
    .word 0x2D23 /* UNKNOWN */
    mul.l r3, r0
    mov.w @r3+, r4
    .word 0x0000 /* UNKNOWN */
    cmp/hs r12, r1
    mul.l r3, r0
    mac.l @r4+, @r4+
.L_const_0x366a:
    .4byte  0x0000366A
    .4byte  0x00369C2F
    .4byte  0x00003B1A
    .4byte  0x00362BF6
    .4byte  0x00003FD3
    .4byte  0x0035B3C7
    .4byte  0x00004498
    .4byte  0x003533C7
    .4byte  0x00004968
    .4byte  0x0034AC1E
    .4byte  0x00004E44
.L_060427A0:
    mov.b r3, @(r0, r0)
    mov.l r15, @(28, r12)
    .word 0x0000 /* UNKNOWN */
    mov.l @(52, r2), r3
    .word 0x0033 /* UNKNOWN */
    .word 0x867E /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    mov.l @(20, r2), r8
    .word 0x0032 /* UNKNOWN */
    mov #-0x1E, r8
    .word 0x0000 /* UNKNOWN */
    mov.l @(52, r2), r13
    .word 0x0032 /* UNKNOWN */
    .word 0x4454 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    mov.b @r4+, r2
    .word 0x0031 /* UNKNOWN */
    mov.w   .L_const_0x71fa_w, r9
    .word 0x0000 /* UNKNOWN */
    exts.b r6, r7
    .word 0x0030 /* UNKNOWN */
    mov #0x33, r7
    .word 0x0000 /* UNKNOWN */
    negc r10, r12
    .word 0x0030 /* UNKNOWN */
    cmp/str r0, r15
    .word 0x0000 /* UNKNOWN */
.L_const_0x71fa_w:
    .2byte  0x71FA
    .4byte  0x002F70CD
    .4byte  0x0000775F
    .4byte  0x002EACB2
    .4byte  0x00007CDC
    .4byte  0x002DE2F7
    .4byte  0x00008270
    .4byte  0x002D13DB
    .4byte  0x0000881E
    .4byte  0x002C3F9F
    .4byte  0x00008DE7
    .4byte  0x002B6686
    .4byte  0x000093CD
    .4byte  0x002A88D2
.L_0604280C:
    .word 0x0000 /* UNKNOWN */
    mov.w   .L_const_0x83ad_w, r9
    movt r0
    .byte   0xA6, 0xC9    /* bra 0x060435A8 (external) */
    .word 0x0000 /* UNKNOWN */
    .2byte  0x9FF7
    .4byte  0x0028C0B2
    .4byte  0x0000A63F
    .4byte  0x0027D6D3
    .4byte  0x0000ACAC
    .4byte  0x0026E978
    .4byte  0x0000B340
    .4byte  0x0025F8E8
    .4byte  0x0000B9FE
    .4byte  0x0025056F
    .4byte  0x0000C0E8
    .4byte  0x00240F5A
    .4byte  0x0000C802
    .4byte  0x002316F5
    .4byte  0x0000CF4E
    .4byte  0x00221C8D
    .4byte  0x0000D6CF
    .4byte  0x00212071
    .4byte  0x0000DE89
    .4byte  0x002022EE
    .4byte  0x0000E680
    .4byte  0x001F2455
    .4byte  0x0000EEB9
    .4byte  0x001E24F5
.L_const_0xf737:
    .4byte  0x0000F737
    .4byte  0x001D251D
.L_fp_one_2:
    .4byte  0x00010000
    .4byte  0x001C251D
    .4byte  0x00010918
.L_fp_27_2545:
    .4byte  0x001B2545
    .4byte  0x00011286
    .4byte  0x001A25E5
    .4byte  0x00011C51
    .4byte  0x0019274C
    .4byte  0x0001267E
    .4byte  0x001829C9
    .4byte  0x00013116
    .4byte  0x00172DAD
    .4byte  0x00013C22
    .4byte  0x00163345
    .4byte  0x000147AA
    .4byte  0x00153AE0
    .4byte  0x000153B9
    .4byte  0x001444CB
    .4byte  0x0001605A
    .4byte  0x00135152
    .4byte  0x00016D9B
    .4byte  0x001260C2
    .4byte  0x00017B89
    .4byte  0x00117366
    .4byte  0x00018A34
    .4byte  0x00108988
    .4byte  0x000199AF
    .4byte  0x000FA371
    .4byte  0x0001AA0E
    .4byte  0x000EC168
    .4byte  0x0001BB67
    .4byte  0x000DE3B4
    .4byte  0x0001CDD6
    .4byte  0x000D0A9B
    .4byte  0x0001E177
    .4byte  0x000C365F
    .4byte  0x0001F66D
    .4byte  0x000B6743
    .4byte  0x00020CE0
    .4byte  0x000A9D88
    .4byte  0x000224FE
    .4byte  0x0009D96D
    .4byte  0x00023EFC
    .4byte  0x00091B2E
    .4byte  0x00025B19
    .4byte  0x00086307
    .4byte  0x0002799F
    .4byte  0x0007B132
    .4byte  0x00029AE7
    .4byte  0x000705E6
    .4byte  0x0002BF5A
    .4byte  0x00066158
    .4byte  0x0002E77A
    .4byte  0x0005C3BC
    .4byte  0x000313E3
    .4byte  0x00052D43
.L_fp_3_4556:
    .4byte  0x00034556
    .4byte  0x00049E1C
    .4byte  0x00037CC7
    .4byte  0x00041673
    .4byte  0x0003BB67
    .4byte  0x00039673
    .4byte  0x000402C2
    .4byte  0x00031E44
    .4byte  0x000454DB
    .4byte  0x0002AE0B
    .4byte  0x0004B462
    .4byte  0x000245EB
    .4byte  0x00052501
    .4byte  0x0001E605
    .4byte  0x0005ABD9
    .4byte  0x00018E76
    .4byte  0x00065052
    .4byte  0x00013F5A
    .4byte  0x00071D88
    .4byte  0x0000F8CA
    .4byte  0x000824F3
    .4byte  0x0000BADB
    .2byte  0x0009
.L_const_0x83ad_w:
    .2byte  0x83AD
    .4byte  0x000085A2
    .4byte  0x000B6E17
    .4byte  0x0000592D
    .4byte  0x000E4CF8
    .4byte  0x0000358D
    .4byte  0x001314C5
    .4byte  0x00001ACA
    .4byte  0x001CA2E1
    .4byte  0x000008EF
    .4byte  0x00394A3A
    .4byte  0x00000105
    .4byte  0x7FFFFFFF
    .4byte  0x00000000

    .global color_palette_effect
    .type color_palette_effect, @function
color_palette_effect:
    mov.l r14, @-r15
    mov r6, r14
    mov.l r13, @-r15
    sts.l pr, @-r15
    add #-0xC, r15
    mov.l r4, @r15
    mov.l r5, @(4, r15)
    mov.l   .L_sym_0603C156, r3
    jsr @r3
    mov.l r7, @(8, r15)
    cmp/eq #0x2, r0
    bf      .L_06042A3A
    mov.l @(8, r15), r13
    mov.l   .L_sym_06042BFC, r3
    .4byte  0x430B64F2
    .4byte  0x4018D21D
    .4byte  0x53F14008
    .4byte  0x4308302C
    .4byte  0x6403343C
    .4byte  0x60E38801
    .4byte  0x8B0262D2
    .4byte  0xA0242422
    .4byte  0x66E34608
    .4byte  0x65D37F0C
    .4byte  0x4F266DF6
    .4byte  0xD314432B
    .2byte  0x6EF6
.L_06042A3A:
    mov.l @(8, r15), r13
    mov.l   .L_sym_06042BFC, r3
    jsr @r3
    mov.l @r15, r4
    shll8 r0
    mov.l   .L_vdp2_cram_00000, r2
    mov.l @(4, r15), r3
    .4byte  0x40004300
    .4byte  0x302C6403
    .4byte  0x343C60E3
    .4byte  0x88018B02
    .4byte  0x62D1A009
    .4byte  0x242166E3
    .4byte  0x460065D3
    .4byte  0x7F0C4F26
    .4byte  0x6DF6D307
    .4byte  0x432B6EF6
    .4byte  0x7F0C4F26
    .4byte  0x6DF6000B
    .4byte  0x6EF6FFFF
.L_sym_0603C156:
    .4byte  sym_0603C156
.L_sym_06042BFC:
    .4byte  sym_06042BFC
.L_vdp2_cram_00000:
    .4byte  0x25F00000
    .4byte  sym_06038A48

    .global sym_06042A8C
sym_06042A8C:
    mov #-0x50, r6
    mov #-0x9, r3
    mov.l @r4, r2
    mov #0x4, r7
    mov.l @r6, r5
    and r3, r5
    or r2, r5
    mov.l @(8, r4), r3
    and r7, r3
    cmp/eq r7, r3
    bf      .L_06042AAA
    mov #-0x2, r3
    and r3, r5
    mov.l @(4, r4), r2
    or r2, r5
.L_06042AAA:
    mov #0x1, r7
    mov.l @(8, r4), r3
    and r7, r3
    cmp/eq r7, r3
    bf      .L_06042AB8
    mov #-0x5, r3
    and r3, r5
.L_06042AB8:
    mov #0x2, r7
    mov.l @(8, r4), r2
    and r7, r2
    cmp/eq r7, r2
    bf      .L_06042AC6
    mov #-0x3, r2
    and r2, r5
.L_06042AC6:
    rts
    mov.l r5, @r6
