/* game_logic_main -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0603A0B0 - 0x0603A7B0
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0603A0B0


    .global game_logic_main
    .type game_logic_main, @function
game_logic_main:
    mov.l r14, @-r15
    mov.l r13, @-r15
    mov.l r12, @-r15
    mov.l r11, @-r15
    sts.l macl, @-r15
    mov #0x10, r11
    add #-0x8, r15
    mov.l   .L_pool_0603A1A8, r13
    mov.l   .L_pool_0603A1AC, r7
    mov.l   .L_pool_0603A1B0, r6
    mov.l   .L_pool_0603A1B4, r5
    mov.l   .L_pool_0603A1B8, r4
    mov.l   .L_pool_0603A1BC, r0
    mov.b @r0, r0
    extu.b r0, r0
    cmp/eq #0x20, r0
    bt/s    .L_0603A0D8
    mov #0x20, r12
    bra     .L_0603A288
    nop
.L_0603A0D8:
    mov.l @r4, r2
    mov.w   DAT_0603a1a2, r3
    mov.b r3, @r2
    mov.b @r5, r0
    mov.l @r4, r3
    mov.w   DAT_0603a1a2, r2
    extu.b r0, r0
    add r3, r0
    mov.b r2, @r0
    mov.b @r5, r0
    mov.l @r4, r3
    extu.b r0, r0
    shll r0
    mov.b @(r0, r3), r0
    mov.w   .L_wpool_0603A1A4, r3
    extu.b r0, r0
    and #0x80, r0
    cmp/eq r3, r0
    bf      .L_0603A12E
    mov.b @r5, r0
    mov.l @r4, r3
    extu.b r0, r0
    shll r0
    add r3, r0
    mov.b @r0, r2
    extu.b r2, r2
    and r12, r2
    cmp/eq r12, r2
    bf      .L_0603A120
    mov.l @r4, r3
    mov #-0x21, r2
    mov.b @r3, r1
    and r2, r1
    mov.b r1, @r3
    bra     .L_0603A16E
    nop
.L_0603A120:
    mov.l @r4, r3
    mov #-0x11, r2
    mov.b @r3, r1
    and r2, r1
    mov.b r1, @r3
    bra     .L_0603A16E
    nop
.L_0603A12E:
    mov.b @r5, r0
    mov.l @r4, r3
    extu.b r0, r0
    shll2 r0
    add r3, r0
    mov.b @r0, r2
    mov #0xA, r3
    extu.b r2, r2
    cmp/gt r3, r2
    bf      .L_0603A16E
    mov.b @r5, r0
    mov.l @r4, r3
    extu.b r0, r0
    shll r0
    add r3, r0
    mov.b @r0, r2
    extu.b r2, r2
    and r12, r2
    cmp/eq r12, r2
    bf      .L_0603A164
    mov.l @r4, r3
    mov #-0x21, r2
    mov.b @r3, r1
    and r2, r1
    mov.b r1, @r3
    bra     .L_0603A16E
    nop
.L_0603A164:
    mov.l @r4, r3
    mov #-0x11, r2
    mov.b @r3, r1
    and r2, r1
    mov.b r1, @r3
.L_0603A16E:
    mov.b @r5, r0
    mov.l @r4, r3
    extu.b r0, r0
    shll r0
    mov.b @(r0, r3), r0
    extu.b r0, r0
    and #0x40, r0
    cmp/eq #0x40, r0
    bf      .L_0603A1CE
    mov.b @r5, r0
    mov.l @r4, r3
    extu.b r0, r0
    shll r0
    add r3, r0
    mov.b @r0, r2
    extu.b r2, r2
    and r11, r2
    cmp/eq r11, r2
    bf      .L_0603A1C0
    mov.l @r4, r3
    mov #-0x41, r2
    mov.b @r3, r1
    and r2, r1
    mov.b r1, @r3
    bra     .L_0603A212
    nop

    .global DAT_0603a1a2
DAT_0603a1a2:
    .2byte  0x00FF
.L_wpool_0603A1A4:
    .2byte  0x0080
    .2byte  0xFFFF
.L_pool_0603A1A8:
    .4byte  sym_060A4CAE
.L_pool_0603A1AC:
    .4byte  sym_060A4CB4
.L_pool_0603A1B0:
    .4byte  sym_060A4CC0
.L_pool_0603A1B4:
    .4byte  sym_060A4CCC
.L_pool_0603A1B8:
    .4byte  sym_060A4CD0
.L_pool_0603A1BC:
    .4byte  sym_060A4CFC
.L_0603A1C0:
    mov.l @r4, r3
    mov.w   DAT_0603a2ca, r2
    mov.b @r3, r1
    and r2, r1
    mov.b r1, @r3
    bra     .L_0603A212
    nop
.L_0603A1CE:
    mov.b @r5, r0
    mov.l @r4, r2
    extu.b r0, r0
    mov r0, r3
    shll r0
    add r3, r0
    add r2, r0
    mov.b @r0, r3
    mov #0xA, r2
    extu.b r3, r3
    cmp/gt r2, r3
    bf      .L_0603A212
    mov.b @r5, r0
    mov.l @r4, r3
    extu.b r0, r0
    shll r0
    add r3, r0
    mov.b @r0, r2
    extu.b r2, r2
    and r11, r2
    cmp/eq r11, r2
    bf      .L_0603A208
    mov.l @r4, r3
    mov #-0x41, r2
    mov.b @r3, r1
    and r2, r1
    mov.b r1, @r3
    bra     .L_0603A212
    nop
.L_0603A208:
    mov.l @r4, r3
    mov.w   DAT_0603a2ca, r2
    mov.b @r3, r1
    and r2, r1
    mov.b r1, @r3
.L_0603A212:
    mov.b @r5, r0
    mov.l @r4, r3
    extu.b r0, r0
    shll r0
    mov.b @(r0, r3), r0
    extu.b r0, r0
    and #0x1, r0
    cmp/eq #0x1, r0
    bf      .L_0603A22E
    mov.l @r4, r3
    mov #-0x5, r2
    mov.b @r3, r1
    and r2, r1
    mov.b r1, @r3
.L_0603A22E:
    mov.b @r5, r0
    mov.l @r4, r3
    extu.b r0, r0
    shll r0
    mov.b @(r0, r3), r0
    extu.b r0, r0
    and #0x4, r0
    cmp/eq #0x4, r0
    bf      .L_0603A24A
    mov.l @r4, r3
    mov #-0x2, r2
    mov.b @r3, r1
    and r2, r1
    mov.b r1, @r3
.L_0603A24A:
    mov.b @r5, r0
    mov.l @r4, r3
    extu.b r0, r0
    shll r0
    mov.b @(r0, r3), r0
    extu.b r0, r0
    and #0x2, r0
    cmp/eq #0x2, r0
    bf      .L_0603A266
    mov.l @r4, r3
    mov #-0x3, r2
    mov.b @r3, r1
    and r2, r1
    mov.b r1, @r3
.L_0603A266:
    mov.b @r5, r0
    mov.l @r4, r3
    extu.b r0, r0
    shll r0
    mov.b @(r0, r3), r0
    extu.b r0, r0
    and #0x8, r0
    cmp/eq #0x8, r0
    bf      .L_0603A282
    mov.l @r4, r3
    mov #-0x9, r2
    mov.b @r3, r1
    and r2, r1
    mov.b r1, @r3
.L_0603A282:
    mov.l   .L_pool_0603A2CC, r3
    mov.b @r3, r3
    mov.b r3, @r13
.L_0603A288:
    mov.l   .L_pool_0603A2D0, r14
    mov.l   .L_pool_0603A2D4, r0
    mov.b @r0, r0
    bra     .L_0603A67C
    extu.b r0, r0
.L_0603A292:
    bra     .L_0603A2BE
    mov #0x0, r14
.L_0603A296:
    mov.b @r13, r2
    extu.b r2, r2
    add #0x1, r2
    mov.l @r7, r3
    mul.l r3, r2
    sts macl, r2
    mov.l @r6, r1
    add r1, r2
    add r14, r2
    mov.b @r5, r0
    extu.b r0, r0
    mul.l r14, r0
    sts macl, r0
    mov.l @r4, r3
    add r3, r0
    mov.b @r0, r1
    mov #0x1, r3
    add r2, r3
    mov.b r1, @r3
    add #0x1, r14
.L_0603A2BE:
    mov.b @r13, r2
    extu.b r2, r2
    cmp/hs r2, r14
    bf      .L_0603A296
    bra     .L_0603A6B2
    nop

    .global DAT_0603a2ca
DAT_0603a2ca:
    .2byte  0xFF7F
.L_pool_0603A2CC:
    .4byte  sym_060A4D02
.L_pool_0603A2D0:
    .4byte  sym_060A4CBC
.L_pool_0603A2D4:
    .4byte  sym_060A4CAF
.L_0603A2D8:
    mov.l @r7, r2
    mov.l @r6, r1
    mov.b @r5, r0
    mov r2, r3
    extu.b r0, r0
    shll r2
    shll2 r3
    add r3, r2
    add r1, r2
    mov.l @r4, r3
    mov.b @(r0, r3), r1
    extu.b r1, r1
    mov.b @r3, r0
    extu.b r0, r0
    shll8 r0
    or r0, r1
    mov.w r1, @r2
    mov.l @r7, r3
    mov r3, r2
    shll r3
    shll2 r2
    add r2, r3
    mov.l r3, @(4, r15)
    mov.l @r6, r2
    add r2, r3
    mov.l r3, @r15
    mov.l @(4, r15), r2
    mov.l @r14, r1
    add r1, r2
    mov.w @r2, r2
    extu.w r2, r2
    not r2, r2
    mov r3, r1
    mov.w @r1, r1
    extu.w r1, r1
    or r1, r2
    extu.w r2, r2
    mov r2, r0
    mov.w r0, @(2, r3)
    bra     .L_0603A6B2
    nop
.L_0603A32A:
    mov.l @r7, r2
    mov.l @r6, r1
    mov.b @r5, r0
    mov r2, r3
    extu.b r0, r0
    shll r2
    shll2 r3
    shll2 r3
    add r3, r2
    add r1, r2
    mov.l @r4, r3
    mov.b @(r0, r3), r1
    extu.b r1, r1
    mov.b @r3, r0
    extu.b r0, r0
    shll8 r0
    or r0, r1
    mov.w r1, @r2
    mov.l @r7, r3
    mov.l @r6, r1
    mov.b @r5, r0
    mov r3, r2
    extu.b r0, r0
    shll r3
    shll2 r2
    shll2 r2
    add r2, r3
    add r1, r3
    shll r0
    mov.l @r4, r2
    mov.b @(r0, r2), r1
    extu.b r1, r0
    mov.w r0, @(2, r3)
    mov.l @r7, r3
    mov.l @r6, r1
    mov.b @r5, r0
    mov r3, r2
    extu.b r0, r0
    shll r3
    shll2 r2
    shll2 r2
    add r2, r3
    add r1, r3
    mov r0, r2
    mov.l @r4, r1
    shll r0
    add r2, r0
    mov.b @(r0, r1), r2
    extu.b r2, r0
    mov.w r0, @(4, r3)
    mov.l @r7, r3
    mov r3, r2
    shll r3
    shll2 r2
    shll2 r2
    add r2, r3
    mov.l @r6, r1
    add r1, r3
    mov.b @r5, r0
    extu.b r0, r0
    shll2 r0
    mov.l @r4, r2
    mov.b @(r0, r2), r1
    extu.b r1, r0
    mov.w r0, @(6, r3)
    mov.l @r7, r3
    mov r3, r2
    shll r3
    shll2 r2
    shll2 r2
    add r2, r3
    mov.l r3, @(4, r15)
    mov.l @r6, r2
    add r2, r3
    mov.l r3, @r15
    mov.l @(4, r15), r2
    mov.l @r14, r1
    add r1, r2
    mov r3, r1
    mov.w @r2, r2
    mov.w @r1, r1
    extu.w r2, r2
    extu.w r1, r1
    not r2, r2
    or r1, r2
    extu.w r2, r0
    mov.w r0, @(8, r3)
    mov.l @r7, r3
    mov r3, r2
    shll r3
    shll2 r2
    shll2 r2
    add r2, r3
    mov.l r3, @(4, r15)
    mov.l @r6, r2
    add r2, r3
    mov.l r3, @r15
    mov.l @(4, r15), r2
    mov.l @r14, r1
    add r1, r2
    mov.w @(2, r2), r0
    mov r3, r1
    mov r0, r2
    mov.w @(2, r1), r0
    mov r0, r1
    sub r1, r2
    exts.w r2, r0
    mov.w r0, @(10, r3)
    mov.l @r7, r3
    mov r3, r2
    shll r3
    shll2 r2
    shll2 r2
    add r2, r3
    mov.l r3, @(4, r15)
    mov.l @r6, r2
    add r2, r3
    mov.l r3, @r15
    mov.l @(4, r15), r2
    mov.l @r14, r1
    add r1, r2
    mov.w @(4, r2), r0
    mov r0, r2
    mov r3, r1
    mov.w @(4, r1), r0
    mov r0, r1
    sub r1, r2
    exts.w r2, r0
    mov.w r0, @(12, r3)
    mov.l @r7, r3
    mov r3, r2
    shll r3
    shll2 r2
    shll2 r2
    add r2, r3
    mov.l r3, @(4, r15)
    mov.l @r6, r2
    add r2, r3
    mov.l r3, @r15
    mov.l @(4, r15), r2
    mov.l @r14, r1
    add r1, r2
    mov.w @(6, r2), r0
    mov r0, r2
    mov r3, r1
    mov.w @(6, r1), r0
    mov r0, r1
    sub r1, r2
    exts.w r2, r2
    mov r2, r0
    mov.w r0, @(14, r3)
    bra     .L_0603A6B2
    nop
.L_0603A45C:
    mov.l @r7, r2
    mov.l @r6, r1
    mov.b @r5, r0
    mov r2, r3
    extu.b r0, r0
    shll r2
    shll2 r3
    shll2 r3
    add r3, r2
    add r1, r2
    mov.l @r4, r3
    mov.b @(r0, r3), r1
    mov.b @r3, r0
    extu.b r1, r1
    extu.b r0, r0
    shll8 r0
    or r0, r1
    mov.w r1, @r2
    mov.l @r7, r3
    mov.l @r6, r1
    mov.b @r5, r0
    mov r3, r2
    extu.b r0, r0
    shll r3
    shll2 r2
    shll2 r2
    add r2, r3
    add r1, r3
    shll r0
    mov.l @r4, r2
    mov.b @(r0, r2), r1
    extu.b r1, r1
    not r1, r1
    extu.w r1, r0
    mov.w r0, @(2, r3)
    mov.l @r7, r3
    mov.l @r6, r1
    mov r3, r2
    shll r3
    shll2 r2
    shll2 r2
    add r2, r3
    add r1, r3
    mov.l r3, @r15
    mov.b @r5, r0
    mov.l @r4, r1
    extu.b r0, r0
    mov r0, r2
    shll r0
    add r2, r0
    mov.b @(r0, r1), r2
    mov r3, r0
    mov #0x2, r1
    mov.w @(r0, r1), r1
    extu.w r1, r1
    and r11, r1
    cmp/eq r11, r1
    bf/s    .L_0603A4D6
    extu.b r2, r2
    bra     .L_0603A4D8
    mov #0x1, r1
.L_0603A4D6:
    mov #-0x1, r1
.L_0603A4D8:
    mul.l r1, r2
    sts macl, r2
    exts.w r2, r0
    mov.w r0, @(4, r3)
    mov.l @r7, r3
    mov.l @r6, r1
    mov r3, r2
    shll r3
    shll2 r2
    shll2 r2
    add r2, r3
    add r1, r3
    mov.l r3, @r15
    mov.b @r5, r0
    mov.l @r4, r2
    extu.b r0, r0
    shll2 r0
    mov.b @(r0, r2), r1
    mov r3, r0
    mov #0x2, r2
    mov.w @(r0, r2), r2
    extu.w r2, r2
    and r12, r2
    cmp/eq r12, r2
    bf/s    .L_0603A510
    extu.b r1, r1
    bra     .L_0603A512
    mov #0x1, r2
.L_0603A510:
    mov #-0x1, r2
.L_0603A512:
    mul.l r2, r1
    sts macl, r1
    exts.w r1, r0
    mov.w r0, @(6, r3)
    mov.l @r7, r3
    mov r3, r2
    shll r3
    shll2 r2
    shll2 r2
    add r2, r3
    mov.l r3, @r15
    mov.l @r6, r2
    add r2, r3
    mov.l r3, @(4, r15)
    mov.l @r15, r2
    mov.l @r14, r1
    add r1, r2
    mov.w @r2, r2
    extu.w r2, r2
    not r2, r2
    mov r3, r1
    mov.w @r1, r1
    extu.w r1, r1
    or r1, r2
    extu.w r2, r2
    mov r2, r0
    mov.w r0, @(8, r3)
    bra     .L_0603A6B2
    nop
.L_0603A54C:
    mov.l @r7, r2
    mov.l @r6, r1
    mov.b @r5, r0
    mov r2, r3
    extu.b r0, r0
    shll r2
    shll2 r3
    shll r3
    add r3, r2
    add r1, r2
    mov.l @r4, r3
    mov.b @(r0, r3), r1
    mov.b @r3, r0
    extu.b r1, r1
    extu.b r0, r0
    shll8 r0
    or r0, r1
    mov.w r1, @r2
    mov.l @r7, r3
    mov.l @r6, r1
    mov.b @r5, r0
    mov r3, r2
    extu.b r0, r0
    shll r3
    shll2 r2
    shll r2
    add r2, r3
    add r1, r3
    shll r0
    mov.l @r4, r2
    mov.b @(r0, r2), r1
    extu.b r1, r1
    not r1, r1
    extu.b r1, r0
    mov.b r0, @(2, r3)
    mov.l @r7, r3
    mov.l @r6, r1
    mov.b @r5, r0
    mov r3, r2
    extu.b r0, r0
    shll r3
    shll2 r2
    shll r2
    add r2, r3
    add r1, r3
    mov r0, r2
    mov.l @r4, r1
    shll r0
    add r2, r0
    add r1, r0
    mov.b @r0, r2
    mov #0x3, r1
    add r3, r1
    mov.b r2, @r1
    mov.l @r7, r3
    mov r3, r2
    shll r3
    shll2 r2
    shll r2
    add r2, r3
    mov.l r3, @(4, r15)
    mov.l @r6, r2
    add r2, r3
    mov.l r3, @r15
    mov.l @(4, r15), r2
    mov.l @r14, r1
    add r1, r2
    mov.w @r2, r2
    extu.w r2, r2
    not r2, r2
    mov r3, r1
    mov.w @r1, r1
    extu.w r1, r1
    or r1, r2
    extu.w r2, r2
    mov r2, r0
    mov.w r0, @(4, r3)
    bra     .L_0603A6B2
    nop
.L_0603A5EA:
    mov.l @r7, r2
    mov.l @r6, r1
    mov r2, r3
    shll r2
    add r3, r2
    add r1, r2
    mov.l @r4, r3
    mov.b @r3, r1
    mov.b r1, @r2
    mov.l @r7, r3
    mov r3, r2
    shll r3
    add r2, r3
    mov.l r3, @r15
    mov.l @r6, r2
    add r2, r3
    mov.l r3, @(4, r15)
    mov.l @r15, r2
    mov.l @r14, r1
    add r1, r2
    mov.b @r2, r2
    extu.b r2, r2
    not r2, r2
    mov r3, r1
    mov.b @r1, r1
    extu.b r1, r1
    or r1, r2
    extu.b r2, r2
    mov r2, r0
    mov.b r0, @(1, r3)
    bra     .L_0603A6B2
    nop
.L_0603A62A:
    mov.l @r7, r2
    mov.l @r6, r1
    mov.b @r5, r0
    mov r2, r3
    extu.b r0, r0
    shll r2
    shll2 r3
    add r3, r2
    add r1, r2
    mov.l @r4, r3
    mov.b @(r0, r3), r1
    mov.b @r3, r0
    extu.b r1, r1
    extu.b r0, r0
    shll8 r0
    or r0, r1
    mov.w r1, @r2
    mov.l @r7, r3
    mov r3, r2
    shll r3
    shll2 r2
    add r2, r3
    mov.l r3, @r15
    mov.l @r6, r2
    add r2, r3
    mov.l r3, @(4, r15)
    mov.l @r15, r2
    mov.l @r14, r1
    add r1, r2
    mov.w @r2, r2
    extu.w r2, r2
    not r2, r2
    mov r3, r1
    mov.w @r1, r1
    extu.w r1, r1
    or r1, r2
    extu.w r2, r2
    mov r2, r0
    mov.w r0, @(2, r3)
    bra     .L_0603A6B2
    nop
.L_0603A67C:
    cmp/eq #0x0, r0
    bf      .L_0603A684
    bra     .L_0603A2D8
    nop
.L_0603A684:
    cmp/eq #0x10, r0
    bf      .L_0603A68C
    bra     .L_0603A32A
    nop
.L_0603A68C:
    cmp/eq #0x20, r0
    bf      .L_0603A694
    bra     .L_0603A45C
    nop
.L_0603A694:
    cmp/eq #0x30, r0
    bf      .L_0603A69C
    bra     .L_0603A54C
    nop
.L_0603A69C:
    mov.w   .L_wpool_0603A6FA, r1
    cmp/eq r1, r0
    bt      .L_0603A5EA
    mov.w   .L_wpool_0603A6FC, r1
    cmp/eq r1, r0
    bt      .L_0603A62A
    mov.w   DAT_0603a6fe, r1
    cmp/eq r1, r0
    bf      .L_0603A6B2
    bra     .L_0603A292
    nop
.L_0603A6B2:
    add #0x8, r15
    lds.l @r15+, macl
    mov.l @r15+, r11
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14
    .4byte  0xE301E400
    .4byte  0xD20E604C
    .4byte  0x2230634C
    .4byte  0xD20D2230
    .4byte  0xD20D634C
    .4byte  0x2240D20D
    .4byte  0x2200604C
    .4byte  0xD20C2230
    .4byte  0xD20C2240
    .4byte  0xD20C2200
    .4byte  0xD30C2342
    .4byte  0xD30C2342
    .4byte  0xD30C2342
    .4byte  0xD30C000B
    .2byte  0x2340
.L_wpool_0603A6FA:
    .2byte  0x00E1
.L_wpool_0603A6FC:
    .2byte  0x00E2

    .global DAT_0603a6fe
DAT_0603a6fe:
    .2byte  0x00FF
    .4byte  sym_060A4D0C
    .4byte  sym_060A4D0D
    .4byte  sym_060A4D0E
    .4byte  sym_060A4D0F
    .4byte  sym_060A4D10
    .4byte  sym_060A4D11
    .4byte  sym_060A4CD8
    .4byte  sym_060A4CB4
    .4byte  sym_060A4CF0
    .4byte  sym_060A4CF8
    .4byte  sym_060A4CA9

    .global sym_0603A72C
sym_0603A72C:
    mov.l   .L_pool_0603A79C, r5
    mov #0x1, r4
    mov.b @r5, r3
    extu.b r3, r3
    and r4, r3
    cmp/eq r4, r3
    bf      .L_0603A73E
    rts
    mov #0x1, r0
.L_0603A73E:
    extu.b r4, r4
    mov.b r4, @r5
    mov.l   .L_pool_0603A7A0, r4
    mov.b @r4, r3
    mov.l   .L_pool_0603A7A4, r2
    mov.b r3, @r2
    mov.b @(1, r4), r0
    mov r0, r3
    add #0x2, r2
    mov.b r3, @r2
    mov.b @(2, r4), r0
    mov r0, r3
    add #0x2, r2
    mov.b r3, @r2
    mov #0x10, r3
    add #0x1A, r2
    mov.b r3, @r2
    mov #0x0, r0
    rts
    nop

    .global display_channel_iter
    .type display_channel_iter, @function
display_channel_iter:
    mov.l r14, @-r15
    mov.l r13, @-r15
    mov.l r12, @-r15
    sts.l pr, @-r15
    mov.l   .L_pool_0603A7A8, r12
    mov.w   .L_wpool_0603A79A, r13
    mov.l   .L_pool_0603A7AC, r14
    bra     .L_0603A786
    nop
.L_0603A778:
    .byte   0xB1, 0xE5    /* bsr 0x0603AB46 (external) */
    extu.b r13, r4
    .byte   0xB0, 0x18    /* bsr 0x0603A7B0 (external) */
    nop
    mov.l @r14, r2
    add #0x1, r2
    mov.l r2, @r14
.L_0603A786:
    mov.w @r12, r3
    mov.l @r14, r2
    extu.w r3, r3
    cmp/ge r3, r2
    bf      .L_0603A778
    lds.l @r15+, pr
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14
.L_wpool_0603A79A:
    .2byte  0x00FF
.L_pool_0603A79C:
    .4byte  0x20100063
.L_pool_0603A7A0:
    .4byte  sym_06063602
.L_pool_0603A7A4:
    .4byte  0x20100001
.L_pool_0603A7A8:
    .4byte  sym_060A4CAC
.L_pool_0603A7AC:
    .4byte  sym_060A4CB4
