/* geom_output_dispatch -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0601F900 - 0x0601FE20
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0601F900


    .global geom_output_dispatch
    .type geom_output_dispatch, @function
geom_output_dispatch:
    sts.l pr, @-r15
    add #-0x4, r15
    mov.l   .L_sym_06063D9A, r3
    mov.w @r3, r2
    mov.w   DAT_0601f962, r3
    extu.w r2, r2
    and r3, r2
    tst r2, r2
    bt      .L_0601F928
    mov.w   DAT_0601f964, r3
    mov r15, r6
    mov.w r3, @r15
    mov.l   .L_vdp2_vram_7fffe, r4
    mov.l   .L_tilemap_dma_update, r3
    jsr @r3
    mov #0x1, r5
    add #0x4, r15
    lds.l @r15+, pr
    rts
    mov #0x1, r0
.L_0601F928:
    bsr     geom_display_ctrl_a
    nop
    mov #0x0, r0
    add #0x4, r15
    lds.l @r15+, pr
    rts
    nop

    .global sym_0601F936
sym_0601F936:
    mov #0x0, r3

    .global resource_validator
    .type resource_validator, @function
resource_validator:
    mov.l r14, @-r15
    mov r3, r4
    mov.l r13, @-r15
    mov.l r12, @-r15
    sts.l pr, @-r15
    mov.w   DAT_0601f962, r13
    mov.l   .L_sym_0605B6D8, r14
    mov.l   .L_sym_0605E05C, r2
    mov.b r3, @r2
    .byte   0xBF, 0x96    /* bsr 0x0601F87A (external) */
    nop
    mov.l   .L_geom_vertex_process, r3
    jsr @r3
    nop
    mov.l   .L_sym_0605E05C, r2
    mov.b @r2, r2
    extu.b r2, r2
    tst r2, r2
    bf      .L_0601F980
    bra     .L_0601F9C2
    nop

    .global DAT_0601f962
DAT_0601f962:
    .2byte  0x0800

    .global DAT_0601f964
DAT_0601f964:
    .2byte  0x4210
    .2byte  0xFFFF
.L_sym_06063D9A:
    .4byte  sym_06063D9A
.L_vdp2_vram_7fffe:
    .4byte  0x25E7FFFE
.L_tilemap_dma_update:
    .4byte  tilemap_dma_update
.L_sym_0605B6D8:
    .4byte  sym_0605B6D8
.L_sym_0605E05C:
    .4byte  sym_0605E05C
.L_geom_vertex_process:
    .4byte  geom_vertex_process
.L_0601F980:
    mov.l   .L_min_s32, r3
    mov.l @r14, r2
    or r3, r2
    mov.l   .L_sym_06026CE0, r3
    jsr @r3
    mov.l r2, @r14
    mov.l   .L_sym_06026CE0, r3
    jsr @r3
    nop
    bsr     geom_output_main
    nop
    mov.l   .L_bit_30, r2
    mov.l @r14, r3
    or r2, r3
    mov.l r3, @r14
    mov.l   .L_sym_06063D9A_2, r12
.L_0601F9A0:
    bsr     geom_display_ctrl_a
    nop
    mov.w @r12, r2
    extu.w r2, r2
    and r13, r2
    tst r2, r2
    bt      .L_0601F9B2
    bra     .L_0601F9B6
    nop
.L_0601F9B2:
    bra     .L_0601F9A0
    nop
.L_0601F9B6:
    bsr     geom_display_ctrl_a
    nop
    mov.l   .L_min_s32, r2
    mov.l @r14, r3
    or r2, r3
    mov.l r3, @r14
.L_0601F9C2:
    lds.l @r15+, pr
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14

    .global geom_output_main
    .type geom_output_main, @function
geom_output_main:
    mov.l r14, @-r15
    mov.l r13, @-r15
    mov.l r12, @-r15
    mov.l r11, @-r15
    mov.l r10, @-r15
    mov.l r9, @-r15
    mov.l r8, @-r15
    sts.l pr, @-r15
    add #-0x8, r15
    mov.w   DAT_0601fa26, r3
    mov r3, r0
    mov.w r0, @(4, r15)
    mov.l   .L_sym_0602853E, r3
    jsr @r3
    mov #0xC, r4
    mov.l   .L_sym_06028560, r3
    jsr @r3
    nop
    mov.l   .L_sym_06063750, r11
    mov.l   .L_sym_06028400, r12
    mov.l   .L_sym_06078644, r0
    mov.l @r0, r0
    cmp/eq #0x1, r0
    bf      .L_0601FAA8
    mov #0x8, r7
    mov.l   .L_fp_1_7700, r5
    mov.l   .L_vdp2_vram_72194, r4
    mov.l   .L_sym_0600511E, r3
    jsr @r3
    mov #0x0, r6
    mov.l   .L_sym_0604894C, r5
    mov.l   .L_vdp2_cram_00600, r4
    mov.l   .L_memcpy_word_idx, r3
    jsr @r3
    mov #0x20, r6
    mov.l   .L_sym_0605E05C_2, r0
    mov.b @r0, r0
    bra     .L_0601FA98
    extu.b r0, r0
.L_0601FA1A:
    mov.w   .L_const_0x2c0_w, r7
    add r11, r7
    mov.l r7, @r15
    mov.l @(4, r7), r7
    bra     .L_0601FA76
    mov #0x0, r6

    .global DAT_0601fa26
DAT_0601fa26:
    .2byte  0x7C00
.L_const_0x2c0_w:
    .2byte  0x02C0
    .2byte  0xFFFF
.L_min_s32:
    .4byte  0x80000000
.L_sym_06026CE0:
    .4byte  sym_06026CE0
.L_bit_30:
    .4byte  0x40000000
.L_sym_06063D9A_2:
    .4byte  sym_06063D9A
.L_sym_0602853E:
    .4byte  sym_0602853E
.L_sym_06028560:
    .4byte  sym_06028560
.L_sym_06063750:
    .4byte  sym_06063750
.L_sym_06028400:
    .4byte  sym_06028400
.L_sym_06078644:
    .4byte  sym_06078644
.L_fp_1_7700:
    .4byte  0x00017700
.L_vdp2_vram_72194:
    .4byte  0x25E72194
.L_sym_0600511E:
    .4byte  sym_0600511E
.L_sym_0604894C:
    .4byte  sym_0604894C
.L_vdp2_cram_00600:
    .4byte  0x25F00600
.L_memcpy_word_idx:
    .4byte  memcpy_word_idx
.L_sym_0605E05C_2:
    .4byte  sym_0605E05C
.L_0601FA6C:
    mov.w   DAT_0601fac4, r7
    add r11, r7
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   .L_const_0x380_w, r6
.L_0601FA76:
    mov.l @r15, r5
    mov.l @r5, r5
    jsr @r12
    mov #0xC, r4
    bra     .L_0601FCD4
    nop
.L_0601FA82:
    mov.w   DAT_0601fac8, r7
    add r11, r7
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   .L_bit_10_w, r6
    mov.l @r15, r5
    mov.l @r5, r5
    jsr @r12
    mov #0xC, r4
    bra     .L_0601FCD4
    nop
.L_0601FA98:
    cmp/eq #0x4, r0
    bt      .L_0601FA1A
    cmp/eq #0x8, r0
    bt      .L_0601FA6C
    cmp/eq #0xC, r0
    bt      .L_0601FA82
    bra     .L_0601FCD4
    nop
.L_0601FAA8:
    mov.l   .L_sym_0605CD9C, r5
    mov.l   .L_vdp2_cram_00600_2, r4
    mov.l   .L_memcpy_word_idx_2, r3
    jsr @r3
    mov #0x20, r6
    mov.w   .L_const_0x0590_w, r8
    mov r8, r9
    add #0x8, r9
    mov.l   .L_sym_060284AE, r13
    mov.w   .L_const_0x090_w, r14
    mov.l   .L_sym_0605E05C_3, r0
    mov.b @r0, r0
    bra     .L_0601FCC4
    extu.b r0, r0

    .global DAT_0601fac4
DAT_0601fac4:
    .2byte  0x02C8
.L_const_0x380_w:
    .2byte  0x0380

    .global DAT_0601fac8
DAT_0601fac8:
    .2byte  0x02D0
.L_bit_10_w:
    .2byte  0x0400
.L_const_0x0590_w:
    .2byte  0x0590
.L_const_0x090_w:
    .2byte  0x0090
.L_sym_0605CD9C:
    .4byte  sym_0605CD9C
.L_vdp2_cram_00600_2:
    .4byte  0x25F00600
.L_memcpy_word_idx_2:
    .4byte  memcpy_word_idx
.L_sym_060284AE:
    .4byte  sym_060284AE
.L_sym_0605E05C_3:
    .4byte  sym_0605E05C
.L_0601FAE4:
    mov.l   .L_sym_0605E0A4, r10
    mov r14, r6
    mov.w   .L_bit_7_w, r5
    mov.l @r10, r7
    jsr @r13
    mov #0xC, r4
    mov r11, r7
    add r9, r7
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   .L_const_0x098_w, r6
    mov.l @r15, r5
    mov.l @r5, r5
    jsr @r12
    mov #0xC, r4
    mov r14, r6
    mov.w   .L_const_0x180_w, r5
    mov.l @(4, r10), r7
    jsr @r13
    mov #0xC, r4
    mov.l @(8, r10), r7
    mov r14, r6
    mov.w   .L_const_0x280_w, r5
    jsr @r13
    mov #0xC, r4
    mov r11, r9
    mov.w   DAT_0601fbae, r6
    add r8, r9
    mov.l @(4, r9), r7
    mov.l @r9, r5
    jsr @r12
    mov #0xC, r4
    mov.l @(12, r10), r7
    mov r14, r6
    mov.w   .L_bit_10_w_2, r5
    jsr @r13
    mov #0xC, r4
    mov r14, r6
    mov.w   .L_mask_0x0500_w, r5
    mov.l @(16, r10), r7
    jsr @r13
    mov #0xC, r4
    mov.l @(4, r9), r7
    mov.w   DAT_0601fbb4, r6
    mov.l @r9, r5
    jsr @r12
    mov #0xC, r4
    mov r14, r6
    mov.w   .L_mask_0x0600_w, r5
    mov.l @(20, r10), r7
    jsr @r13
    mov #0xC, r4
    mov.l @(24, r10), r7
    mov r14, r6
    mov.w   .L_mask_0x0700_w, r5
    jsr @r13
    mov #0xC, r4
    mov.l @(4, r9), r7
    mov.w   .L_const_0x0730_w, r6
    mov.l @r9, r5
    jsr @r12
    mov #0xC, r4
    mov.l @(28, r10), r7
    mov r14, r6
    mov.w   .L_bit_11_w, r5
    jsr @r13
    mov #0xC, r4
    mov r14, r6
    mov.w   .L_mask_0x0900_w, r5
    mov.l @(32, r10), r7
    jsr @r13
    mov #0xC, r4
    mov.l @(36, r10), r7
    mov r14, r6
    mov.w   .L_mask_0x0a00_w, r5
    jsr @r13
    mov #0xC, r4
    mov r14, r6
    mov.w   .L_mask_0x0b00_w, r5
    mov.l @(40, r10), r7
    jsr @r13
    mov #0xC, r4
    mov.l @(4, r9), r7
    mov.w   DAT_0601fbc4, r6
    mov.l @r9, r5
    jsr @r12
    mov #0xC, r4
    mov r14, r6
    mov.w   .L_const_0x0c80_w, r5
    mov.l   .L_sym_0605E0E4, r7
    mov.l @r7, r7
    jsr @r13
    mov #0xC, r4
    mov.l @(4, r9), r7
    mov.w   DAT_0601fbc8, r6
    bra     .L_0601FC34
    mov.l @r9, r5
.L_bit_7_w:
    .2byte  0x0080
.L_const_0x098_w:
    .2byte  0x0098
.L_const_0x180_w:
    .2byte  0x0180
.L_const_0x280_w:
    .2byte  0x0280

    .global DAT_0601fbae
DAT_0601fbae:
    .2byte  0x0296
.L_bit_10_w_2:
    .2byte  0x0400
.L_mask_0x0500_w:
    .2byte  0x0500

    .global DAT_0601fbb4
DAT_0601fbb4:
    .2byte  0x0536
.L_mask_0x0600_w:
    .2byte  0x0600
.L_mask_0x0700_w:
    .2byte  0x0700
.L_const_0x0730_w:
    .2byte  0x0730
.L_bit_11_w:
    .2byte  0x0800
.L_mask_0x0900_w:
    .2byte  0x0900
.L_mask_0x0a00_w:
    .2byte  0x0A00
.L_mask_0x0b00_w:
    .2byte  0x0B00

    .global DAT_0601fbc4
DAT_0601fbc4:
    .2byte  0x0B0E
.L_const_0x0c80_w:
    .2byte  0x0C80

    .global DAT_0601fbc8
DAT_0601fbc8:
    .2byte  0x0CD2
    .2byte  0xFFFF
.L_sym_0605E0A4:
    .4byte  sym_0605E0A4
.L_sym_0605E0E4:
    .4byte  sym_0605E0E4
.L_0601FBD4:
    mov.l   .L_sym_0605E0D0, r7
    mov r14, r6
    mov.w   .L_const_0x380_w_2, r5
    mov.l @r7, r7
    jsr @r13
    mov #0xC, r4
    mov r11, r7
    add r9, r7
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   .L_const_0x398_w, r6
    mov.l @r15, r5
    mov.l @r5, r5
    jsr @r12
    mov #0xC, r4
    mov r14, r6
    mov.w   .L_mask_0x0500_w_2, r5
    mov.l   .L_sym_0605E0D4, r7
    mov.l @r7, r7
    jsr @r13
    mov #0xC, r4
    mov r11, r10
    mov.w   DAT_0601fc94, r6
    add r8, r10
    mov.l @(4, r10), r7
    mov.l @r10, r5
    jsr @r12
    mov #0xC, r4
    mov.l   .L_sym_0605E0D8, r7
    mov r14, r6
    mov.w   .L_const_0x0680_w, r5
    mov.l @r7, r7
    jsr @r13
    mov #0xC, r4
    mov.l @(4, r10), r7
    mov.w   .L_const_0x06b2_w, r6
    mov.l @r10, r5
    jsr @r12
    mov #0xC, r4
    mov r14, r6
    mov.w   .L_const_0x0880_w, r5
    mov.l   .L_sym_0605E0E4_2, r7
    mov.l @r7, r7
    jsr @r13
    mov #0xC, r4
    mov.l @(4, r10), r7
    mov.w   DAT_0601fc9c, r6
    mov.l @r10, r5
.L_0601FC34:
    jsr @r12
    mov #0xC, r4
    bra     .L_0601FCD4
    nop
.L_0601FC3C:
    mov.l   .L_sym_0605E0DC, r7
    mov r14, r6
    mov.w   .L_const_0x0480_w, r5
    mov.l @r7, r7
    jsr @r13
    mov #0xC, r4
    mov r11, r7
    add r9, r7
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   .L_const_0x0498_w, r6
    mov.l @r15, r5
    mov.l @r5, r5
    jsr @r12
    mov #0xC, r4
    mov r14, r6
    mov.w   .L_mask_0x0600_w_2, r5
    mov.l   .L_sym_0605E0E0, r7
    mov.l @r7, r7
    jsr @r13
    mov #0xC, r4
    mov r11, r10
    mov.w   .L_const_0x0620_w, r6
    add r8, r10
    mov.l @(4, r10), r7
    mov.l @r10, r5
    jsr @r12
    mov #0xC, r4
    mov.l   .L_sym_0605E0E4_2, r7
    mov r14, r6
    mov.w   .L_bit_11_w_2, r5
    mov.l @r7, r7
    jsr @r13
    mov #0xC, r4
    mov.l @(4, r10), r7
    mov.w   .L_const_0x0852_w, r6
    mov.l @r10, r5
    jsr @r12
    mov #0xC, r4
    bra     .L_0601FCD4
    nop
.L_const_0x380_w_2:
    .2byte  0x0380
.L_const_0x398_w:
    .2byte  0x0398
.L_mask_0x0500_w_2:
    .2byte  0x0500

    .global DAT_0601fc94
DAT_0601fc94:
    .2byte  0x051E
.L_const_0x0680_w:
    .2byte  0x0680
.L_const_0x06b2_w:
    .2byte  0x06B2
.L_const_0x0880_w:
    .2byte  0x0880

    .global DAT_0601fc9c
DAT_0601fc9c:
    .2byte  0x08D2
.L_const_0x0480_w:
    .2byte  0x0480
.L_const_0x0498_w:
    .2byte  0x0498
.L_mask_0x0600_w_2:
    .2byte  0x0600
.L_const_0x0620_w:
    .2byte  0x0620
.L_bit_11_w_2:
    .2byte  0x0800
.L_const_0x0852_w:
    .2byte  0x0852
    .2byte  0xFFFF
.L_sym_0605E0D0:
    .4byte  sym_0605E0D0
.L_sym_0605E0D4:
    .4byte  sym_0605E0D4
.L_sym_0605E0D8:
    .4byte  sym_0605E0D8
.L_sym_0605E0E4_2:
    .4byte  sym_0605E0E4
.L_sym_0605E0DC:
    .4byte  sym_0605E0DC
.L_sym_0605E0E0:
    .4byte  sym_0605E0E0
.L_0601FCC4:
    cmp/eq #0x4, r0
    bf      .L_0601FCCC
    bra     .L_0601FAE4
    nop
.L_0601FCCC:
    cmp/eq #0x8, r0
    bt      .L_0601FBD4
    cmp/eq #0xC, r0
    bt      .L_0601FC3C
.L_0601FCD4:
    mov.l   .L_channel_nibble_config, r14
    mov.w   .L_bit_8_w, r4
    jsr @r14
    mov #0x0, r5
    mov #0x0, r5
    jsr @r14
    mov #0x4, r4
    mov #0x0, r5
    jsr @r14
    mov #0x8, r4
    mov #0x0, r5
    jsr @r14
    mov #0x10, r4
    mov #0x7, r5
    jsr @r14
    mov #0x20, r4
    mov #0x0, r5
    jsr @r14
    mov #0x1, r4
    mov r15, r6
    mov.l   .L_vdp2_vram_7fffe_2, r4
    mov.l   .L_tilemap_dma_update_2, r3
    add #0x4, r6
    jsr @r3
    mov #0x1, r5
    mov #0x7, r5
    jsr @r14
    mov #0x20, r4
    add #0x8, r15
    lds.l @r15+, pr
    mov.l @r15+, r8
    mov.l @r15+, r9
    mov.l @r15+, r10
    mov.l @r15+, r11
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14

    .global geom_display_ctrl_a
    .type geom_display_ctrl_a, @function
geom_display_ctrl_a:
    sts.l pr, @-r15
    mov.l   .L_sym_0605B6D8_2, r4
    mov.l   .L_sym_06026CE0_2, r3
    mov.l @r4, r0
    or #0x4, r0
    jsr @r3
    mov.l r0, @r4
    mov #0x0, r4
    mov.l   .L_sym_060620D0, r3
    mov.l r4, @r3
    mov.l   .L_sym_0605A000, r3
    mov.l r4, @r3
    mov.l   .L_sym_0605A004, r3
    mov.l r4, @r3
    mov.l   .L_sym_0605A008, r3
    mov.l r4, @r3
    mov.l   .L_sym_06059F44, r3
    lds.l @r15+, pr
    rts
    mov.l r4, @r3
.L_bit_8_w:
    .2byte  0x0100
    .2byte  0xFFFF
.L_channel_nibble_config:
    .4byte  channel_nibble_config
.L_vdp2_vram_7fffe_2:
    .4byte  0x25E7FFFE
.L_tilemap_dma_update_2:
    .4byte  tilemap_dma_update
.L_sym_0605B6D8_2:
    .4byte  sym_0605B6D8
.L_sym_06026CE0_2:
    .4byte  sym_06026CE0
.L_sym_060620D0:
    .4byte  sym_060620D0
.L_sym_0605A000:
    .4byte  sym_0605A000
.L_sym_0605A004:
    .4byte  sym_0605A004
.L_sym_0605A008:
    .4byte  sym_0605A008
.L_sym_06059F44:
    .4byte  sym_06059F44

    .global geom_display_ctrl_b
    .type geom_display_ctrl_b, @function
geom_display_ctrl_b:
    sts.l pr, @-r15
    add #-0x10, r15
    mov r15, r1
    mov.l   .L_sym_0605F498, r2
    mov.l   .L_sym_06035168, r3
    jsr @r3
    mov #0x10, r0
    mov r15, r3
    mov.l   .L_sym_06087804, r2
    mov.w @r2, r2
    extu.w r2, r2
    shll2 r2
    add r3, r2
    mov.l @r2, r2
    jsr @r2
    nop
    add #0x10, r15
    lds.l @r15+, pr
    rts
    nop

    .global vram_alloc_mgr
    .type vram_alloc_mgr, @function
vram_alloc_mgr:
    sts.l pr, @-r15
    mov.l   .L_sym_060877F8, r4
    mov.l   .L_sym_0607EBC4, r3
    mov.l   .L_fp_128, r2
    mov.l @r3, r3
    and r2, r3
    tst r3, r3
    bt      .L_0601FDBC
    mov.l   .L_sym_0607EAD8, r3
    mov.l @r3, r3
    shll2 r3
    mov.l   .L_sym_0605F62C, r2
    add r2, r3
    mov.l @r3, r1
    bra     .L_0601FDC8
    nop
.L_0601FDBC:
    mov.l   .L_sym_0607EAD8, r3
    mov.l @r3, r3
    shll2 r3
    mov.l   .L_sym_0605F5EC, r2
    add r2, r3
    mov.l @r3, r1
.L_0601FDC8:
    mov.l r1, @r4
    mov r1, r2
    mov.l @r2, r3
    mov.l   .L_sym_060877F4, r1
    mov.l r3, @r1
    .byte   0xB0, 0x25    /* bsr 0x0601FE20 (external) */
    nop
    mov.l   .L_sym_0605AD10, r4
    mov.l @r4, r0
    cmp/eq #0x17, r0
    movt r1
    cmp/eq #0x16, r0
    movt r0
    or r1, r0
    tst r0, r0
    bt      .L_0601FDEC
    .byte   0xA1, 0x5C    /* bra 0x060200A4 (external) */
    lds.l @r15+, pr
.L_0601FDEC:
    lds.l @r15+, pr
    rts
    nop
    .2byte  0xFFFF
.L_sym_0605F498:
    .4byte  sym_0605F498
.L_sym_06035168:
    .4byte  sym_06035168
.L_sym_06087804:
    .4byte  sym_06087804
.L_sym_060877F8:
    .4byte  sym_060877F8
.L_sym_0607EBC4:
    .4byte  sym_0607EBC4
.L_fp_128:
    .4byte  0x00800000
.L_sym_0607EAD8:
    .4byte  sym_0607EAD8
.L_sym_0605F62C:
    .4byte  sym_0605F62C
.L_sym_0605F5EC:
    .4byte  sym_0605F5EC
.L_sym_060877F4:
    .4byte  sym_060877F4
.L_sym_0605AD10:
    .4byte  sym_0605AD10
