/* gfx_frame_dispatch -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0601389E - 0x060138BE
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0601389E


    .global gfx_frame_dispatch
    .type gfx_frame_dispatch, @function
gfx_frame_dispatch:
    mov.l r14, @-r15
    sts.l pr, @-r15
    .byte   0xD3, 0x13    /* mov.l .L_pool_060138F0, r3 */
    .byte   0xD2, 0x1C    /* mov.l .L_pool_06013918, r2 */
    mov.b @r3, r3
    extu.b r3, r3
    shll2 r3
    add r2, r3
    mov.l @r3, r3
    jsr @r3
    nop
    .byte   0xDE, 0x19    /* mov.l .L_pool_0601391C, r14 */
    mov #0x0, r2
    mov r14, r7
    mov r14, r6
    mov.l r2, @-r15
