/* hud_rpm_bar_idx_1 -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x06032B72 - 0x06032B80
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_06032B72


    .global hud_rpm_bar_idx_1
    .type hud_rpm_bar_idx_1, @function
hud_rpm_bar_idx_1:
    sts.l pr, @-r15
    jsr @r0
    nop
    lds.l @r15+, pr
    .byte   0xD0, 0x75    /* mov.l .L_pool_06032D50, r0 */
    mov.w @(r0, r14), r4
    .byte   0xD0, 0x6B    /* mov.l .L_pool_06032D2C, r0 */
