/* hud_layer_composite -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x060114B8 - 0x0601155E
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_060114B8


    .global hud_layer_composite
    .type hud_layer_composite, @function
hud_layer_composite:
    sts.l pr, @-r15
    shll2 r0
    mov.l   .L_pool_06011504, r14
    mov.l   .L_pool_060114FC, r3
    mov.l   .L_pool_06011500, r2
    shll2 r0
    mov.l @r2, r2
    add r3, r0
    shll2 r2
    mov.l @(r0, r2), r1
    mov.l @r14, r2
    mov #0x0, r0
    sub r2, r1
    cmp/gt r1, r0
    addc r0, r1
    shar r1
    add r1, r2
    mov.l r2, @r14
    mov.l   .L_pool_06011508, r4
    mov.b @r4, r4
    extu.b r4, r4
    mov r4, r0
    cmp/eq #0x3, r0
    bt      .L_060114EE
    mov r4, r0
    cmp/eq #0xB, r0
    bf      .L_06011510
.L_060114EE:
    mov.l   .L_pool_0601150C, r0
    mov.l @r0, r0
    tst #0x1, r0
    bt      .L_06011510
    bra     .L_06011552
    nop
    .2byte  0xFFFF
.L_pool_060114FC:
    .4byte  sym_060447A8
.L_pool_06011500:
    .4byte  sym_0607EADC
.L_pool_06011504:
    .4byte  sym_06078860
.L_pool_06011508:
    .4byte  sym_0607887F
.L_pool_0601150C:
    .4byte  sym_0607EBC8
.L_06011510:
    extu.w r13, r12
    extu.w r13, r11
    .byte   0xD3, 0x2C    /* mov.l .L_pool_060115C8, r3 */
    shll r12
    shll2 r11
    add r3, r12
    shll2 r11
    mov.w @r12, r2
    mov.l r2, @-r15
    .byte   0xD7, 0x2A    /* mov.l .L_pool_060115CC, r7 */
    .byte   0x96, 0x4F    /* mov.w .L_wpool_060115C6, r6 */
    .byte   0xD2, 0x2A    /* mov.l .L_pool_060115D0, r2 */
    add r2, r11
    add #0xC, r11
    mov.l @r11, r5
    .byte   0xB0, 0xBB    /* bsr 0x060116A8 (external) */
    mov.l @r14, r4
    add #0x4, r15
    mov.w @r12, r7
    mov.l @r11, r6
    .byte   0xD4, 0x26    /* mov.l .L_pool_060115D4, r4 */
    .byte   0xB2, 0x1D    /* bsr 0x06011978 (external) */
    mov.l @r14, r5
    mov.w @r12, r7
    mov.l @r11, r6
    mov.l @r14, r5
    .byte   0xD4, 0x24    /* mov.l .L_pool_060115D8, r4 */
    lds.l @r15+, pr
    mov.l @r15+, r11
    mov.l @r15+, r12
    mov.l @r15+, r13
    .byte   0xA2, 0x13    /* bra 0x06011978 (external) */
    mov.l @r15+, r14
.L_06011552:
    lds.l @r15+, pr
    mov.l @r15+, r11
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14
