/* hud_menu_logic -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x060127E0 - 0x06012AC4
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_060127E0


    .global hud_menu_logic
    .type hud_menu_logic, @function
hud_menu_logic:
    mov.l r14, @-r15
    mov.l r13, @-r15
    mov.l r12, @-r15
    mov.l r11, @-r15
    mov.l r10, @-r15
    mov.l r9, @-r15
    mov.l r8, @-r15
    sts.l pr, @-r15
    add #-0x4, r15
    mov.l   .L_pool_06012894, r4
    mov.l @r4, r3
    mov.l   .L_pool_06012898, r2
    mov.l r3, @r2
    mov.l   .L_pool_0601289C, r5
    mov.l @r5, r0
    or #0x80, r0
    mov.l r0, @r5
    mov.l   .L_pool_060128A0, r3
    mov.l @r4, r2
    add r3, r2
    mov.l r2, @r4
    mov.l   .L_pool_060128A4, r4
    mov.l @r4, r4
    mov.w   DAT_06012884, r0
    mov.l @(r0, r4), r4
    mov.l   .L_pool_060128A8, r8
    mov.l   .L_pool_060128AC, r9
    mov.w   .L_wpool_06012886, r10
    mov.l   .L_pool_060128B0, r11
    mov.l   .L_pool_060128B4, r12
    mov.l   .L_pool_060128B8, r13
    mov.l   .L_pool_060128BC, r14
    bra     .L_06012A52
    mov.l @r14, r0
.L_06012824:
    mov.w   DAT_06012888, r7
    add r13, r7
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   .L_wpool_0601288A, r6
    mov.l @r15, r5
    mov.l @r5, r5
    jsr @r12
    mov #0xC, r4
    mov.w   DAT_0601288c, r7
    add r13, r7
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   DAT_0601288e, r6
    mov.l @r15, r5
    mov.l @r5, r5
    jsr @r12
    mov #0xC, r4
    mov.l @r14, r3
    add #0x1, r3
    mov.l r3, @r14
    bra     .L_06012A7E
    nop
.L_06012852:
    mov r4, r0
    cmp/eq #0x52, r0
    bt      .L_060128E6
    mov.l   .L_pool_060128C0, r3
    mov.w @r3, r2
    extu.w r2, r2
    mov.l   .L_pool_060128C4, r3
    mov.w @r3, r3
    extu.w r3, r3
    and r3, r2
    tst r2, r2
    bf      .L_06012874
    mov.l   .L_pool_060128C8, r0
    mov.w @r0, r0
    extu.w r0, r0
    tst r0, r0
    bt      .L_060128CC
.L_06012874:
    mov r13, r7
    add r10, r7
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   DAT_06012890, r3
    add r3, r7
    bra     .L_060128D8
    nop

    .global DAT_06012884
DAT_06012884:
    .2byte  0x01EC
.L_wpool_06012886:
    .2byte  0x0090

    .global DAT_06012888
DAT_06012888:
    .2byte  0x0098
.L_wpool_0601288A:
    .2byte  0x0880

    .global DAT_0601288c
DAT_0601288c:
    .2byte  0x00A0

    .global DAT_0601288e
DAT_0601288e:
    .2byte  0x088C

    .global DAT_06012890
DAT_06012890:
    .2byte  0x4000
    .2byte  0xFFFF
.L_pool_06012894:
    .4byte  sym_060788F8
.L_pool_06012898:
    .4byte  sym_0605B714
.L_pool_0601289C:
    .4byte  sym_0605B6D8
.L_pool_060128A0:
    .4byte  0x0004CCCC
.L_pool_060128A4:
    .4byte  sym_0607E944
.L_pool_060128A8:
    .4byte  sym_060283E0
.L_pool_060128AC:
    .4byte  sound_cmd_dispatch
.L_pool_060128B0:
    .4byte  sym_0605ACDD
.L_pool_060128B4:
    .4byte  sym_06028400
.L_pool_060128B8:
    .4byte  sym_06063750
.L_pool_060128BC:
    .4byte  sym_060788F4
.L_pool_060128C0:
    .4byte  sym_06063D98
.L_pool_060128C4:
    .4byte  sym_0608188C
.L_pool_060128C8:
    .4byte  sym_0607ED8C
.L_060128CC:
    mov.w   DAT_0601299a, r7
    add r13, r7
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   DAT_0601299c, r3
    add r3, r7
.L_060128D8:
    mov.w   DAT_0601299e, r6
    mov.l @r15, r5
    mov.l @r5, r5
    jsr @r12
    mov #0x8, r4
    bra     .L_06012A7E
    nop
.L_060128E6:
    mov r11, r7
    mov.l @r14, r2
    add #0x1, r2
    mov.l r2, @r14
    mov.l   .L_mask_nibble3, r6
    mov.w   DAT_0601299e, r5
    jsr @r8
    mov #0x8, r4
    mov r11, r7
    mov.l   .L_mask_nibble3, r6
    mov.w   DAT_060129a0, r5
    jsr @r8
    mov #0x8, r4
    mov r11, r7
    mov.l   .L_mask_nibble3, r6
    mov.w   DAT_060129a2, r5
    jsr @r8
    mov #0x8, r4
    mov r13, r7
    add #0x78, r7
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   DAT_060129a4, r3
    mov.w   DAT_060129a6, r6
    mov.l @r15, r5
    add r3, r7
    mov.l @r5, r5
    jsr @r12
    mov #0x8, r4
    mov.l   .L_pool_060129AC, r5
    jsr @r9
    mov #0x0, r4
    bra     .L_06012A7E
    nop
.L_0601292A:
    mov r4, r0
    cmp/eq #0x58, r0
    bt      .L_06012934
    bra     .L_06012A7E
    nop
.L_06012934:
    mov.l @r14, r3
    mov r13, r7
    add #0x1, r3
    add #0x70, r7
    mov.l r3, @r14
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   DAT_060129a4, r3
    mov.w   DAT_060129a6, r6
    mov.l @r15, r5
    add r3, r7
    mov.l @r5, r5
    jsr @r12
    mov #0x8, r4
    mov #0x1, r3
    mov.l   .L_pool_060129B0, r2
    mov.b r3, @r2
    mov.l   .L_pool_060129B4, r3
    mov.l   .L_pool_060129B8, r1
    mov.l @r3, r3
    mov.l @(48, r3), r2
    mov.l r2, @r1
    mov.l   .L_pool_060129BC, r5
    jsr @r9
    mov #0x0, r4
    bra     .L_06012A7E
    nop
.L_0601296A:
    mov r4, r0
    cmp/eq #0x5D, r0
    bt      .L_06012974
    bra     .L_06012A7E
    nop
.L_06012974:
    mov.l @r14, r3
    mov r13, r7
    add #0x1, r3
    add #0x68, r7
    mov.l r3, @r14
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   DAT_060129a4, r3
    mov.w   DAT_060129a6, r6
    mov.l @r15, r5
    add r3, r7
    mov.l @r5, r5
    jsr @r12
    mov #0x8, r4
    mov.l   .L_pool_060129C0, r5
    jsr @r9
    mov #0x0, r4
    bra     .L_06012A7E
    nop

    .global DAT_0601299a
DAT_0601299a:
    .2byte  0x0088

    .global DAT_0601299c
DAT_0601299c:
    .2byte  0x4000

    .global DAT_0601299e
DAT_0601299e:
    .2byte  0x061C

    .global DAT_060129a0
DAT_060129a0:
    .2byte  0x069C

    .global DAT_060129a2
DAT_060129a2:
    .2byte  0x071C

    .global DAT_060129a4
DAT_060129a4:
    .2byte  0x3000

    .global DAT_060129a6
DAT_060129a6:
    .2byte  0x0626
.L_mask_nibble3:
    .4byte  0x0000F000                  /* nibble 3 mask */
.L_pool_060129AC:
    .4byte  0xAE1122FF
.L_pool_060129B0:
    .4byte  sym_06078654
.L_pool_060129B4:
    .4byte  sym_0607E944
.L_pool_060129B8:
    .4byte  sym_06063EF0
.L_pool_060129BC:
    .4byte  0xAE1123FF
.L_pool_060129C0:
    .4byte  0xAE1124FF
.L_060129C4:
    mov r4, r0
    cmp/eq #0x61, r0
    bf      .L_06012A7E
    mov.l @r14, r3
    add #0x1, r3
    mov.l r3, @r14
    mov.w   DAT_06012a92, r7
    add r13, r7
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   DAT_06012a94, r3
    mov.w   .L_wpool_06012A96, r6
    mov.l @r15, r5
    add r3, r7
    mov.l @r5, r5
    jsr @r12
    mov #0x8, r4
    mov.l   .L_pool_06012AA4, r5
    jsr @r9
    mov #0x0, r4
    mov #0x14, r3
    mov.l   .L_pool_06012AA8, r2
    mov.w r3, @r2
    mov #0x1, r3
    mov.l   .L_pool_06012AAC, r2
    mov.b r3, @r2
    bra     .L_06012A7E
    nop
.L_060129FC:
    mov.l   .L_pool_06012AB0, r14
    mov r11, r7
    mov r10, r6
    mov.w   .L_wpool_06012A96, r5
    jsr @r14
    mov #0x8, r4
    mov r11, r7
    mov r10, r6
    mov.w   .L_wpool_06012A98, r5
    jsr @r14
    mov #0x8, r4
    mov r11, r7
    mov r10, r6
    mov.w   .L_wpool_06012A9A, r5
    jsr @r14
    mov #0x8, r4
    mov r11, r7
    mov.l   .L_mask_nibble3_06012AB4, r6
    mov.w   .L_wpool_06012A9C, r5
    jsr @r8
    mov #0x8, r4
    mov r10, r6
    mov.w   .L_wpool_06012A9E, r5
    mov.l   .L_pool_06012AB8, r7
    jsr @r14
    mov #0xC, r4
    mov.l   .L_pool_06012AB8, r7
    mov r10, r6
    mov.w   .L_wpool_06012AA0, r5
    jsr @r14
    mov #0xC, r4
    mov #0x0, r4
    mov.l   .L_pool_06012ABC, r3
    mov.l r4, @r3
    exts.b r4, r4
    mov.l   .L_pool_06012AC0, r3
    mov.b r4, @r3
    bra     .L_06012A7E
    nop
.L_06012A4A:
    mov.l @r14, r2
    add #0x1, r2
    bra     .L_06012A7E
    mov.l r2, @r14
.L_06012A52:
    cmp/eq #0x0, r0
    bf      .L_06012A5A
    bra     .L_06012824
    nop
.L_06012A5A:
    cmp/eq #0x1, r0
    bf      .L_06012A62
    bra     .L_06012852
    nop
.L_06012A62:
    cmp/eq #0x2, r0
    bf      .L_06012A6A
    bra     .L_0601292A
    nop
.L_06012A6A:
    cmp/eq #0x3, r0
    bf      .L_06012A72
    bra     .L_0601296A
    nop
.L_06012A72:
    cmp/eq #0x4, r0
    bt      .L_060129C4
    cmp/eq #0x13, r0
    bt      .L_060129FC
    bra     .L_06012A4A
    nop
.L_06012A7E:
    add #0x4, r15
    lds.l @r15+, pr
    mov.l @r15+, r8
    mov.l @r15+, r9
    mov.l @r15+, r10
    mov.l @r15+, r11
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14

    .global DAT_06012a92
DAT_06012a92:
    .2byte  0x0080

    .global DAT_06012a94
DAT_06012a94:
    .2byte  0x3000
.L_wpool_06012A96:
    .2byte  0x0520
.L_wpool_06012A98:
    .2byte  0x0620
.L_wpool_06012A9A:
    .2byte  0x0720
.L_wpool_06012A9C:
    .2byte  0x0820
.L_wpool_06012A9E:
    .2byte  0x0880
.L_wpool_06012AA0:
    .2byte  0x0980
    .2byte  0xFFFF
.L_pool_06012AA4:
    .4byte  0xAE1125FF
.L_pool_06012AA8:
    .4byte  sym_06086056
.L_pool_06012AAC:
    .4byte  sym_0608605A
.L_pool_06012AB0:
    .4byte  sym_060284AE
.L_mask_nibble3_06012AB4:
    .4byte  0x0000F000                  /* nibble 3 mask */
.L_pool_06012AB8:
    .4byte  sym_0605AC9C
.L_pool_06012ABC:
    .4byte  sym_0605B714
.L_pool_06012AC0:
    .4byte  sym_06078636
