/* input_event_handler -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x06005A22 - 0x06005AE8
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_06005A22
    .space 2    /* align to match original address 0x06005A22 (mod 4 = 2) */


    .global input_event_handler
    .type input_event_handler, @function
input_event_handler:
    mov.l r14, @-r15
    sts.l pr, @-r15
    add #-0x4, r15
    mov.l   .L_sym_0607EABC, r4
    mov.l @r4, r3
    cmp/pl r3
    bf      .L_06005AE0
    mov.l @r4, r3
    add #-0x1, r3
    mov r3, r0
    tst #0x1, r0
    bt/s    .L_06005A9C
    mov.l r3, @r4
    mov.l   .L_sym_06085FF4, r0
    mov.b @r0, r0
    tst r0, r0
    bt      .L_06005A4A
    mov.w   .L_const_0x0b0_w, r14
    bra     .L_06005A4C
    nop
.L_06005A4A:
    mov #0x21, r14
.L_06005A4C:
    mov.l   .L_sym_0607EAC0, r0
    mov.l @r0, r0
    tst r0, r0
    bt      .L_06005A78
    mov r14, r7
    shll2 r7
    shll r7
    mov.l   .L_sym_06063750, r3
    add r3, r7
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   DAT_06005abc, r3
    add r3, r7
    mov.w   DAT_06005abe, r6
    mov.l @r15, r5
    mov.l @r5, r5
    mov #0x8, r4
    add #0x4, r15
    lds.l @r15+, pr
    mov.l   .L_sym_06028400, r3
    jmp @r3
    mov.l @r15+, r14
.L_06005A78:
    mov r14, r7
    shll2 r7
    shll r7
    mov.l   .L_sym_06063750, r3
    add r3, r7
    mov.l r7, @r15
    mov.l @(4, r7), r7
    mov.w   DAT_06005abc, r3
    add r3, r7
    mov.w   DAT_06005ac0, r6
    mov.l @r15, r5
    mov.l @r5, r5
    mov #0x8, r4
    add #0x4, r15
    lds.l @r15+, pr
    mov.l   .L_sym_06028400, r3
    jmp @r3
    mov.l @r15+, r14
.L_06005A9C:
    mov.l   .L_sym_0605ACDD, r7
    mov.w   .L_const_0x090_w, r6
    mov.w   DAT_06005abe, r5
    mov.l   .L_sym_060284AE, r3
    jsr @r3
    mov #0x8, r4
    mov.l   .L_sym_0605ACDD, r7
    mov.w   .L_const_0x090_w, r6
    mov.w   DAT_06005ac0, r5
    mov #0x8, r4
    add #0x4, r15
    lds.l @r15+, pr
    mov.l   .L_sym_060284AE, r3
    jmp @r3
    mov.l @r15+, r14
.L_const_0x0b0_w:
    .2byte  0x00B0

    .global DAT_06005abc
DAT_06005abc:
    .2byte  0x5000

    .global DAT_06005abe
DAT_06005abe:
    .2byte  0x049C

    .global DAT_06005ac0
DAT_06005ac0:
    .2byte  0x059C
.L_const_0x090_w:
    .2byte  0x0090
.L_sym_0607EABC:
    .4byte  sym_0607EABC
.L_sym_06085FF4:
    .4byte  sym_06085FF4
.L_sym_0607EAC0:
    .4byte  sym_0607EAC0
.L_sym_06063750:
    .4byte  sym_06063750
.L_sym_06028400:
    .4byte  sym_06028400
.L_sym_0605ACDD:
    .4byte  sym_0605ACDD
.L_sym_060284AE:
    .4byte  sym_060284AE
.L_06005AE0:
    add #0x4, r15
    lds.l @r15+, pr
    rts
    mov.l @r15+, r14
