/* lap_time_record -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0600D92C - 0x0600D9BC
 * Auto-generated by tools/generate_l3_tu.py
 *
 * Lap time recording — called when a lap is completed. Records the
 * elapsed time for this lap and updates the best lap time.
 *
 * Car struct offsets:
 *   [+0x21C] = current lap counter
 *   [+0x220] = lap delta time (this lap's duration)
 *   [+0x22C] = lap start timestamp (updated to current timer each lap)
 *   [+0x230] = completed laps counter
 *   [+0x240] = best lap time (0 = no best yet)
 *
 * Logic:
 *   1. If lap_counter > max_laps - 1:
 *      → set race_complete_flag = 3, increment completed_laps
 *   2. Set countdown_timer = 40 frames (0x28)
 *   3. Call lap timing function (external BSR)
 *   4. Compute lap_time = global_timer - lap_start_timestamp
 *   5. Update lap_start_timestamp to current timer
 *   6. Store lap_time in per-lap array: lap_times[(lap-1)*4]
 *   7. If lap_time < best_lap OR best_lap == 0:
 *      → update best_lap to this lap_time
 */

    .section .text.FUN_0600D92C


    .global lap_time_record
    .type lap_time_record, @function
lap_time_record:
    mov.l r14, @-r15
    sts.l pr, @-r15
    mov.l   .L_car_struct_ptr, r14
    mov.l   .L_max_laps, r3
    mov.w   DAT_0600d996, r0          /* r0 = +0x21C (lap counter offset) */
    mov.l @r14, r14                    /* r14 = car struct */
    mov.l @r3, r3                      /* r3 = max laps */
    mov.l @(r0, r14), r2              /* r2 = current lap count */
    add #-0x1, r3                      /* r3 = max_laps - 1 */
    cmp/hi r3, r2                      /* lap_count > max_laps - 1? */
    bf      .L_0600D950               /* no → skip race complete */
    mov #0x3, r2                       /* race complete: set flag = 3 */
    mov.l   .L_race_complete_flag, r3
    mov.l r2, @r3
    mov.w   DAT_0600d998, r0          /* +0x230 = completed laps */
    mov.l @(r0, r14), r2
    add #0x1, r2                       /* increment completed laps */
    mov.l r2, @(r0, r14)
.L_0600D950:
    mov #0x28, r3                      /* set countdown timer = 40 frames */
    mov.l   .L_countdown_timer, r2
    mov.l r3, @r2
    .byte   0xB1, 0xB7    /* bsr 0x0600DCC8 (external) — lap timing function */
    nop
    mov.l   .L_global_timer, r5       /* compute lap time */
    mov.w   DAT_0600d99a, r0          /* +0x22C = lap start timestamp */
    mov.l @r5, r4                      /* r4 = current global timer */
    mov.l @r5, r3
    mov.l @(r0, r14), r2              /* r2 = lap start time */
    mov.l r3, @(r0, r14)              /* update start time to current */
    sub r2, r4                         /* r4 = lap_time (delta) */
    mov.l @(r0, r14), r3
    mov.l   .L_prev_lap_store, r2
    add #-0xC, r0                      /* r0 = +0x220 (lap delta storage) */
    mov.l r3, @r2                      /* store current timer externally */
    mov.l r4, @(r0, r14)              /* car[+0x220] = lap_time */
    add #-0x4, r0                      /* r0 = +0x21C (lap counter) */
    mov.l   .L_lap_times_array, r2
    mov.l @(r0, r14), r3              /* r3 = lap counter */
    add #0x24, r0                      /* r0 = +0x240 (best lap) */
    add #-0x1, r3                      /* index = lap - 1 */
    shll2 r3                           /* index * 4 (32-bit entries) */
    add r2, r3                         /* r3 → lap_times[lap-1] */
    mov.l r4, @r3                      /* store this lap's time */
    mov.l @(r0, r14), r5              /* r5 = current best lap time */
    cmp/ge r5, r4                      /* new_time >= best? */
    bf      .L_0600D98C               /* new_time < best → update best */
    tst r5, r5                         /* best == 0? (no best yet) */
    bf      .L_0600D990               /* best != 0 → keep current best */
.L_0600D98C:
    mov.w   .L_off_best_lap, r0       /* +0x240 = best lap time */
    mov.l r4, @(r0, r14)              /* update best lap = this lap's time */
.L_0600D990:
    lds.l @r15+, pr
    rts
    mov.l @r15+, r14

    .global DAT_0600d996
DAT_0600d996:
    .2byte  0x021C                        /* car offset: current lap counter */

    .global DAT_0600d998
DAT_0600d998:
    .2byte  0x0230                        /* car offset: completed laps counter */

    .global DAT_0600d99a
DAT_0600d99a:
    .2byte  0x022C                        /* car offset: lap start timestamp */
.L_off_best_lap:
    .2byte  0x0240                        /* car offset: best lap time */
    .2byte  0xFFFF
.L_car_struct_ptr:
    .4byte  sym_0607E940               /* pointer to current car struct */
.L_max_laps:
    .4byte  sym_06063F28               /* maximum lap count for current race */
.L_race_complete_flag:
    .4byte  sym_0607EBF4               /* race complete flag (3 = finished) */
.L_countdown_timer:
    .4byte  sym_0607EAC0               /* countdown timer (set to 40 on lap complete) */
.L_global_timer:
    .4byte  sym_060786B0               /* global race timer */
.L_prev_lap_store:
    .4byte  sym_060786A4               /* external lap time storage */
.L_lap_times_array:
    .4byte  sym_0607EBF8               /* per-lap time array (4 bytes per lap) */
