/* main_scene_render -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0602E892 - 0x0602EDA2
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0602E892


    .global main_scene_render
    .type main_scene_render, @function
main_scene_render:
    sts.l pr, @-r15                 ! save return address
    jsr @r13                        ! call function pointer in r13
    nop                             ! delay slot
    lds.l @r15+, pr                 ! restore return address
    .byte   0xAF, 0x77    /* bra 0x0602E78C (external) */
    nop                             ! delay slot
    .2byte  0x0000
    .4byte  0x00000000
    .4byte  0xAE1109FF
    .4byte  sound_cmd_dispatch

    .global sym_0602E8AC
sym_0602E8AC:
    .4byte  loc_06060BD4
    .4byte  loc_06060C44
    .4byte  loc_06060CB4

    .global sym_0602E8B8
sym_0602E8B8:
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    mov #0x66, r6                   ! data (not code) — decoded as instruction
    .word 0x0000 /* UNKNOWN */
    .word 0xCCCC /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .byte   0xB3, 0x33    /* bsr 0x0602EF48 (external) — data, not a real branch */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */

    .global sym_0602E938
sym_0602E938:
    bt/s    .L_scene_data_block_a   ! data (not code) — VDP2 rotation params
    mov.w @r15+, r8                 ! data (not code)
    mov.l @(0, r0), r0              ! data (not code)
    mov.l @(40, r7), r2             ! data (not code)
    bt/s    .L_scene_data_block_b   ! data (not code)
    mov.w @r15+, r8                 ! data (not code)
    mov.l @(0, r0), r0              ! data (not code)
    mov.l @(40, r7), r2             ! data (not code)
    .word 0xFD4F /* UNKNOWN */
    tst #0xF5, r0                   ! data (not code)
    mov.w r0, @(22, r14)            ! data (not code)
    mov.w @(0, r0), r0              ! data (not code)
    .word 0xFD4F /* UNKNOWN */
    tst #0xF5, r0                   ! data (not code)
    mov.w r0, @(22, r14)            ! data (not code)
    mov.w @(0, r0), r0              ! data (not code)
    mov #0x4F, r13                  ! data (not code)
    .byte   0xD8, 0xF5    /* mov.l .L_pool_render_body, r8 — data, not code */
    mov.w   .L_wpool_vdp2_rot_params, r0   ! data (not code)
    add #0x7A, r1                   ! data (not code)
.L_wpool_vdp2_rot_params:          /* [MEDIUM] VDP2 rotation parameter table entry */
    .2byte  0xED4F
    .2byte  0xD8F5
    .4byte  0x9000717A
    .4byte  0xCD4F98F5
    .4byte  0x81EB847A
    .4byte  0xCD4F98F5
    .4byte  0x81EB847A
    .4byte  0x8D4F68F5
    .4byte  0x51EB547A
    .4byte  0x8D4F68F5
    .4byte  0x51EB547A
    .4byte  0xCD4FC8F5
    .4byte  0xA1EB847A
    .4byte  0xCD4FC8F5
    .4byte  0xA1EB847A
    .4byte  0x8D4F68F5
    .4byte  0x5000517A
    .4byte  0x8D4F68F5
    .4byte  0x5000517A

    .global loc_0602E9A8
loc_0602E9A8:                       ! scene config data — course 0
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    sett                             ! data (not code) — 0x0018
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    mul.l r1, r0                     ! data (not code) — 0x0107
    .word 0x0000 /* UNKNOWN */
    .word 0x0060 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    mov.b r0, @(0, r0)              ! data (not code) — 0x8000
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
.L_scene_data_block_a:
    .byte   0xD0, 0x00    /* mov.l .L_pool_scene_data_term_a, r0 */
.L_pool_scene_data_term_a:
    .4byte  0x00003C00
    .2byte  0x0004
.L_scene_data_block_b:
    mov.b r0, @(0, r0)              ! data (not code) — 0x8000
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    mov.l r1, @(r0, r0)             ! data (not code)
    .word 0x0000 /* UNKNOWN */
    sett                             ! data (not code) — 0x0018
    .word 0x0001 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    mov #0x0, r0                     ! data (not code) — 0xE000
    .word 0x0000 /* UNKNOWN */
    mov.b @r0, r0                    ! data (not code) — 0xC000
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    mul.l r1, r0                     ! data (not code) — 0x0107
    .word 0x0000 /* UNKNOWN */
    mov.b @(r0, r0), r0              ! data (not code) — 0x00CC
    .word 0x0000 /* UNKNOWN */
    mov.b r0, @(0, r0)              ! data (not code) — 0x8000
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    mov #0x0, r8                     ! data (not code) — 0xE800
    .word 0x0000 /* UNKNOWN */
    add #0x0, r0                     ! data (not code) — 0x7000
    mov.w r0, @(r0, r0)             ! data (not code)
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    mac.l @r1+, @r0+                ! data (not code) — 0x000F
    .word 0x0000 /* UNKNOWN */
    sett                             ! data (not code) — 0x0018
    .word 0x0000 /* UNKNOWN */
    mov.b r0, @r8                    ! data (not code) — 0x2080
    .word 0x0000 /* UNKNOWN */
    mov.w   .L_wpool_scene0_viewport_data, r8   ! data (not code) -- 0x9800
    .word 0x0000 /* UNKNOWN */
.L_wpool_scene0_viewport_data:     /* [MEDIUM] scene config course 0 viewport parameters */
    .2byte  0xD200
    .4byte  0x00006800
    .4byte  0x0001E800
    .4byte  0x00000000
    .4byte  0x00000017
    .4byte  0x00000010
    .4byte  0xFFFF0000
    .4byte  0x00000000
    .4byte  0x0000D000
    .4byte  0x0000B000
    .4byte  0x00021800
    .4byte  0x00000000
    .4byte  0x0000001F
    .4byte  0x00000010
    .4byte  0x00000000
    .4byte  0x00000000
    .4byte  0x0000F300
    .4byte  0x0000C000
    .4byte  0x00058000
    .4byte  0x00000000
    .4byte  0xFFFFFFFF

    .global loc_0602EA8C
loc_0602EA8C:                       ! scene config data — course 1 / course 3
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0020 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    mac.l @r0+, @r0+                ! data (not code) — 0x000F
    .word 0x0000 /* UNKNOWN */
    .word 0x0060 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0001 /* UNKNOWN */
    mov.b r0, @(0, r0)              ! data (not code) — 0x8000
    .word 0x0000 /* UNKNOWN */
    .byte   0xD0, 0x00    /* mov.l .L_pool_scene_cfg_1, r0 */
.L_pool_scene_cfg_1:
    .4byte  0x00007C00
    .4byte  0x00048000
    .4byte  0x00000000
    .4byte  0x0000000E
    .4byte  0x00000018
    .4byte  0x00000000
    .4byte  0x00010000
    .4byte  0x0000E000
    .4byte  0x0000A000
    .4byte  0x00000000
    .4byte  0x00000000
    .4byte  0x0000000F
    .4byte  0x0000000C
    .4byte  0x00000000
    .4byte  0x00008000
    .4byte  0x0000E800
    .4byte  0x0000B000
    .4byte  0x00050000
    .4byte  0x00000000
    .4byte  0x0000001F
    .4byte  0x00000018
    .4byte  0xFFFF6800
    .4byte  0x00002800
    .4byte  0x0000D200
    .4byte  0x0000A800
    .4byte  0x0001E800
    .4byte  0x00000000
    .4byte  0x0000000F
    .4byte  0x00000010
    .4byte  0x00000000
    .4byte  0xFFFF0000
    .4byte  0x0000D000
    .4byte  0x0000F000
    .4byte  0x00021800
    .4byte  0x00000000
    .4byte  0x0000001F
    .4byte  0x00000010
    .4byte  0x00000000
    .4byte  0x00000000
    .4byte  0x0000F300
    .4byte  0x00010000
    .4byte  0x00058000
    .4byte  0x00000000
    .4byte  0xFFFFFFFF

    .global loc_0602EB70
loc_0602EB70:                       ! scene config data — course 2
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    sett                             ! data (not code) — 0x0018
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    mul.l r1, r0                     ! data (not code) — 0x0107
    .word 0x0000 /* UNKNOWN */
    .word 0x0060 /* UNKNOWN */
    .word 0xFFFE /* UNKNOWN */
    mov.b r0, @(0, r0)              ! data (not code) — 0x8000
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .byte   0xD0, 0x00    /* mov.l .L_pool_scene_cfg_2, r0 */
.L_pool_scene_cfg_2:
    .4byte  0x0000AF33
    .4byte  0x00048000
    .4byte  0x00000000
    .4byte  0x00000016
    .4byte  0x00000018
    .4byte  0xFFFF0000
    .4byte  0x00000000
    .4byte  0x0000E000
    .4byte  0x0000D333
    .4byte  0x00000000
    .4byte  0x00000000
    .4byte  0x00000017
    .4byte  0x0000000C
    .4byte  0xFFFF8000
    .4byte  0x00000000
    .4byte  0x0000E800
    .4byte  0x0000E333
    .4byte  0x00050000
    .4byte  0x00000000
    .4byte  0x0000001F
    .4byte  0x00000018
    .4byte  0xFFFFD800
    .4byte  0xFFFF3800
    .4byte  0x0000D200
    .4byte  0x0000DB33
    .4byte  0x0001F800
    .4byte  0x00000000
    .4byte  0x00000017
    .4byte  0x00000010
    .4byte  0x00010000
    .4byte  0x00000000
    .4byte  0x0000D000
    .4byte  0x00012333
    .4byte  0x00023800
    .4byte  0x00000000
    .4byte  0x0000001F
    .4byte  0x00000010
    .4byte  0x00000000
    .4byte  0x00000000
    .4byte  0x0000F300
    .4byte  0x00013333
    .4byte  0x00058000
    .4byte  0x00000000
    .4byte  0xFFFFFFFF

    .global sym_0602EC54
sym_0602EC54:
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0020 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0050 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0080 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x00B0 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x00D0 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x00D0 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x00D0 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x00D0 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x00D0 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x00D0 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    .word 0x0080 /* UNKNOWN */
    .4byte  0x00000040
    .4byte  0x00000000
    .4byte  0xFFFFC000
    .4byte  0x00000000
    .4byte  0x00004000
    .4byte  0x00000000

    .global sym_0602ECAC
sym_0602ECAC:                       ! scene boundary params
    .word 0xFFFF /* UNKNOWN */
    .word 0xF800 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */
    cmp/eq r0, r8                    ! data (not code) — 0x3008
    .word 0x0000 /* UNKNOWN */
    add #0x0, r8                     ! data (not code) — 0x7800
    .word 0x0000 /* UNKNOWN */
    .word 0x0000 /* UNKNOWN */

    .global sym_0602ECBC
sym_0602ECBC:
    .4byte  loc_0602E9A8
    .4byte  loc_0602EA8C
    .4byte  loc_0602EB70
    .4byte  loc_0602EA8C

    .global sym_0602ECCC
sym_0602ECCC:                       ! interrupt mask helper
    mov.l r3, @-r15                 ! save r3
    mov #-0x10, r3                  ! r3 = 0xFFFFFFF0 (mask value)
    stc.l sr, @-r15                 ! save status register
    extu.b r3, r3                   ! r3 = 0xF0 (zero-extend low byte)
    .4byte  0x430ED305
    .4byte  0x23020009
    .4byte  0x13110009
    .4byte  0x50350009
    .4byte  0x4F0763F6
    .4byte  0x000B6103
    .4byte  0xFFFFFF00
    .2byte  0xFF00

    .global sym_0602ECF2
sym_0602ECF2:                       ! render state dispatch
    .byte   0xD1, 0x04    /* mov.l .L_pool_render_state_ptr, r1 */
    mov.l @r1, r2                   ! r2 = current render state index
    .byte   0xD3, 0x04    /* mov.l .L_pool_render_jump_tbl, r3 */
    shll2 r2                        ! r2 *= 4 (index to offset)
    add r2, r3                      ! r3 = &jump_table[state]
    mov.l @r3, r3                   ! r3 = jump target address
    jmp @r3                         ! dispatch to render state handler
    nop                             ! delay slot
    .2byte  0x0000
.L_pool_render_state_ptr:
    .4byte  sym_0607EAE4
.L_pool_render_jump_tbl:
    .4byte  sym_0602ED0C

    .global sym_0602ED0C
sym_0602ED0C:
    .4byte  loc_0602ED18
    .4byte  loc_0602ED18
    .4byte  loc_0602EEAC

    .global loc_0602ED18
loc_0602ED18:                       ! render body — state 0/1 handler
    .byte   0xD0, 0x2A    /* mov.l .L_pool_sound_cooldown_ptr, r0 — [HIGH] sym_0602FDA1 SINIT sound cooldown counter */
    mov #0x50, r1                   ! r1 = 0x50 (cooldown init value)
    mov.b r1, @r0                   ! write cooldown counter = 0x50
    .byte   0xD0, 0x2A    /* mov.l .L_pool_car_ptr_global, r0 — [HIGH] sym_0607E944 current car pointer */
    mov.l @r0, r0                   ! r0 = current car struct pointer
    .byte   0xD1, 0x2A    /* mov.l .L_pool_physics_step_counter, r1 — [HIGH] sym_0607EAE4 physics step counter */
    mov.l @r1, r2                   ! r2 = physics step counter
    add #0x1, r2                    ! increment step counter
    mov.l r2, @r1                   ! store updated step counter
    mov.l @(8, r0), r2              ! r2 = car field at offset 0x8
    shll16 r2                       ! r2 <<= 16 (extract high portion)
    .byte   0x92, 0x3F    /* mov.w .L_wpool_render_dim_const, r2 — [LOW] loads 0x005C render dimension constant */
.L_pool_render_body:
    .4byte  0xE3000236
    .4byte  0x913DE301
    .4byte  0x923C4328
    .4byte  0x01360236
    .4byte  0x9139E301
    .4byte  0x310C2132
    .4byte  0x11311132
    .4byte  0x11339133
    .4byte  0xD31F310C
    .4byte  0x21329230
    .4byte  0xD11E022D
    .4byte  0x932E4200
    .4byte  0x312C330C
    .4byte  0x64142340
    .4byte  0x64107301
    .4byte  0x2340D11A
    .4byte  0x93254200
    .4byte  0x312C6112
    .4byte  0x03169121
    .4byte  0x041D2448
    .4byte  0xD1168900
    .4byte  0xD116931C
    .4byte  0x312C330C
    .4byte  0x62152321
    .4byte  0x62117302
    .4byte  0x23212F86
    .4byte  0x2F962FA6
    .4byte  0x2FB62FC6
    .2byte  0x2FD6
