/* menu_credits_elem -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0603B680 - 0x0603B6A8
 * Auto-generated by tools/generate_l3_tu.py
 *
 * Copies 12 bytes from the element pointer (r4) into the global
 * UI/command state struct at offset +0xB8 (credits element slot).
 * Uses memcpy_long for the transfer.
 */

    .section .text.FUN_0603B680


    .global menu_credits_elem
    .type menu_credits_elem, @function
menu_credits_elem:
    sts.l pr, @-r15                     ! save return address
    mov r4, r1                          ! r1 = src (element data from caller)
    mov.l   .L_ptr_cmd_state, r2        ! r2 = &global command state pointer
    mov.w   .L_const_credits_offset, r3 ! r3 = 0x00B8 (credits element offset)
    mov.l @r2, r2                       ! r2 = state struct base
    add r3, r2                          ! r2 = dst (state_base + 0xB8)
    mov.l   .L_fn_memcpy_long, r3       ! r3 = memcpy_long
    jsr @r3                             ! memcpy_long(r0=12, r1=src, r2=dst)
    mov #0xC, r0                        ! delay slot: r0 = 0xC (12 bytes)
    lds.l @r15+, pr                     ! restore return address
    rts                                 ! return
    nop
    .2byte  0x00A8                      ! shared pool: timer element offset (used by menu_timer_clock)
.L_const_credits_offset:
    .2byte  0x00B8                      /* [HIGH] offset into state struct for credits element slot */
    .4byte  timer_stub                  /* [HIGH] shared pool: timer_stub address (used by menu_timer_clock) */
.L_ptr_cmd_state:
    .4byte  sym_060A4D14               /* [HIGH] global UI/command state pointer — dereferenced to get struct base */
.L_fn_memcpy_long:
    .4byte  sym_06035168               /* [HIGH] memcpy_long — unrolled longword copy (r0=nbytes, r1=dst, r2=src) */
