/* menu_stub_nop -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0603B3CA - 0x0603B3D0
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0603B3CA


    .global menu_stub_nop
    .type menu_stub_nop, @function
menu_stub_nop:
    mov.l r14, @-r15
    mov.l r13, @-r15
    mov r4, r14
