/* nop_stub_menu -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0603B630 - 0x0603B634
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0603B630


    .global nop_stub_menu
    .type nop_stub_menu, @function
nop_stub_menu:
    mov.l r14, @-r15
    mov #0x1D, r1
