/* preview_camera_pos -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0601A770 - 0x0601A7AC
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0601A770


    .global preview_camera_pos
    .type preview_camera_pos, @function
preview_camera_pos:
    sts.l pr, @-r15
    .byte   0xD0, 0x1C    /* mov.l .L_pool_0601A7E4, r0 */
    mov.b @r0, r0
    extu.b r0, r0
    tst r0, r0
    bt      .L_0601A78E
    .byte   0xD3, 0x1A    /* mov.l .L_pool_0601A7E8, r3 */
    jsr @r3
    nop
    .byte   0xD3, 0x1A    /* mov.l .L_pool_0601A7EC, r3 */
    jsr @r3
    nop
    mov #0x0, r2
    .byte   0xD3, 0x16    /* mov.l .L_pool_0601A7E4, r3 */
    mov.b r2, @r3
.L_0601A78E:
    .byte   0xD2, 0x18    /* mov.l .L_pool_0601A7F0, r2 */
    mov.b @r2, r2
    tst r2, r2
    bt      .L_0601A7A2
    .byte   0xD3, 0x17    /* mov.l .L_pool_0601A7F4, r3 */
    jsr @r3
    nop
    mov #0x0, r2
    .byte   0xD3, 0x14    /* mov.l .L_pool_0601A7F0, r3 */
    mov.b r2, @r3
.L_0601A7A2:
    .byte   0xD5, 0x15    /* mov.l .L_pool_0601A7F8, r5 */
    mov #0x0, r4
    .byte   0xD3, 0x15    /* mov.l .L_pool_0601A7FC, r3 */
    jmp @r3
    lds.l @r15+, pr
