/* projection_mgr -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x06023290 - 0x06023574
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_06023290


    .global projection_mgr
    .type projection_mgr, @function
projection_mgr:
    mov.l r14, @-r15
    mov.l r13, @-r15
    mov.l r12, @-r15
    mov.l r11, @-r15
    mov.l r10, @-r15
    mov.l r9, @-r15
    mov.l r8, @-r15
    sts.l pr, @-r15
    mov.l   .L_pool_060233C8, r9
    mov.l   .L_pool_060233CC, r13
    mov.l   .L_pool_060233D0, r4
    mov #0x3, r0
    mov.w r0, @(4, r4)
    mov #0x4, r0
    mov.w r0, @(6, r4)
    mov #0x5, r0
    mov.w r0, @(8, r4)
    mov #0x6, r0
    mov.w r0, @(10, r4)
    mov #0x7, r0
    mov.w r0, @(12, r4)
    mov #0x8, r0
    mov.w r0, @(14, r4)
    mov #0x9, r0
    mov.w r0, @(16, r4)
    mov #0xA, r0
    mov.w r0, @(18, r4)
    mov #0xB, r0
    mov.w r0, @(20, r4)
    mov #0xC, r0
    mov.w r0, @(22, r4)
    mov #0xD, r0
    mov.w r0, @(24, r4)
    mov #0xE, r0
    mov.w r0, @(26, r4)
    mov #0xF, r0
    mov.w r0, @(28, r4)
    mov #0x10, r0
    mov.w r0, @(30, r4)
    mov r4, r3
    add #0x20, r3
    mov #0x11, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x22, r3
    mov #0x12, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x24, r3
    mov #0x13, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x26, r3
    mov #0x14, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x28, r3
    mov #0x15, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x2A, r3
    mov #0x16, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x2C, r3
    mov #0x17, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x2E, r3
    mov #0x18, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x30, r3
    mov #0x19, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x32, r3
    mov #0x1A, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x34, r3
    mov #0x1B, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x36, r3
    mov #0x1C, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x38, r3
    mov #0x1D, r2
    mov.w r2, @r3
    mov #0x1E, r5
    mov r4, r3
    add #0x3A, r3
    extu.w r5, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x3C, r3
    mov #0x1F, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x3E, r3
    mov #0x20, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x40, r3
    mov #0x21, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x42, r3
    mov #0x22, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x44, r3
    mov #0x23, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x46, r3
    mov #0x24, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x48, r3
    mov #0x25, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x4A, r3
    mov #0x26, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x4C, r3
    mov #0x27, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x4E, r3
    mov #0x28, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x50, r3
    mov #0x29, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x52, r3
    mov #0x2A, r2
    mov.w r2, @r3
    mov r4, r3
    add #0x54, r3
    mov #0x36, r2
    mov.w r2, @r3
    add #0x56, r4
    mov #0x37, r3
    mov.w r3, @r4
    extu.w r5, r11
    mov.w   .L_wpool_060233C6, r6
    bra     .L_060233D4
    nop
.L_wpool_060233C6:
    .2byte  0x4240
.L_pool_060233C8:
    .4byte  sym_06056940
.L_pool_060233CC:
    .4byte  sym_0606A4EC
.L_pool_060233D0:
    .4byte  sym_06089E44
.L_060233D4:
    mov.l   .L_pool_0602348C, r5
    mov.l   .L_pool_06023490, r4
    mov.l   .L_pool_06023494, r3
    mov.w   .L_wpool_06023484, r2
    mov.l @r4, r4
    mov.l @r3, r3
    shll2 r4
    shll r4
    add r3, r4
    add r2, r4
    mov.l   .L_pool_06023498, r2
    jsr @r2
    nop
    bra     .L_06023540
    mov #0x0, r12
.L_060233F2:
    extu.b r12, r4
    mov #0x13, r2
    mov r4, r3
    shll2 r4
    shll2 r3
    shll r3
    add r3, r4
    extu.b r4, r4
    extu.w r12, r3
    add r9, r4
    mov.l @r4, r10
    mov.w @(8, r4), r0
    cmp/gt r2, r3
    bf/s    .L_06023412
    mov r0, r8
    add #0x36, r11
.L_06023412:
    extu.w r8, r2
    cmp/pl r2
    bf/s    .L_060234D8
    mov #0x0, r14
.L_0602341A:
    extu.w r12, r0
    cmp/eq #0x13, r0
    bf      .L_060234C2
    extu.w r14, r0
    cmp/eq #0x15, r0
    bf      .L_06023430
    mov.l @r13, r2
    mov.l   .L_pool_0602349C, r3
    mov.l r2, @r3
    bra     .L_060234C2
    nop
.L_06023430:
    extu.w r14, r0
    cmp/eq #0x27, r0
    bf      .L_06023440
    mov.l @r13, r2
    mov.l   .L_pool_060234A0, r3
    mov.l r2, @r3
    bra     .L_060234C2
    nop
.L_06023440:
    extu.w r14, r0
    cmp/eq #0x40, r0
    bf      .L_06023450
    mov.l @r13, r2
    mov.l   .L_pool_060234A4, r3
    mov.l r2, @r3
    bra     .L_060234C2
    nop
.L_06023450:
    extu.w r14, r0
    cmp/eq #0x44, r0
    bf      .L_06023460
    mov.l @r13, r2
    mov.l   .L_pool_060234A8, r3
    mov.l r2, @r3
    bra     .L_060234C2
    nop
.L_06023460:
    extu.w r14, r2
    mov.w   .L_wpool_06023486, r3
    cmp/eq r3, r2
    bf      .L_06023472
    mov.l @r13, r3
    mov.l   .L_pool_060234AC, r2
    mov.l r3, @r2
    bra     .L_060234C2
    nop
.L_06023472:
    extu.w r14, r2
    mov.w   .L_wpool_06023488, r3
    cmp/eq r3, r2
    bf      .L_060234B4
    mov.l @r13, r3
    mov.l   .L_pool_060234B0, r2
    mov.l r3, @r2
    bra     .L_060234C2
    nop
.L_wpool_06023484:
    .2byte  0x03C0
.L_wpool_06023486:
    .2byte  0x0082
.L_wpool_06023488:
    .2byte  0x0088
    .2byte  0xFFFF
.L_pool_0602348C:
    .4byte  0x002A8000
.L_pool_06023490:
    .4byte  sym_06059FFC
.L_pool_06023494:
    .4byte  sym_06063F5C
.L_pool_06023498:
    .4byte  memcpy_word_idx
.L_pool_0602349C:
    .4byte  sym_06089E30
.L_pool_060234A0:
    .4byte  sym_06089E2C
.L_pool_060234A4:
    .4byte  sym_06089E34
.L_pool_060234A8:
    .4byte  sym_06089E38
.L_pool_060234AC:
    .4byte  sym_06089E28
.L_pool_060234B0:
    .4byte  sym_06089E3C
.L_060234B4:
    extu.w r14, r2
    mov.w   .L_wpool_0602355E, r3
    cmp/eq r3, r2
    bf      .L_060234C2
    mov.l @r13, r3
    mov.l   .L_pool_06023560, r2
    mov.l r3, @r2
.L_060234C2:
    extu.w r11, r5
    mov.l   .L_pool_06023568, r3
    mov.l   .L_pool_06023564, r6
    jsr @r3
    mov r10, r4
    add #0x1, r14
    extu.w r8, r3
    extu.w r14, r2
    cmp/ge r3, r2
    bf/s    .L_0602341A
    add #0xC, r10
.L_060234D8:
    extu.b r12, r14
    mov r14, r3
    shll2 r14
    shll2 r3
    shll r3
    add r3, r14
    extu.b r14, r14
    add r9, r14
    mov.l @(4, r14), r14
    tst r14, r14
    bf      .L_060234F2
    bra     .L_0602354C
    nop
.L_060234F2:
    extu.b r12, r8
    mov r8, r3
    shll2 r8
    shll2 r3
    shll r3
    add r3, r8
    extu.b r8, r8
    add r9, r8
    mov.w @(10, r8), r0
    mov r0, r8
    extu.w r12, r0
    cmp/eq #0x13, r0
    bf      .L_0602350E
    add #0x53, r11
.L_0602350E:
    extu.w r8, r2
    cmp/pl r2
    bf/s    .L_0602352A
    mov #0x0, r10
.L_06023516:
    extu.w r11, r5
    mov.l   .L_pool_0602356C, r3
    jsr @r3
    mov r14, r4
    add #0x1, r10
    extu.w r8, r3
    extu.w r10, r2
    cmp/ge r3, r2
    bf/s    .L_06023516
    add #0x6, r14
.L_0602352A:
    extu.w r12, r0
    cmp/eq #0x14, r0
    bf      .L_06023534
    mov.l   .L_pool_06023570, r3
    mov.w r11, @r3
.L_06023534:
    extu.w r12, r2
    mov #0x13, r3
    cmp/ge r3, r2
    bt      .L_0602353E
    add #0xA, r11
.L_0602353E:
    add #0x1, r12
.L_06023540:
    extu.w r12, r3
    mov #0x14, r2
    cmp/gt r2, r3
    bt      .L_0602354C
    bra     .L_060233F2
    nop
.L_0602354C:
    lds.l @r15+, pr
    mov.l @r15+, r8
    mov.l @r15+, r9
    mov.l @r15+, r10
    mov.l @r15+, r11
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14
.L_wpool_0602355E:
    .2byte  0x00A9
.L_pool_06023560:
    .4byte  sym_06089E40
.L_pool_06023564:
    .4byte  0x002A8000
.L_pool_06023568:
    .4byte  vdp1_sprite_render_alt
.L_pool_0602356C:
    .4byte  sym_06007590
.L_pool_06023570:
    .4byte  sym_0607886C
