/* race_state_pair_2 -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x06019058 - 0x0601905C
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_06019058


    .global race_state_pair_2
    .type race_state_pair_2, @function
race_state_pair_2:
    mov.l r14, @-r15
    mov #0x0, r3
