/* render_pass_extra -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x06007A50 - 0x06007BCC
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_06007A50


    .global render_pass_extra
    .type render_pass_extra, @function
render_pass_extra:
    mov.l r14, @-r15
    mov.l r13, @-r15
    mov.l r12, @-r15
    mov.l r11, @-r15
    mov.l r10, @-r15
    mov.l r8, @-r15
    sts.l pr, @-r15
    add #-0x8, r15
    mov.l   .L_pool_06007AA4, r5
    mov.w   DAT_06007a92, r4
    mov.w   DAT_06007a94, r0
    mov.l @r5, r3
    mov.l @(r0, r3), r2
    cmp/gt r4, r2
    bf      .L_06007A72
    bra     .L_06007A78
    mov r4, r13
.L_06007A72:
    mov.l @r5, r13
    mov.w   DAT_06007a94, r0
    mov.l @(r0, r13), r13
.L_06007A78:
    mov.l   .L_pool_06007AA8, r14
    mov.l   .L_pool_06007AAC, r5
    jsr @r14
    mov r13, r4
    mov.w   DAT_06007a96, r4
    add r0, r4
    mov.l   .L_pool_06007AB0, r0
    mov.b @r0, r0
    extu.b r0, r0
    tst r0, r0
    bt      .L_06007AB4
    bra     .L_06007AB6
    mov #0x24, r11

    .global DAT_06007a92
DAT_06007a92:
    .2byte  0x2134

    .global DAT_06007a94
DAT_06007a94:
    .2byte  0x00E4

    .global DAT_06007a96
DAT_06007a96:
    .2byte  0x7000
    .4byte  sym_06026CE0
    .4byte  sym_06059F44
    .4byte  sym_0606BDF8
.L_pool_06007AA4:
    .4byte  sym_0607E944
.L_pool_06007AA8:
    .4byte  fpmul
.L_pool_06007AAC:
    .4byte  0x0000D1B7
.L_pool_06007AB0:
    .4byte  sym_06085FF4
.L_06007AB4:
    mov #0x34, r11
.L_06007AB6:
    mov r15, r6
    mov.l   .L_pool_06007B9C, r3
    add #0x4, r6
    jsr @r3
    mov r15, r5
    mov.l   .L_pool_06007BA0, r12
    mov.l   .L_pool_06007BA4, r13
    mov.l   .L_pool_06007BA8, r4
    jsr @r14
    mov.l @r15, r5
    jsr @r12
    neg r0, r4
    add #0x8, r0
    exts.w r0, r0
    mov.w r0, @(8, r13)
    mov.l   .L_pool_06007BA8, r4
    jsr @r14
    mov.l @(4, r15), r5
    jsr @r12
    mov r0, r4
    add r11, r0
    exts.w r0, r0
    mov.w r0, @(10, r13)
    mov.l   .L_pool_06007BAC, r10
    mov.l   .L_pool_06007BB0, r4
    jsr @r14
    mov.l @(4, r15), r5
    mov r0, r8
    mov.l @r15, r5
    jsr @r14
    mov r10, r4
    mov r8, r4
    jsr @r12
    sub r0, r4
    add #0x8, r0
    exts.w r0, r0
    mov.w r0, @(12, r13)
    mov.l   .L_pool_06007BB0, r4
    jsr @r14
    mov.l @r15, r5
    mov r0, r8
    mov.l @(4, r15), r5
    jsr @r14
    mov r10, r4
    mov r8, r4
    jsr @r12
    add r0, r4
    add r11, r0
    exts.w r0, r0
    mov.w r0, @(14, r13)
    mov.l   .L_pool_06007BB4, r4
    jsr @r14
    mov.l @r15, r5
    jsr @r12
    neg r0, r4
    add #0x8, r0
    exts.w r0, r0
    mov.w r0, @(16, r13)
    mov.l   .L_pool_06007BB4, r4
    jsr @r14
    mov.l @(4, r15), r5
    jsr @r12
    mov r0, r4
    add r11, r0
    exts.w r0, r0
    mov.w r0, @(18, r13)
    mov.l   .L_pool_06007BB8, r4
    jsr @r14
    mov.l @(4, r15), r5
    mov r0, r8
    mov.l @r15, r5
    jsr @r14
    mov r10, r4
    mov r8, r4
    jsr @r12
    sub r0, r4
    add #0x8, r0
    exts.w r0, r0
    mov.w r0, @(20, r13)
    mov.l   .L_pool_06007BB8, r4
    jsr @r14
    mov.l @r15, r5
    mov r0, r8
    mov.l @(4, r15), r5
    jsr @r14
    mov r10, r4
    mov r8, r4
    jsr @r12
    add r0, r4
    add r11, r0
    mov.w r0, @(22, r13)
    mov.l   .L_pool_06007BBC, r0
    mov.w r0, @(6, r13)
    mov.l   .L_pool_06007BC0, r14
    mov.l   .L_pool_06007BC4, r3
    mov.l @r14, r5
    jsr @r3
    mov r13, r4
    mov.l   .L_pool_06007BC8, r4
    mov.l @r4, r2
    add #0x1, r2
    mov.l r2, @r4
    mov.l @r14, r3
    add #0x20, r3
    mov.l r3, @r14
    add #0x8, r15
    lds.l @r15+, pr
    mov.l @r15+, r8
    mov.l @r15+, r10
    mov.l @r15+, r11
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14
    .2byte  0xFFFF
.L_pool_06007B9C:
    .4byte  sincos_pair
.L_pool_06007BA0:
    .4byte  swap_sign_ext
.L_pool_06007BA4:
    .4byte  sym_06078604
.L_pool_06007BA8:
    .4byte  0x00970000
.L_pool_06007BAC:
    .4byte  0x00900000
.L_pool_06007BB0:
    .4byte  0x00020000
.L_pool_06007BB4:
    .4byte  0x00890000
.L_pool_06007BB8:
    .4byte  0xFFFE0000
.L_pool_06007BBC:
    .4byte  0x0000A3FF
.L_pool_06007BC0:
    .4byte  sym_060785FC
.L_pool_06007BC4:
    .4byte  sym_060280C4
.L_pool_06007BC8:
    .4byte  sym_0605A008
