/* render_pass_extra -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x060078DC - 0x06007CEC
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_060078DC


    .global frame_end_commit
    .type frame_end_commit, @function
frame_end_commit:
    mov.l r14, @-r15
    mov.l r13, @-r15
    mov.l r12, @-r15
    mov.l r11, @-r15
    mov.l r10, @-r15
    mov.l r9, @-r15
    sts.l pr, @-r15
    mov.w   DAT_060079ce, r9
    mov.l   .L_pool_060079D4, r10
    mov.l   .L_pool_060079D8, r12
    mov.l   .L_pool_060079DC, r13
    mov.l   .L_pool_060079E0, r14
    mov.l @r13, r3
    sub r9, r3
    mov.l r3, @r13
    mov.l @r14, r2
    cmp/hs r9, r2
    bt      .L_0600793C
    mov.l @r13, r6
    mov.l   .L_pool_060079E4, r5
    mov.l @r14, r4
    mov r6, r2
    extu.w r4, r4
    shll2 r6
    shll2 r2
    mov r4, r3
    shll r6
    shll2 r2
    shll2 r4
    shll2 r3
    add r2, r6
    shll r4
    shll2 r3
    mov.l   .L_pool_060079E8, r2
    add r3, r4
    extu.w r4, r4
    mov.l   .L_pool_060079EC, r3
    jsr @r3
    add r2, r4
    mov.l @r13, r6
    mov.w   .L_wpool_060079D0, r5
    mov.l @r14, r4
    mov.l   .L_pool_060079F0, r3
    shll r6
    add r10, r5
    shll r4
    jsr @r3
    add r10, r4
.L_0600793C:
    mov.l @r13, r2
    mov r10, r5
    mov.l @r14, r3
    add r2, r3
    mov.l r3, @r14
    mov.l r9, @r13
    mov.l   .L_pool_060079F4, r3
    jsr @r3
    mov.l @r14, r4
    mov #0x20, r6
    mov.l   .L_pool_060079FC, r5
    mov.l   .L_pool_060079F8, r11
    mov.l   .L_pool_06007A00, r3
    mov.l   .L_pool_06007A04, r2
    mov.w @r5, r5
    shll2 r5
    shll2 r5
    shll r5
    add r3, r5
    jsr @r2
    mov.l @r11, r4
    mov.l   .L_pool_06007A08, r3
    mov.l   .L_pool_06007A0C, r2
    mov.l r3, @r2
    mov.l @r12, r3
    add #0x1, r3
    mov.l r3, @r12
    bsr     vdp1_sprite_builder
    nop
    mov #0x1, r2
    mov.l   .L_pool_06007A10, r3
    mov.l r2, @r3
    mov.l   .L_pool_06007A14, r3
    jsr @r3
    nop
    mov.l @r12, r6
    mov.l   .L_pool_06007A08, r5
    mov.l @r11, r4
    mov.l   .L_pool_06007A04, r3
    add #-0x1, r6
    shll2 r6
    shll2 r6
    shll r6
    jsr @r3
    add #0x20, r4
    mov.l @r12, r0
    mov.l @r11, r3
    mov.l   .L_pool_06007A18, r2
    shll2 r0
    shll2 r0
    shll r0
    add r3, r0
    mov.w r2, @r0
    mov.l   .L_pool_06007A1C, r4
    mov.l   .L_pool_06007A20, r3
    mov.l @r4, r2
    or r3, r2
    mov r2, r0
    or #0x4, r0
    mov.l r0, @r4
    mov.l   .L_pool_06007A24, r0
    mov.l @r0, r0
    tst r0, r0
    bf      .L_060079C4
    mov.l   .L_pool_06007A28, r3
    mov.l @r4, r2
    or r3, r2
    mov.l r2, @r4
.L_060079C4:
    mov #0x0, r11
    mov.l   .L_pool_06007A10, r3
    mov.l r11, @r3
    bra     .L_06007A2C
    nop

    .global DAT_060079ce
DAT_060079ce:
    .2byte  0x0258
.L_wpool_060079D0:
    .2byte  0x04B0
    .2byte  0xFFFF
.L_pool_060079D4:
    .4byte  sym_0606A4F8
.L_pool_060079D8:
    .4byte  sym_0605A008
.L_pool_060079DC:
    .4byte  sym_060620D4
.L_pool_060079E0:
    .4byte  sym_060620D0
.L_pool_060079E4:
    .4byte  sym_0608E460
.L_pool_060079E8:
    .4byte  sym_0608AC20
.L_pool_060079EC:
    .4byte  memcpy_long_idx
.L_pool_060079F0:
    .4byte  memcpy_word_idx
.L_pool_060079F4:
    .4byte  sym_0602C494
.L_pool_060079F8:
    .4byte  sym_06063F5C
.L_pool_060079FC:
    .4byte  sym_0605A016
.L_pool_06007A00:
    .4byte  sym_0605A018
.L_pool_06007A04:
    .4byte  dma_transfer
.L_pool_06007A08:
    .4byte  sym_0606BDFC
.L_pool_06007A0C:
    .4byte  sym_060785FC
.L_pool_06007A10:
    .4byte  sym_0605A00C
.L_pool_06007A14:
    .4byte  sym_060394C2
.L_pool_06007A18:
    .4byte  0x00008000
.L_pool_06007A1C:
    .4byte  sym_0605B6D8
.L_pool_06007A20:
    .4byte  0x20000000
.L_pool_06007A24:
    .4byte  sym_0607EAE0
.L_pool_06007A28:
    .4byte  0x08000000
.L_06007A2C:
    mov.l   .L_pool_06007A98, r3
    jsr @r3
    nop
    mov.l r11, @r14
    mov.l r11, @r12
    mov.l   .L_pool_06007A9C, r4
    mov.l   .L_pool_06007AA0, r3
    mov.l @r4, r2
    mov.l r2, @r3
    mov.l r11, @r4
    lds.l @r15+, pr
    mov.l @r15+, r9
    mov.l @r15+, r10
    mov.l @r15+, r11
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14

    .global render_pass_extra
    .type render_pass_extra, @function
render_pass_extra:
    mov.l r14, @-r15
    mov.l r13, @-r15
    mov.l r12, @-r15
    mov.l r11, @-r15
    mov.l r10, @-r15
    mov.l r8, @-r15
    sts.l pr, @-r15
    add #-0x8, r15
    mov.l   .L_pool_06007AA4, r5
    mov.w   DAT_06007a92, r4
    mov.w   DAT_06007a94, r0
    mov.l @r5, r3
    mov.l @(r0, r3), r2
    cmp/gt r4, r2
    bf      .L_06007A72
    bra     .L_06007A78
    mov r4, r13
.L_06007A72:
    mov.l @r5, r13
    mov.w   DAT_06007a94, r0
    mov.l @(r0, r13), r13
.L_06007A78:
    mov.l   .L_pool_06007AA8, r14
    mov.l   .L_pool_06007AAC, r5
    jsr @r14
    mov r13, r4
    mov.w   DAT_06007a96, r4
    add r0, r4
    mov.l   .L_pool_06007AB0, r0
    mov.b @r0, r0
    extu.b r0, r0
    tst r0, r0
    bt      .L_06007AB4
    bra     .L_06007AB6
    mov #0x24, r11

    .global DAT_06007a92
DAT_06007a92:
    .2byte  0x2134

    .global DAT_06007a94
DAT_06007a94:
    .2byte  0x00E4

    .global DAT_06007a96
DAT_06007a96:
    .2byte  0x7000
.L_pool_06007A98:
    .4byte  sym_06026CE0
.L_pool_06007A9C:
    .4byte  sym_06059F44
.L_pool_06007AA0:
    .4byte  sym_0606BDF8
.L_pool_06007AA4:
    .4byte  sym_0607E944
.L_pool_06007AA8:
    .4byte  fpmul
.L_pool_06007AAC:
    .4byte  0x0000D1B7
.L_pool_06007AB0:
    .4byte  sym_06085FF4
.L_06007AB4:
    mov #0x34, r11
.L_06007AB6:
    mov r15, r6
    mov.l   .L_pool_06007B9C, r3
    add #0x4, r6
    jsr @r3
    mov r15, r5
    mov.l   .L_pool_06007BA0, r12
    mov.l   .L_pool_06007BA4, r13
    mov.l   .L_pool_06007BA8, r4
    jsr @r14
    mov.l @r15, r5
    jsr @r12
    neg r0, r4
    add #0x8, r0
    exts.w r0, r0
    mov.w r0, @(8, r13)
    mov.l   .L_pool_06007BA8, r4
    jsr @r14
    mov.l @(4, r15), r5
    jsr @r12
    mov r0, r4
    add r11, r0
    exts.w r0, r0
    mov.w r0, @(10, r13)
    mov.l   .L_pool_06007BAC, r10
    mov.l   .L_pool_06007BB0, r4
    jsr @r14
    mov.l @(4, r15), r5
    mov r0, r8
    mov.l @r15, r5
    jsr @r14
    mov r10, r4
    mov r8, r4
    jsr @r12
    sub r0, r4
    add #0x8, r0
    exts.w r0, r0
    mov.w r0, @(12, r13)
    mov.l   .L_pool_06007BB0, r4
    jsr @r14
    mov.l @r15, r5
    mov r0, r8
    mov.l @(4, r15), r5
    jsr @r14
    mov r10, r4
    mov r8, r4
    jsr @r12
    add r0, r4
    add r11, r0
    exts.w r0, r0
    mov.w r0, @(14, r13)
    mov.l   .L_pool_06007BB4, r4
    jsr @r14
    mov.l @r15, r5
    jsr @r12
    neg r0, r4
    add #0x8, r0
    exts.w r0, r0
    mov.w r0, @(16, r13)
    mov.l   .L_pool_06007BB4, r4
    jsr @r14
    mov.l @(4, r15), r5
    jsr @r12
    mov r0, r4
    add r11, r0
    exts.w r0, r0
    mov.w r0, @(18, r13)
    mov.l   .L_pool_06007BB8, r4
    jsr @r14
    mov.l @(4, r15), r5
    mov r0, r8
    mov.l @r15, r5
    jsr @r14
    mov r10, r4
    mov r8, r4
    jsr @r12
    sub r0, r4
    add #0x8, r0
    exts.w r0, r0
    mov.w r0, @(20, r13)
    mov.l   .L_pool_06007BB8, r4
    jsr @r14
    mov.l @r15, r5
    mov r0, r8
    mov.l @(4, r15), r5
    jsr @r14
    mov r10, r4
    mov r8, r4
    jsr @r12
    add r0, r4
    add r11, r0
    mov.w r0, @(22, r13)
    mov.l   .L_pool_06007BBC, r0
    mov.w r0, @(6, r13)
    mov.l   .L_pool_06007BC0, r14
    mov.l   .L_pool_06007BC4, r3
    mov.l @r14, r5
    jsr @r3
    mov r13, r4
    mov.l   .L_pool_06007BC8, r4
    mov.l @r4, r2
    add #0x1, r2
    mov.l r2, @r4
    mov.l @r14, r3
    add #0x20, r3
    mov.l r3, @r14
    add #0x8, r15
    lds.l @r15+, pr
    mov.l @r15+, r8
    mov.l @r15+, r10
    mov.l @r15+, r11
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14
    .2byte  0xFFFF
.L_pool_06007B9C:
    .4byte  sincos_pair
.L_pool_06007BA0:
    .4byte  swap_sign_ext
.L_pool_06007BA4:
    .4byte  sym_06078604
.L_pool_06007BA8:
    .4byte  0x00970000
.L_pool_06007BAC:
    .4byte  0x00900000
.L_pool_06007BB0:
    .4byte  0x00020000
.L_pool_06007BB4:
    .4byte  0x00890000
.L_pool_06007BB8:
    .4byte  0xFFFE0000
.L_pool_06007BBC:
    .4byte  0x0000A3FF
.L_pool_06007BC0:
    .4byte  sym_060785FC
.L_pool_06007BC4:
    .4byte  sym_060280C4
.L_pool_06007BC8:
    .4byte  sym_0605A008

    .global vdp1_sprite_builder
    .type vdp1_sprite_builder, @function
vdp1_sprite_builder:
    mov.l r14, @-r15
    mov #0x0, r4
    mov.l r13, @-r15
    mov.l r12, @-r15
    mov.l r11, @-r15
    mov.l r10, @-r15
    mov.l r9, @-r15
    mov.l r8, @-r15
    sts.l pr, @-r15
    mov.l   .L_pool_06007CAC, r8
    mov.l   .L_pool_06007CB0, r9
    mov.l   .L_pool_06007CB4, r10
    mov.l   .L_pool_06007CB8, r13
    mov.l   .L_pool_06007CBC, r14
    mov.l   .L_pool_06007CC0, r3
    mov.l r4, @r3
    mov.l   .L_pool_06007CC4, r5
    mov.l   .L_pool_06007CC8, r0
    mov.w @r0, r0
    extu.w r0, r0
    tst #0x8, r0
    bt      .L_06007C00
    mov #0x1, r3
    mov.l r3, @r5
    bra     .L_06007C02
    nop
.L_06007C00:
    mov.l r4, @r5
.L_06007C02:
    mov.l   .L_pool_06007CC0, r11
    bra     .L_06007C6A
    mov.l @r11, r11
.L_06007C08:
    mov r11, r12
    mov.l   .L_pool_06007CCC, r3
    shll r12
    add r3, r12
    mov.w @r12, r12
    extu.w r12, r12
    extu.w r12, r0
    mov r0, r2
    shll2 r0
    shll2 r2
    shll r0
    shll2 r2
    add r2, r0
    extu.w r0, r0
    add r13, r0
    mov.w @(6, r0), r0
    extu.w r0, r0
    cmp/eq #0x9, r0
    bf      .L_06007C4C
    mov r10, r6
    extu.w r12, r4
    mov.l @r14, r5
    mov r4, r3
    shll2 r4
    shll2 r3
    shll r4
    shll2 r3
    add r3, r4
    extu.w r4, r4
    mov.l   .L_pool_06007CD0, r3
    jsr @r3
    add r13, r4
    bra     .L_06007C62
    nop
.L_06007C4C:
    mov.l @r14, r5
    extu.w r12, r4
    mov r4, r3
    shll2 r4
    shll2 r3
    shll r4
    shll2 r3
    add r3, r4
    extu.w r4, r4
    jsr @r8
    add r13, r4
.L_06007C62:
    add #0x1, r11
    mov.l @r14, r2
    add #0x20, r2
    mov.l r2, @r14
.L_06007C6A:
    mov.l @r9, r3
    cmp/hs r3, r11
    bf      .L_06007C08
    mov.l   .L_pool_06007CD4, r4
    mov.l @r9, r3
    mov.l @r4, r2
    add r3, r2
    mov.l r2, @r4
    mov.l   .L_pool_06007CD8, r3
    mov.l   .L_pool_06007CDC, r2
    mov.l @r3, r3
    and r2, r3
    tst r3, r3
    bt      .L_06007C90
    mov.l   .L_pool_06007CE0, r3
    jsr @r3
    nop
    bsr     render_pass_extra
    nop
.L_06007C90:
    mov.l   .L_pool_06007CE4, r3
    jsr @r3
    nop
    lds.l @r15+, pr
    mov.l @r15+, r8
    mov.l @r15+, r9
    mov.l @r15+, r10
    mov.l @r15+, r11
    mov.l @r15+, r12
    mov.l @r15+, r13
    mov.l   .L_pool_06007CE8, r3
    jmp @r3
    mov.l @r15+, r14
    .2byte  0xFFFF
.L_pool_06007CAC:
    .4byte  sym_060280F8
.L_pool_06007CB0:
    .4byte  sym_060620D0
.L_pool_06007CB4:
    .4byte  0x00008000
.L_pool_06007CB8:
    .4byte  sym_0608AC20
.L_pool_06007CBC:
    .4byte  sym_060785FC
.L_pool_06007CC0:
    .4byte  sym_06078620
.L_pool_06007CC4:
    .4byte  sym_0607861C
.L_pool_06007CC8:
    .4byte  sym_06063DA0
.L_pool_06007CCC:
    .4byte  sym_0606A4F8
.L_pool_06007CD0:
    .4byte  sym_060281B8
.L_pool_06007CD4:
    .4byte  sym_0605A008
.L_pool_06007CD8:
    .4byte  sym_0607EBC4
.L_pool_06007CDC:
    .4byte  0x20228000
.L_pool_06007CE0:
    .4byte  sym_060333D8
.L_pool_06007CE4:
    .4byte  post_sprite_cleanup
.L_pool_06007CE8:
    .4byte  vdp2_frame_update
