/* scene_3d_processor -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x06027CA4 - 0x06027EDE
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_06027CA4


    .global scene_3d_processor
    .type scene_3d_processor, @function
scene_3d_processor:
    mov.l r14, @-r15
    mov.l r13, @-r15
    mov.l r12, @-r15
    mov.l r11, @-r15
    mov.l r10, @-r15
    mov.l r9, @-r15
    mov.l r8, @-r15
    sts.l pr, @-r15
    mov.l r5, @-r15
    mov.l @r4, r1
    mov.l   .L_cart_cs1_00000, r2
    add r2, r1
    shlr16 r1
    shlr2 r1
    shlr2 r1
    shlr r1
    mov.l @(8, r4), r2
    mov.l   .L_cart_cs0_1ffffff, r3
    sub r2, r3
    shlr16 r3
    shlr2 r3
    shlr2 r3
    shlr r3
    shll2 r3
    shll2 r3
    shll2 r3
    add r3, r1
    mov.l   .L_sym_0607EAD8, r2
    mov.l @r2, r0
    cmp/eq #0x2, r0
    bf      .L_06027D40
    mov.l r1, @-r15
    mov r1, r10
    mov.l   .L_sym_06061270, r1
    xor r12, r12
.L_06027CEA:
    mov.w @r1+, r0
    tst r0, r0
    bt      .L_06027D34
    cmp/eq r0, r10
    bt      .L_06027D08
    bra     .L_06027CEA
    add #0x2, r12
.L_cart_cs1_00000:
    .4byte  0x04000000
.L_cart_cs0_1ffffff:
    .4byte  0x03FFFFFF
.L_sym_0607EAD8:
    .4byte  sym_0607EAD8
.L_sym_06061270:
    .4byte  sym_06061270
.L_06027D08:
    mov.l   .L_sym_0607E940, r1
    mov.l @r1, r1
    mov.w   DAT_06027d26, r0
    mov.l @(r0, r1), r1
    mov #0x46, r0
    cmp/gt r0, r1
    bt      .L_06027D34
    shll r12
    mov.l   .L_sym_06061240, r0
    add r12, r0
    mov.l   .L_sym_06063F50, r1
    mov.w @r0+, r2
    mov.w @r0, r12
    bra     .L_06027D36
    mov.w r2, @r1

    .global DAT_06027d26
DAT_06027d26:
    .2byte  0x01EC
.L_sym_0607E940:
    .4byte  sym_0607E940
.L_sym_06061240:
    .4byte  sym_06061240
.L_sym_06063F50:
    .4byte  sym_06063F50
.L_06027D34:
    xor r12, r12
.L_06027D36:
    mov.l @r15+, r1
    tst r12, r12
    bt      .L_06027D40
    bra     .L_06027D50
    mov r2, r13
.L_06027D40:
    mov r1, r2
    shll2 r2
    mov.l   .L_sym_060C2000, r0
    add r0, r2
    mov.w @r2, r13
    extu.w r13, r13
    mov.w @(2, r2), r0
    mov r0, r12
.L_06027D50:
    cmp/pl r12
    bt      .L_06027D60
    mov #0x0, r0
    mov r0, r3
    bra     .L_06027E6A
    mov #0x0, r6
.L_sym_060C2000:
    .4byte  sym_060C2000
.L_06027D60:
    mov.l   .L_sym_060BF000, r0
    mov.w @(r0, r13), r5
    mov #0x34, r6
    mov.l   .L_sym_060A6000, r0
    muls.w r6, r5
    sts macl, r5
    add r5, r0
    mov.l @r0, r6
    add #0x10, r0
    mov #0x1, r14
    mov.l @r0+, r7
    shll16 r14
    mov.l @r4, r2
    shll8 r14
    dmuls.l r7, r2
    mov.l @r0+, r9
    mov.l @(8, r4), r10
    sts mach, r2
    sts macl, r3
    xtrct r2, r3
    tst r14, r6
    add r9, r3
    bf      .L_06027D90
    add r10, r3
.L_06027D90:
    mov.w   .L_wpool_06027DA0, r11
    tst r11, r6
    bt      .L_06027DAC
    cmp/pl r3
    bf      .L_06027DB6
    add #0x2, r13
    bra     .L_06027D50
    add #-0x1, r12
.L_wpool_06027DA0:
    .2byte  0x0100
    .2byte  0x0000
.L_sym_060BF000:
    .4byte  sym_060BF000
.L_sym_060A6000:
    .4byte  sym_060A6000
.L_06027DAC:
    cmp/pz r3
    bt      .L_06027DB6
    add #0x2, r13
    bra     .L_06027D50
    add #-0x1, r12
.L_06027DB6:
    mov r4, r1
    mov.l @r0+, r7
    mov.l @r1, r2
    shll r14
    dmuls.l r7, r2
    mov.l @r0+, r9
    mov.l @(8, r4), r10
    sts mach, r2
    sts macl, r3
    xtrct r2, r3
    tst r14, r6
    add r9, r3
    bf      .L_06027DD2
    add r10, r3
.L_06027DD2:
    mov.w   .L_wpool_06027DE2, r11
    tst r11, r6
    bt      .L_06027DE4
    cmp/pl r3
    bf      .L_06027DEE
    add #0x2, r13
    bra     .L_06027D50
    add #-0x1, r12
.L_wpool_06027DE2:
    .2byte  0x0200
.L_06027DE4:
    cmp/pz r3
    bt      .L_06027DEE
    add #0x2, r13
    bra     .L_06027D50
    add #-0x1, r12
.L_06027DEE:
    mov.l @r0+, r7
    mov.l @r4, r2
    shll r14
    dmuls.l r7, r2
    mov.l @r0+, r9
    mov.l @(8, r4), r10
    sts mach, r2
    sts macl, r3
    xtrct r2, r3
    tst r14, r6
    add r9, r3
    bf      .L_06027E08
    add r10, r3
.L_06027E08:
    mov.w   .L_wpool_06027E18, r10
    tst r10, r6
    bt      .L_06027E1A
    cmp/pl r3
    bf      .L_06027E24
    add #0x2, r13
    bra     .L_06027D50
    add #-0x1, r12
.L_wpool_06027E18:
    .2byte  0x0400
.L_06027E1A:
    cmp/pz r3
    bt      .L_06027E24
    add #0x2, r13
    bra     .L_06027D50
    add #-0x1, r12
.L_06027E24:
    mov.l @r0+, r7
    mov.l @r4, r2
    shll r14
    dmuls.l r7, r2
    mov.l @r0+, r9
    mov.l @(8, r4), r10
    sts mach, r2
    sts macl, r3
    xtrct r2, r3
    tst r14, r6
    add r9, r3
    bf      .L_06027E3E
    add r10, r3
.L_06027E3E:
    mov.l   .L_pool_06027E50, r10
    tst r10, r6
    bt      .L_06027E54
    cmp/pl r3
    bf      .L_06027E5E
    add #0x2, r13
    bra     .L_06027D50
    add #-0x1, r12
    .2byte  0x0000
.L_pool_06027E50:
    .4byte  0x00000800
.L_06027E54:
    cmp/pz r3
    bt      .L_06027E5E
    add #0x2, r13
    bra     .L_06027D50
    add #-0x1, r12
.L_06027E5E:
    mov.l   .L_sym_060A6000_2, r1
    add r5, r1
    mov.l @r1, r3
    mov.w   DAT_06027e98, r6
    and r6, r3
    mov r3, r0
.L_06027E6A:
    mov.w r0, @(12, r4)
    mov #0x0, r0
    cmp/eq r0, r6
    bt      .L_06027EA8
    add #0x30, r1
    mov.w @r1, r0
    mov.l r0, @(16, r4)
    mov r0, r8
    mov r5, r1
    mov #0x34, r0
    mov.l   .L_sym_0602ECCC, r12
    jsr @r12
    mov.l r3, @-r15
    mov.l @r15+, r3
    mov.w r0, @(14, r4)
    mov.l   .L_sym_0607E940_2, r6
    mov.l @r6, r0
    mov.l @r15+, r5
    cmp/pl r5
    bt      .L_06027EAE
    mov.w   DAT_06027e9a, r1
    bra     .L_06027EAE
    mov.l r8, @(r0, r1)

    .global DAT_06027e98
DAT_06027e98:
    .2byte  0x00FF

    .global DAT_06027e9a
DAT_06027e9a:
    .2byte  0x025C
.L_sym_060A6000_2:
    .4byte  sym_060A6000
.L_sym_0602ECCC:
    .4byte  sym_0602ECCC
.L_sym_0607E940_2:
    .4byte  sym_0607E940
.L_06027EA8:
    mov.l   .L_sym_0607E940_3, r6
    mov.l @r6, r0
    mov.l @r15+, r5
.L_06027EAE:
    shll r5
    mov.l   .L_sym_0606128A, r2
    add r5, r2
    mov.w @r2, r2
    extu.w r2, r2
    mov.l r3, @(r0, r2)
    lds.l @r15+, pr
    mov.l @r15+, r8
    mov.l @r15+, r9
    mov.l @r15+, r10
    mov.l @r15+, r11
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14
.L_sym_0607E940_3:
    .4byte  sym_0607E940
.L_sym_0606128A:
    .4byte  sym_0606128A
    .4byte  0x00093600
    .4byte  0x89FCAFD5
    .2byte  0x0009
