/* score_commit_save -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x06013E14 - 0x06013E3C
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_06013E14


    .global score_commit_save
    .type score_commit_save, @function
score_commit_save:
    mov.l r14, @-r15                       ! save r14
    mov.l   .L_direction_state, r0         ! r0 = &direction_state
    mov.l @r0, r0                          ! r0 = direction_state value
    and #0x1F, r0                          ! mask to 5-bit direction index
    exts.w r0, r14                         ! sign-extend to 32-bit
    cmp/gt r2, r14                         ! if direction > threshold (r2)?
    bf      .L_below_threshold             ! no — skip rotation, return
    shll8 r14                              ! direction << 8
    shll2 r14                              ! direction << 10
    shll2 r14                              ! direction << 12 (fixed-point angle)
    exts.w r14, r4                         ! r4 = angle argument (sign-extended)
    mov.l   .L_fn_mat_rot_y, r3           ! r3 = &mat_rot_y
    jmp @r3                                ! tail-call mat_rot_y(angle)
    mov.l @r15+, r14                       ! (delay slot) restore r14
.L_below_threshold:
    rts                                    ! return — no rotation applied
    mov.l @r15+, r14                       ! (delay slot) restore r14
.L_direction_state:
    .4byte  sym_0607EBC8
.L_fn_mat_rot_y:
    .4byte  mat_rot_y
