/* sound_timer_init -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x06003218 - 0x060032D4
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_06003218


    .global sound_timer_init
    .type sound_timer_init, @function
sound_timer_init:
    sts.l pr, @-r15
    mov.l   .L_pool_060032C0, r3
    mov.l   .L_pool_060032C4, r5
    mov.l @r3, r3
    jsr @r3
    mov #0x65, r4
    mov.w   .L_wpool_060032B2, r5
    mov.b @r5, r4
    mov #0xF, r2
    and r2, r4
    extu.b r4, r0
    or #0x8, r0
    extu.b r0, r0
    mov.b r0, @r5
    mov.w   .L_wpool_060032B4, r6
    mov.b @r6, r4
    mov #0x1, r5
    extu.b r4, r4
    or r5, r4
    extu.b r4, r4
    mov.b r4, @r6
    mov.w   .L_wpool_060032B6, r4
    mov.b @r4, r3
    extu.b r3, r3
    mov #-0x4, r2
    and r2, r3
    mov.b r3, @r4
    add #0x1, r4
    mov.b @r4, r3
    extu.b r3, r3
    mov #-0x11, r2
    and r2, r3
    extu.b r3, r3
    mov.b r3, @r4
    mov.w   .L_wpool_060032B8, r3
    mov.b r5, @r3
    mov #0x66, r2
    add #0x1, r3
    mov #0x0, r4
    mov.b r2, @r3
    add #-0x3, r3
    mov.b r4, @r3
    add #0x1, r3
    lds.l @r15+, pr
    rts
    mov.b r4, @r3

    .global vdp_init_dispatch
    .type vdp_init_dispatch, @function
vdp_init_dispatch:
    mov.l r14, @-r15
    sts.l pr, @-r15
    mov.l   .L_pool_060032C0, r14
    mov.l   .L_pool_060032C8, r5
    mov.l @r14, r3
    jsr @r3
    mov #0x4, r4
    mov.l @r14, r2
    mov.l   .L_pool_060032CC, r5
    jsr @r2
    mov #0x6, r4
    mov.l @r14, r3
    mov.l   .L_pool_060032D0, r5
    jsr @r3
    mov #0x9, r4
    mov.l @r14, r2
    mov.l   .L_pool_060032C8, r5
    mov.w   .L_wpool_060032BA, r4
    jsr @r2
    nop
    mov.l @r14, r3
    mov.l   .L_pool_060032CC, r5
    mov.w   .L_wpool_060032BC, r4
    jsr @r3
    nop
    mov.l @r14, r2
    mov.l   .L_pool_060032D0, r5
    mov.w   .L_wpool_060032BE, r4
    lds.l @r15+, pr
    jmp @r2
    mov.l @r15+, r14
.L_wpool_060032B2:
    .2byte  0xFE10
.L_wpool_060032B4:
    .2byte  0xFE11
.L_wpool_060032B6:
    .2byte  0xFE16
.L_wpool_060032B8:
    .2byte  0xFE14
.L_wpool_060032BA:
    .2byte  0x0104
.L_wpool_060032BC:
    .2byte  0x0106
.L_wpool_060032BE:
    .2byte  0x0109
.L_pool_060032C0:
    .4byte  sym_06000310
.L_pool_060032C4:
    .4byte  sym_060072E4
.L_pool_060032C8:
    .4byte  sym_06028218
.L_pool_060032CC:
    .4byte  sym_06028230
.L_pool_060032D0:
    .4byte  sym_06028248
