/* state_snapshot_compare -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0601905C - 0x060190B8
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0601905C


    .global state_snapshot_compare
    .type state_snapshot_compare, @function
state_snapshot_compare:
    sts.l pr, @-r15
    mov.l   .L_pool_0601909C, r14
    mov.l   .L_pool_060190A0, r2
    mov.l r3, @r2
    mov.l   .L_pool_060190A4, r5
    jsr @r14
    mov #0xF, r4
    mov.l   .L_pool_060190A8, r5
    jsr @r14
    mov #0xF, r4
    .byte   0xB1, 0x3A    /* bsr 0x060192E8 (external) */
    nop
    mov.l   .L_pool_060190A0, r0
    mov.l @r0, r0
    tst r0, r0
    bf      .L_06019088
    mov.l   .L_pool_060190AC, r3
    jsr @r3
    nop
    mov #0x0, r2
    mov.l   .L_sound_ram_0x02DBE, r3
    mov.w r2, @r3
.L_06019088:
    mov.l   .L_pool_060190A4, r5
    jsr @r14
    mov #0xF, r4
    mov.l   .L_pool_060190B4, r5
    jsr @r14
    mov #0xF, r4
    lds.l @r15+, pr
    rts
    mov.l @r15+, r14
    .2byte  0xFFFF
.L_pool_0601909C:
    .4byte  sound_cmd_dispatch
.L_pool_060190A0:
    .4byte  sym_06086050
.L_pool_060190A4:
    .4byte  0xAE0001FF
.L_pool_060190A8:
    .4byte  0xAE0005FF
.L_pool_060190AC:
    .4byte  sym_06012F10
.L_sound_ram_0x02DBE:
    .4byte  0x25A02DBE                  /* Sound RAM +0x02DBE */
.L_pool_060190B4:
    .4byte  0xAE0600FF
