/* track_effect_stub -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x06036B64 - 0x06036B70
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_06036B64


    .global track_effect_stub
    .type track_effect_stub, @function
track_effect_stub:
    mov.l r14, @-r15
    mov r6, r14
    mov.l r13, @-r15
    mov r4, r13
    mov.l r12, @-r15
    mov r5, r12
