/* transition_timer_set -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x060190BC - 0x060190F4
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_060190BC


    .global transition_timer_set
    .type transition_timer_set, @function
transition_timer_set:
    sts.l pr, @-r15
    .byte   0xDE, 0x1C    /* mov.l .L_pool_06019130, r14 */
    .byte   0xD2, 0x1C    /* mov.l .L_pool_06019134, r2 */
    mov.l r3, @r2
    .byte   0xD5, 0x1C    /* mov.l .L_pool_06019138, r5 */
    jsr @r14
    mov #0xF, r4
    .byte   0xD5, 0x1C    /* mov.l .L_pool_0601913C, r5 */
    jsr @r14
    mov #0xF, r4
    .byte   0xB1, 0x0A    /* bsr 0x060192E8 (external) */
    nop
    .byte   0xD0, 0x17    /* mov.l .L_pool_06019134, r0 */
    mov.l @r0, r0
    tst r0, r0
    bf      .L_060190E8
    .byte   0xD3, 0x18    /* mov.l .L_pool_06019140, r3 */
    jsr @r3
    nop
    mov #0x0, r2
    .byte   0xD3, 0x17    /* mov.l .L_pool_06019144, r3 */
    mov.w r2, @r3
.L_060190E8:
    .byte   0xD5, 0x13    /* mov.l .L_pool_06019138, r5 */
    jsr @r14
    mov #0xF, r4
    lds.l @r15+, pr
    rts
    mov.l @r15+, r14
