/* transform_rotation_apply -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x06026362 - 0x060263EC
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_06026362


    .global transform_rotation_apply
    .type transform_rotation_apply, @function
transform_rotation_apply:
    mov.l r14, @-r15
    mov.l r13, @-r15
    mov.l r12, @-r15
    .byte   0xDC, 0x0C    /* mov.l .L_pool_0602639C, r12 */
    mov #0xA, r13
    .byte   0xDE, 0x0C    /* mov.l .L_pool_060263A0, r14 */
    .byte   0xD7, 0x0D    /* mov.l .L_pool_060263A4, r7 */
    .byte   0xD5, 0x0D    /* mov.l .L_fp_half, r5 */
    mov #0x0, r4
    extu.w r4, r6
.L_06026376:
    extu.w r6, r0
    shll2 r0
    shll r0
    add r12, r0
    mov.w @(6, r0), r0
    bra     .L_060263AC
    extu.w r0, r0
    .4byte  0xA001624D
    .4byte  0x625DA027
    .4byte  0x2E21A001
    .4byte  0x624D625D
    .4byte  0xA0222721
.L_06026398:
    bra     .L_060263DC
    nop
.L_pool_0602639C:
    .4byte  sym_06060F2C
.L_pool_060263A0:
    .4byte  sym_06060D2A
.L_pool_060263A4:
    .4byte  sym_06060D34
.L_fp_half:
    .4byte  0x00008000                  /* 0.5 (16.16 fixed-point) */
.L_060263AC:
    mov.w   .L_wpool_060263C2, r1
    sub r1, r0
    mov #0xC, r1
    cmp/hs r1, r0
    bt      .L_06026398
    shll r0
    mov r0, r1
    .word 0xC702 /* UNKNOWN */
    mov.w @(r0, r1), r0
    braf r0
    nop
.L_wpool_060263C2:
    .2byte  0x008A
    .4byte  0xFFC2FFC2
    .4byte  0xFFCCFFCC
    .4byte  0xFFC6FFC6
    .4byte  0xFFC6FFC6
    .4byte  0xFFD0FFD0
    .4byte  0xFFD0FFD0
.L_060263DC:
    add #0x1, r6
    extu.w r6, r2
    cmp/ge r13, r2
    bf      .L_06026376
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14
