/* update_mode_dispatch -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0600DF66 - 0x0600DFD0
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0600DF66


    .global update_mode_dispatch
    .type update_mode_dispatch, @function
update_mode_dispatch:
    sts.l pr, @-r15
    .byte   0xD3, 0x12    /* mov.l .L_pool_0600DFB4, r3 */
    mov.l @r3, r3
    shar r3
    exts.w r3, r3
    .byte   0xD2, 0x11    /* mov.l .L_pool_0600DFB8, r2 */
    mov.w r3, @r2
    .byte   0xD0, 0x11    /* mov.l .L_pool_0600DFBC, r0 */
    bra     .L_0600DFC0
    mov.b @r0, r0
.L_0600DF7A:
    .byte   0xB2, 0x49    /* bsr 0x0600E410 (external) */
    nop
    bra     .L_0600DFCC
    nop
.L_0600DF82:
    .byte   0xB2, 0x7B    /* bsr 0x0600E47C (external) */
    nop
    bra     .L_0600DFCC
    nop
.L_0600DF8A:
    .byte   0xB2, 0x77    /* bsr 0x0600E47C (external) */
    nop
    bra     .L_0600DFCC
    nop
    .2byte  0xFFFF
    .4byte  sym_06078635
    .4byte  sym_06063EF0
    .4byte  sym_06078634
    .4byte  sym_0600A8BC
    .4byte  sym_06083255
    .4byte  terrain_data_lookup
    .4byte  sprite_transform
    .4byte  sprite_batch_render
.L_pool_0600DFB4:
    .4byte  sym_0607EA98
.L_pool_0600DFB8:
    .4byte  sym_060786CA
.L_pool_0600DFBC:
    .4byte  sym_06083261
.L_0600DFC0:
    cmp/eq #0x0, r0
    bt      .L_0600DF7A
    cmp/eq #0x1, r0
    bt      .L_0600DF82
    cmp/eq #0x2, r0
    bt      .L_0600DF8A
.L_0600DFCC:
    .byte   0xA0, 0x78    /* bra 0x0600E0C0 (external) */
    lds.l @r15+, pr
