/* vdp2_coeff_helper_b -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0602E32C - 0x0602E338
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0602E32C


    .global vdp2_coeff_helper_b
    .type vdp2_coeff_helper_b, @function
vdp2_coeff_helper_b:
    sts.l pr, @-r15
    jsr @r13
    nop
    lds.l @r15+, pr
    nop
    .byte   0xDD, 0x15    /* mov.l .L_pool_0602E38C, r13 */
