/* vdp2_regs_setup -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x0603836C - 0x0603853C
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_0603836C


    .global vdp2_regs_setup
    .type vdp2_regs_setup, @function
vdp2_regs_setup:
    mov.l r14, @-r15
    mov.l r13, @-r15
    mov.l r12, @-r15
    mov.l   .L_mask_low16, r12
    mov #0x10, r13
    mov #0x8, r14
    mov.l   .L_pool_06038490, r7
    mov.l   .L_pool_06038494, r5
    mov #0x0, r4
    mov.l   .L_vdp2_tvmd, r3
    mov.l   .L_pool_0603849C, r2
    mov.l r3, @r2
    mov.l   .L_fp_half, r3
    mov.w r3, @r7
    extu.w r4, r2
    mov r2, r0
    mov.w r0, @(2, r7)
    extu.w r4, r0
    mov.w r0, @(6, r7)
    extu.w r4, r0
    mov.w r0, @(12, r7)
    shlr2 r3
    mov r3, r0
    mov.w r0, @(14, r7)
    extu.w r4, r6
.L_0603839E:
    extu.w r6, r3
    mov r7, r2
    extu.w r12, r1
    shll r3
    add #0x1, r6
    add #0x10, r2
    add r2, r3
    mov.w r1, @r3
    extu.w r6, r3
    cmp/ge r14, r3
    bf      .L_0603839E
    mov #0x20, r0
    mov.w r4, @(r0, r7)
    mov #0x22, r0
    mov.w r4, @(r0, r7)
    mov #0x24, r0
    mov.w r4, @(r0, r7)
    mov #0x26, r0
    mov.w r4, @(r0, r7)
    mov.w r4, @r5
    extu.w r4, r2
    mov r2, r0
    mov.w r0, @(2, r5)
    extu.w r4, r0
    mov.w r0, @(4, r5)
    extu.w r4, r0
    mov.w r0, @(6, r5)
    extu.w r4, r0
    mov.w r0, @(8, r5)
    extu.w r4, r0
    mov.w r0, @(10, r5)
    extu.w r4, r0
    mov.w r0, @(12, r5)
    extu.w r4, r0
    mov.w r0, @(14, r5)
    extu.w r4, r0
    mov.w r0, @(16, r5)
    extu.w r4, r0
    mov.w r0, @(18, r5)
    extu.w r4, r0
    mov.w r0, @(20, r5)
    extu.w r4, r3
    mov r3, r0
    mov.w r0, @(22, r5)
    extu.w r4, r6
.L_060383F8:
    extu.w r6, r3
    mov r5, r2
    extu.w r4, r1
    shll r3
    add #0x1, r6
    add #0x18, r2
    add r2, r3
    mov.w r1, @r3
    extu.w r6, r3
    cmp/ge r14, r3
    bf      .L_060383F8
    extu.w r4, r6
.L_06038410:
    extu.w r6, r3
    mov r5, r2
    extu.w r4, r1
    shll r3
    add #0x1, r6
    add #0x28, r2
    add r2, r3
    mov.w r1, @r3
    extu.w r6, r3
    cmp/ge r13, r3
    bf      .L_06038410
    mov.l   .L_pool_060384A4, r6
    mov.l r4, @r6
    mov.l r4, @(4, r6)
    mov.l   .L_fp_one, r0
    mov.l r0, @(8, r6)
    mov.l r0, @(12, r6)
    mov.l r4, @(16, r6)
    mov.l r4, @(20, r6)
    mov.l r0, @(24, r6)
    mov.l r0, @(28, r6)
    mov #0x20, r0
    mov.w r4, @(r0, r6)
    mov #0x22, r0
    mov.w r4, @(r0, r6)
    mov #0x24, r0
    mov.w r4, @(r0, r6)
    mov #0x26, r0
    mov.w r4, @(r0, r6)
    mov #0x28, r0
    mov.w r4, @(r0, r6)
    mov #0x2A, r0
    mov.w r4, @(r0, r6)
    mov.l r4, @(44, r6)
    mov r6, r3
    add #0x30, r3
    add r4, r3
    mov.l r4, @r3
    mov.l r4, @(52, r6)
    mov.l r4, @(56, r6)
    mov.l r4, @(60, r6)
    mov.l   .L_pool_060384AC, r6
    mov.w r4, @r6
    extu.w r4, r0
    mov.w r0, @(2, r6)
    extu.w r4, r0
    mov.w r0, @(4, r6)
    extu.w r4, r0
    mov.w r0, @(6, r6)
    mov r6, r3
    add #0x8, r3
    add r4, r3
    mov.w r4, @r3
    extu.w r4, r0
    mov.w r0, @(10, r6)
    mov.l r4, @(12, r6)
    mov.l   .L_pool_060384B0, r6
    mov r6, r3
    add r4, r3
    mov.w r4, @r3
    bra     .L_060384B4
    nop
.L_mask_low16:
    .4byte  0x0000FFFF                  /* low 16-bit mask */
.L_pool_06038490:
    .4byte  sym_060A3D88
.L_pool_06038494:
    .4byte  sym_060A3DB0
.L_vdp2_tvmd:
    .4byte  0x25F80000                  /* VDP2 TVMD — TV mode/display enable */
.L_pool_0603849C:
    .4byte  sym_060A3D84
.L_fp_half:
    .4byte  0x00008000                  /* 0.5 (16.16 fixed-point) */
.L_pool_060384A4:
    .4byte  sym_060A3DF8
.L_fp_one:
    .4byte  0x00010000                  /* 1.0 (16.16 fixed-point) */
.L_pool_060384AC:
    .4byte  sym_060A3E38
.L_pool_060384B0:
    .4byte  sym_060A3E48
.L_060384B4:
    extu.w r4, r0
    mov.w r0, @(2, r6)
    mov r6, r3
    add #0x4, r3
    add r4, r3
    mov.w r4, @r3
    extu.w r4, r0
    mov.w r0, @(6, r6)
    mov r6, r3
    add #0x8, r3
    add r4, r3
    mov.w r4, @r3
    extu.w r4, r0
    mov.w r0, @(10, r6)
    mov r6, r3
    add #0xC, r3
    add r4, r3
    mov.w r4, @r3
    extu.w r4, r0
    mov.w r0, @(14, r6)
    mov r6, r3
    add #0x10, r3
    add r4, r3
    extu.w r4, r2
    mov.w r2, @r3
    extu.w r4, r0
    mov.w r0, @(18, r6)
    extu.w r4, r0
    mov.w r0, @(20, r6)
    extu.w r4, r0
    mov.w r0, @(22, r6)
    mov.l r4, @(24, r6)
    mov.l r4, @(28, r6)
    mov.l   .L_pool_06038534, r6
    mov.w @r6, r3
    extu.w r3, r3
    tst r3, r3
    bf      .L_06038504
    mov #0x1, r3
    mov.w r3, @r6
.L_06038504:
    mov.l @r15+, r12
    mov.l @r15+, r13
    rts
    mov.l @r15+, r14

    .global sym_0603850C
sym_0603850C:
    mov.l   .L_pool_06038534, r5
    mov.w @r5, r0
    extu.w r0, r0
    cmp/eq #0x1, r0
    bf      .L_0603851A
    mov #0x0, r2
    mov.w r2, @r5
.L_0603851A:
    mov.l   .L_pool_06038538, r3
    rts
    mov.l r4, @r3

    .global sym_06038520
sym_06038520:
    mov.l   .L_pool_06038534, r4
    mov.w @r4, r3
    extu.w r3, r3
    tst r3, r3
    bf      .L_0603852E
    mov #0x1, r3
    mov.w r3, @r4
.L_0603852E:
    rts
    nop
    .2byte  0xFFFF
.L_pool_06038534:
    .4byte  sym_060635AC
.L_pool_06038538:
    .4byte  sym_060635A8
