/* vertex_transform_rot -- L3 assembly (SH-2 mnemonics)
 * Translation unit: 0x06011978 - 0x0601198C
 * Auto-generated by tools/generate_l3_tu.py
 */

    .section .text.FUN_06011978


    .global vertex_transform_rot
    .type vertex_transform_rot, @function
vertex_transform_rot:
    mov.l r14, @-r15
    mov.l r13, @-r15
    mov.l r12, @-r15
    mov.l r11, @-r15
    mov.l r10, @-r15
    mov r4, r11
    mov.l r9, @-r15
    mov r5, r10
    mov.l r8, @-r15
    mov r6, r9
